package main

import (
	"fmt"
	"go/format"
	"regexp"
	"strings"
)

// postProcess removes the oapi-codegen runtime dependency from generated code
// and fixes known codegen bugs.
func postProcess(src []byte) ([]byte, error) {
	s := string(src)

	s = fixPackageComment(s)
	s = removeMergeMethods(s)
	s = removeRuntimeImport(s)
	s = fixDiscriminatorPointerAssign(s)

	out, err := format.Source([]byte(s))
	if err != nil {
		return nil, fmt.Errorf("formatting post-processed source: %w", err)
	}
	return out, nil
}

// packageCommentRe matches the oapi-codegen package doc comment block and
// replaces it with a standalone generated-code marker that won't appear in
// godoc.
var packageCommentRe = regexp.MustCompile(
	`(?s)^// Package \w+ provides primitives.*?DO NOT EDIT\.\npackage (\w+)`,
)

func fixPackageComment(s string) string {
	return packageCommentRe.ReplaceAllString(s,
		"// Code generated by oapi-codegen. DO NOT EDIT.\n\npackage $1")
}

// mergeFuncRe matches entire Merge* methods including the preceding doc comment
// through the closing brace.
var mergeFuncRe = regexp.MustCompile(
	`(?ms)^// Merge\w+ performs a merge[^\n]*\n.+?\n\}\n`,
)

func removeMergeMethods(s string) string {
	return mergeFuncRe.ReplaceAllString(s, "")
}

func removeRuntimeImport(s string) string {
	s = strings.ReplaceAll(s, "\t\"github.com/oapi-codegen/runtime\"\n", "")
	s = strings.ReplaceAll(s, "\topenapi_types \"github.com/oapi-codegen/runtime/types\"\n", "")
	return s
}

// discriminatorRe matches discriminator assignments in From* methods
// (oapi-codegen#2297): v.Field = "literal" where Field is actually *string.
// We wrap with a temporary variable to take the address.
var discriminatorRe = regexp.MustCompile(
	`(func \([^)]+\) From\w+\([^)]*\) error \{\n)\t(\w+\.\w+) = (".*")`,
)

func fixDiscriminatorPointerAssign(s string) string {
	return discriminatorRe.ReplaceAllString(s, "${1}\t_v := $3\n\t$2 = &_v")
}
