package main

import (
	"fmt"
	"go/format"
	"regexp"
	"strings"
)

// postProcess removes the oapi-codegen runtime dependency from generated code
// and fixes known codegen bugs. discriminatorValues maps a Go schema name to
// the OpenAPI discriminator mapping key that should appear on the wire
// (see fixDiscriminatorValueLiteral).
func postProcess(src []byte, discriminatorValues map[string]string) ([]byte, error) {
	s := string(src)

	s = fixPackageComment(s)
	s = removeMergeMethods(s)
	s = removeRuntimeImport(s)
	s = fixDiscriminatorValueLiteral(s, discriminatorValues)
	s = fixDiscriminatorPointerAssign(s)
	s = underscoreEnumConstants(s)

	out, err := format.Source([]byte(s))
	if err != nil {
		return nil, fmt.Errorf("formatting post-processed source: %w", err)
	}
	return out, nil
}

// packageCommentRe matches the oapi-codegen package doc comment block and
// replaces it with a standalone generated-code marker that won't appear in
// godoc.
var packageCommentRe = regexp.MustCompile(
	`(?s)^// Package \w+ provides primitives.*?DO NOT EDIT\.\npackage (\w+)`,
)

func fixPackageComment(s string) string {
	return packageCommentRe.ReplaceAllString(s,
		"// Code generated by oapi-codegen. DO NOT EDIT.\n\npackage $1")
}

// mergeFuncRe matches entire Merge* methods including the preceding doc comment
// through the closing brace.
var mergeFuncRe = regexp.MustCompile(
	`(?ms)^// Merge\w+ performs a merge[^\n]*\n.+?\n\}\n`,
)

func removeMergeMethods(s string) string {
	return mergeFuncRe.ReplaceAllString(s, "")
}

func removeRuntimeImport(s string) string {
	s = strings.ReplaceAll(s, "\t\"github.com/oapi-codegen/runtime\"\n", "")
	s = strings.ReplaceAll(s, "\topenapi_types \"github.com/oapi-codegen/runtime/types\"\n", "")
	return s
}

// discriminatorRe matches discriminator assignments in From* methods
// (oapi-codegen#2297): v.Field = "literal" where Field is actually *string.
// We wrap with a temporary variable to take the address.
var discriminatorRe = regexp.MustCompile(
	`(func \([^)]+\) From\w+\([^)]*\) error \{\n)\t(\w+\.\w+) = (".*")`,
)

func fixDiscriminatorPointerAssign(s string) string {
	return discriminatorRe.ReplaceAllString(s, "${1}\t_v := $3\n\t$2 = &_v")
}

// fromMethodLiteralRe matches the literal assigned to the discriminator field
// inside a generated From{Schema} method. The function name's suffix is the
// schema name; we replace the literal with the OpenAPI discriminator mapping
// key when one is known. Untracked by oapi-codegen (separate from #2297).
var fromMethodLiteralRe = regexp.MustCompile(
	`(func \([^)]+\) From(\w+)\([^)]*\) error \{\n\t\w+\.\w+ = )"[^"]*"`,
)

// valueByDiscriminatorCaseRe matches the `case "Schema":` lines emitted in the
// ValueByDiscriminator switch. Same root cause: the schema name is used in
// place of the mapping key.
var valueByDiscriminatorCaseRe = regexp.MustCompile(
	`(\tcase )"(\w+)"(:\n\t\treturn t\.As\w+\(\))`,
)

func fixDiscriminatorValueLiteral(s string, mapping map[string]string) string {
	if len(mapping) == 0 {
		return s
	}
	s = fromMethodLiteralRe.ReplaceAllStringFunc(s, func(match string) string {
		sub := fromMethodLiteralRe.FindStringSubmatch(match)
		mapped, ok := mapping[sub[2]]
		if !ok {
			return match
		}
		return sub[1] + `"` + mapped + `"`
	})
	s = valueByDiscriminatorCaseRe.ReplaceAllStringFunc(s, func(match string) string {
		sub := valueByDiscriminatorCaseRe.FindStringSubmatch(match)
		mapped, ok := mapping[sub[2]]
		if !ok {
			return match
		}
		return sub[1] + `"` + mapped + `"` + sub[3]
	})
	return s
}

// enumConstRe matches a typed string-enum constant declaration like
// `\tDeploymentStatusACTIVE DeploymentStatus = "ACTIVE"`. Captures the
// constant name, type name, and string literal value. oapi-codegen sanitizes
// the value (strips underscores) when forming the constant name, which makes
// names like `DeploymentStatusBUILDFAILED` ambiguous to read; we rewrite to
// `DeploymentStatus_BUILD_FAILED` using the raw JSON value.
var enumConstRe = regexp.MustCompile(
	`(?m)^\t([A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"]*)"$`,
)

// underscoreEnumConstants rewrites string-enum constants emitted by
// oapi-codegen so they preserve the underlying JSON value verbatim, separated
// from the type name by an underscore. e.g.
// `DeploymentStatusBUILDFAILED` -> `DeploymentStatus_BUILD_FAILED`.
func underscoreEnumConstants(s string) string {
	renames := map[string]string{}
	for _, m := range enumConstRe.FindAllStringSubmatch(s, -1) {
		oldName, typeName, value := m[1], m[2], m[3]
		// Skip if the value isn't a usable Go identifier suffix (would
		// produce an invalid name); leave the original name in place.
		if !isValidIdentTail(value) {
			continue
		}
		newName := typeName + "_" + value
		if oldName == newName {
			continue
		}
		renames[oldName] = newName
	}
	for oldName, newName := range renames {
		s = regexp.MustCompile(`\b`+regexp.QuoteMeta(oldName)+`\b`).ReplaceAllString(s, newName)
	}
	return s
}

func isValidIdentTail(v string) bool {
	if v == "" {
		return false
	}
	for _, r := range v {
		if !(r == '_' || (r >= '0' && r <= '9') || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z')) {
			return false
		}
	}
	return true
}

// modelConfigHeader is the doc comment prepended to the generated modelconfig
// file, mirroring the doc comments produced by clientgen for the API packages.
const modelConfigHeader = `// Code generated by github.com/atombender/go-jsonschema. DO NOT EDIT.

// Package modelconfig contains generated types for Baseten model
// configuration (also known as Truss config).
//
// Types in this package are generated from the Truss config JSON Schema and
// are NOT covered by any stability or compatibility guarantees. They may
// change without notice between versions.
package modelconfig
`

var modelConfigHeaderRe = regexp.MustCompile(
	`(?s)^// Code generated by github.com/atombender/go-jsonschema.*?\npackage modelconfig\n`,
)

func postProcessModelConfig(src []byte) ([]byte, error) {
	src = modelConfigHeaderRe.ReplaceAll(src, []byte(modelConfigHeader))
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("formatting modelconfig source: %w", err)
	}
	return out, nil
}
