package main

import (
	"fmt"
	"go/format"
	"maps"
	"regexp"
	"slices"
	"strings"
)

// postProcess removes the oapi-codegen runtime dependency from generated code
// and fixes known codegen bugs. discriminatorValues maps a Go schema name to
// the OpenAPI discriminator mapping keys that select it on the wire
// (see fixDiscriminatorValueLiteral). discriminatorRequired maps a Go schema
// name to whether its discriminator field is required, hence non-pointer
// (see fixDiscriminatorPointerAssign).
func postProcess(src []byte, discriminatorValues map[string][]string, discriminatorRequired map[string]bool, nullDistinct map[string][]string) ([]byte, error) {
	s := string(src)

	s = fixPackageComment(s)
	s = removeMergeMethods(s)
	s = removeRuntimeImport(s)
	s = fixDiscriminatorValueLiteral(s, discriminatorValues)
	s = fixDiscriminatorPointerAssign(s, discriminatorRequired)
	s = underscoreEnumConstants(s)
	s, err := applyNullDistinct(s, nullDistinct)
	if err != nil {
		return nil, err
	}

	out, err := format.Source([]byte(s))
	if err != nil {
		return nil, fmt.Errorf("formatting post-processed source: %w", err)
	}
	return out, nil
}

// packageCommentRe matches the oapi-codegen package doc comment block and
// replaces it with a standalone generated-code marker that won't appear in
// godoc.
var packageCommentRe = regexp.MustCompile(
	`(?s)^// Package \w+ provides primitives.*?DO NOT EDIT\.\npackage (\w+)`,
)

func fixPackageComment(s string) string {
	return packageCommentRe.ReplaceAllString(s,
		"// Code generated by oapi-codegen. DO NOT EDIT.\n\npackage $1")
}

// mergeFuncRe matches entire Merge* methods including the preceding doc comment
// through the closing brace.
var mergeFuncRe = regexp.MustCompile(
	`(?ms)^// Merge\w+ performs a merge[^\n]*\n.+?\n\}\n`,
)

func removeMergeMethods(s string) string {
	return mergeFuncRe.ReplaceAllString(s, "")
}

func removeRuntimeImport(s string) string {
	s = strings.ReplaceAll(s, "\t\"github.com/oapi-codegen/runtime\"\n", "")
	s = strings.ReplaceAll(s, "\topenapi_types \"github.com/oapi-codegen/runtime/types\"\n", "")
	return s
}

// discriminatorRe matches discriminator assignments in From* methods
// (oapi-codegen#2297): v.Field = "literal" where Field is actually *string.
// We wrap with a temporary variable to take the address. Group 2 is the schema
// name (the From{Name} suffix), used to look up whether the field is a pointer.
var discriminatorRe = regexp.MustCompile(
	`(func \([^)]+\) From(\w+)\([^)]*\) error \{\n)\t(\w+\.\w+) = (".*")`,
)

// fixDiscriminatorPointerAssign takes the address of the discriminator literal
// only when the member's field is a pointer. A member that requires its
// discriminator property gets a non-pointer string field from oapi-codegen, so
// the plain literal assignment is already correct and left untouched.
func fixDiscriminatorPointerAssign(s string, discriminatorRequired map[string]bool) string {
	return discriminatorRe.ReplaceAllStringFunc(s, func(match string) string {
		sub := discriminatorRe.FindStringSubmatch(match)
		prefix, schemaName, field, literal := sub[1], sub[2], sub[3], sub[4]
		if discriminatorRequired[schemaName] {
			return match
		}
		return prefix + "\t_v := " + literal + "\n\t" + field + " = &_v"
	})
}

// fromMethodAssignRe matches the whole discriminator assignment line inside a
// generated From{Schema} method. The function name's suffix is the schema name;
// we replace the literal with the OpenAPI discriminator mapping key when one is
// known. Untracked by oapi-codegen (separate from #2297).
var fromMethodAssignRe = regexp.MustCompile(
	`(func \([^)]+\) From(\w+)\([^)]*\) error \{\n)\t(\w+\.\w+) = "[^"]*"\n`,
)

// valueByDiscriminatorCaseRe matches the `case "Schema":` lines emitted in the
// ValueByDiscriminator switch. Same root cause: the schema name is used in
// place of the mapping key.
var valueByDiscriminatorCaseRe = regexp.MustCompile(
	`(\tcase )"(\w+)"(:\n\t\treturn t\.As\w+\(\))`,
)

func fixDiscriminatorValueLiteral(s string, mapping map[string][]string) string {
	if len(mapping) == 0 {
		return s
	}
	// A member selected by several mapping keys has no single correct literal,
	// and its discriminator property is a multi-value enum the caller sets
	// itself. Drop the assignment so the caller's value survives, rather than
	// overwriting it with one arbitrary key.
	s = fromMethodAssignRe.ReplaceAllStringFunc(s, func(match string) string {
		sub := fromMethodAssignRe.FindStringSubmatch(match)
		mapped, ok := mapping[sub[2]]
		if !ok {
			return match
		}
		if len(mapped) > 1 {
			return sub[1]
		}
		return sub[1] + "\t" + sub[3] + ` = "` + mapped[0] + `"` + "\n"
	})
	s = valueByDiscriminatorCaseRe.ReplaceAllStringFunc(s, func(match string) string {
		sub := valueByDiscriminatorCaseRe.FindStringSubmatch(match)
		mapped, ok := mapping[sub[2]]
		if !ok {
			return match
		}
		labels := make([]string, len(mapped))
		for i, v := range mapped {
			labels[i] = `"` + v + `"`
		}
		return sub[1] + strings.Join(labels, ", ") + sub[3]
	})
	return s
}

// enumConstRe matches a typed string-enum constant declaration like
// `\tDeploymentStatusACTIVE DeploymentStatus = "ACTIVE"`. Captures the
// constant name, type name, and string literal value. oapi-codegen sanitizes
// the value (strips underscores) when forming the constant name, which makes
// names like `DeploymentStatusBUILDFAILED` ambiguous to read; we rewrite to
// `DeploymentStatus_BUILD_FAILED` using the raw JSON value.
var enumConstRe = regexp.MustCompile(
	`(?m)^\t([A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"]*)"$`,
)

// underscoreEnumConstants rewrites string-enum constants emitted by
// oapi-codegen so they preserve the underlying JSON value verbatim, separated
// from the type name by an underscore. e.g.
// `DeploymentStatusBUILDFAILED` -> `DeploymentStatus_BUILD_FAILED`.
func underscoreEnumConstants(s string) string {
	renames := map[string]string{}
	for _, m := range enumConstRe.FindAllStringSubmatch(s, -1) {
		oldName, typeName, value := m[1], m[2], m[3]
		// Skip if the value isn't a usable Go identifier suffix (would
		// produce an invalid name); leave the original name in place.
		if !isValidIdentTail(value) {
			continue
		}
		newName := typeName + "_" + value
		if oldName == newName {
			continue
		}
		renames[oldName] = newName
	}
	for oldName, newName := range renames {
		s = regexp.MustCompile(`\b`+regexp.QuoteMeta(oldName)+`\b`).ReplaceAllString(s, newName)
	}
	return s
}

func isValidIdentTail(v string) bool {
	if v == "" {
		return false
	}
	for _, r := range v {
		if !(r == '_' || (r >= '0' && r <= '9') || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z')) {
			return false
		}
	}
	return true
}

// modelConfigHeader is the doc comment prepended to the generated modelconfig
// file, mirroring the doc comments produced by clientgen for the API packages.
const modelConfigHeader = `// Code generated by github.com/atombender/go-jsonschema. DO NOT EDIT.

// Package modelconfig contains generated types for Baseten model
// configuration (also known as Truss config).
//
// Types in this package are generated from the Truss config JSON Schema and
// are NOT covered by any stability or compatibility guarantees. They may
// change without notice between versions.
package modelconfig
`

var modelConfigHeaderRe = regexp.MustCompile(
	`(?s)^// Code generated by github.com/atombender/go-jsonschema.*?\npackage modelconfig\n`,
)

func postProcessModelConfig(src []byte) ([]byte, error) {
	src = modelConfigHeaderRe.ReplaceAll(src, []byte(modelConfigHeader))
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("formatting modelconfig source: %w", err)
	}
	return out, nil
}

// applyNullDistinct retypes the fields the spec marks x-null-distinct from
// `*T` with omitempty to `Optional[T]` with omitzero, and appends the Optional
// definition when at least one field was rewritten. oapi-codegen renders every
// optional property as a pointer with omitempty, which collapses an explicit
// null into an omitted field; these are the fields where the API tells the two
// apart.
//
// A field named here that is missing, already non-pointer, or not tagged
// omitempty is a mismatch between the spec and the generated source, and fails
// the build rather than silently leaving null unreachable.
func applyNullDistinct(s string, nullDistinct map[string][]string) (string, error) {
	rewrote := false
	for _, schema := range slices.Sorted(maps.Keys(nullDistinct)) {
		for _, field := range nullDistinct[schema] {
			replaced, err := retypeFieldAsOptional(s, schema, field)
			if err != nil {
				return "", err
			}
			s = replaced
			rewrote = true
		}
	}
	if !rewrote {
		return s, nil
	}
	if !strings.Contains(s, `"encoding/json"`) {
		return "", fmt.Errorf("Optional needs encoding/json, which the generated source does not import")
	}
	return s + optionalTypeSource, nil
}

// structBodyRe captures a named struct's body so a field rewrite stays scoped
// to the type that declares it. Field names repeat across schemas: Timezone is
// null-distinct on UpdateAutoscalingScheduleSettings but a plain read-only
// field on EnvironmentAutoscalingSchedules.
func structBodyRe(schema string) *regexp.Regexp {
	return regexp.MustCompile(`(?ms)^type ` + regexp.QuoteMeta(schema) + ` struct \{\n(.*?)^\}`)
}

func retypeFieldAsOptional(s, schema, field string) (string, error) {
	body := structBodyRe(schema).FindStringSubmatchIndex(s)
	if body == nil {
		return "", fmt.Errorf("%s: no generated struct for a schema marked %s", schema, nullDistinctExtension)
	}
	start, end := body[2], body[3]
	fieldRe := regexp.MustCompile(`(?m)^\t` + regexp.QuoteMeta(field) + ` \*(\S+) ` + "`" + `json:"([^"]+)"` + "`" + `$`)
	match := fieldRe.FindStringSubmatchIndex(s[start:end])
	if match == nil {
		return "", fmt.Errorf("%s.%s: no pointer field to retype; %s must mark an optional property",
			schema, field, nullDistinctExtension)
	}
	goType := s[start+match[2] : start+match[3]]
	tag := s[start+match[4] : start+match[5]]
	name, ok := strings.CutSuffix(tag, ",omitempty")
	if !ok {
		return "", fmt.Errorf("%s.%s: json tag %q is not omitempty, so the property is required and cannot be null-distinct",
			schema, field, tag)
	}
	replacement := fmt.Sprintf("\t%s Optional[%s] `json:%q`", field, goType, name+",omitzero")
	return s[:start+match[0]] + replacement + s[start+match[1]:], nil
}

// optionalTypeSource is appended to a generated package that has at least one
// null-distinct field. It is emitted per package rather than shared, so the
// generated clients keep no runtime dependency of their own.
const optionalTypeSource = `

// Optional is a field whose explicit null differs from its omission. The zero
// value is unset, which the omitzero tag omits from the request body entirely.
// The API reads an omitted field as "leave unchanged" and a null as "clear".
type Optional[T any] struct {
	set   bool
	value *T
}

// NewOptional returns an Optional holding value. A nil value encodes as JSON
// null, clearing the field server-side.
func NewOptional[T any](value *T) Optional[T] {
	return Optional[T]{set: true, value: value}
}

// IsSet reports whether the field was set, to either a value or null.
func (o Optional[T]) IsSet() bool { return o.set }

// IsNull reports whether the field was set to null.
func (o Optional[T]) IsNull() bool { return o.set && o.value == nil }

// Get returns the value, or nil when the field is unset or null. Use IsSet to
// tell those apart.
func (o Optional[T]) Get() *T { return o.value }

// IsZero reports whether the field is unset, which is how the omitzero tag
// decides to omit it.
func (o Optional[T]) IsZero() bool { return !o.set }

func (o Optional[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.value)
}

func (o *Optional[T]) UnmarshalJSON(data []byte) error {
	// Unmarshaling into the *T leaves it nil for null and allocates otherwise.
	o.set = true
	o.value = nil
	return json.Unmarshal(data, &o.value)
}
`
