// Code generated by apigen/clientgen. DO NOT EDIT.

// Package inferenceapi is a generated client for the Baseten inferenceapi.
//
// Types and methods in this package are generated from the OpenAPI
// specification and are NOT covered by any stability or compatibility
// guarantees. They may change without notice between versions.
package inferenceapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Client is a generated HTTP client for the inferenceapi API.
//
// On HTTP failure, methods return [*ResponseError] unless documented
// otherwise on the method.
type Client struct {
	BaseURL    string
	HTTPClient interface {
		Do(*http.Request) (*http.Response, error)
	}
	// Headers are added to every request.
	Headers http.Header
}

// ResponseError represents a non-success HTTP response whose body could not
// be decoded into a typed error.
type ResponseError struct {
	StatusCode int
	Body       string
}

func (e *ResponseError) Error() string {
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, e.Body)
}

// ResponseErrorResponse is returned for non-success HTTP responses whose body
// decoded as [ErrorResponse].
type ResponseErrorResponse struct {
	StatusCode    int
	ErrorResponse ErrorResponse
}

func (e *ResponseErrorResponse) Error() string {
	b, _ := json.Marshal(e.ErrorResponse)
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, string(b))
}

// AsyncPredict: Asynchronously call a named environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 413, 429, 503.
func (c *Client) AsyncPredict(ctx context.Context, envName string, body AsyncPredictRequest) (*AsyncPredictOutput, error) {
	return doJSON[AsyncPredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/environments/%s/async_predict",
		pathArgs:    []any{envName},
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 413: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncPredictDeployment: Asynchronously call a specific deployment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 413, 429, 503.
func (c *Client) AsyncPredictDeployment(ctx context.Context, deploymentId string, body AsyncPredictRequest) (*AsyncPredictOutput, error) {
	return doJSON[AsyncPredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/deployment/%s/async_predict",
		pathArgs:    []any{deploymentId},
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 413: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncPredictDevelopment: Asynchronously call the development deployment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 413, 429, 503.
func (c *Client) AsyncPredictDevelopment(ctx context.Context, body AsyncPredictRequest) (*AsyncPredictOutput, error) {
	return doJSON[AsyncPredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/development/async_predict",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 413: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncPredictProduction: Asynchronously call the production environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 413, 429, 503.
func (c *Client) AsyncPredictProduction(ctx context.Context, body AsyncPredictRequest) (*AsyncPredictOutput, error) {
	return doJSON[AsyncPredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/production/async_predict",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 413: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncPredictRegional: Asynchronously call a regional environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 413, 429, 503.
func (c *Client) AsyncPredictRegional(ctx context.Context, body AsyncPredictRequest) (*AsyncPredictOutput, error) {
	return doJSON[AsyncPredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/async_predict",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 413: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncRunRemote: Asynchronously call a named environment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 503.
func (c *Client) AsyncRunRemote(ctx context.Context, envName string, body any) (*AsyncRunRemoteOutput, error) {
	return doJSON[AsyncRunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/environments/%s/async_run_remote",
		pathArgs:    []any{envName},
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncRunRemoteDeployment: Asynchronously call a specific deployment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 503.
func (c *Client) AsyncRunRemoteDeployment(ctx context.Context, deploymentId string, body any) (*AsyncRunRemoteOutput, error) {
	return doJSON[AsyncRunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/deployment/%s/async_run_remote",
		pathArgs:    []any{deploymentId},
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncRunRemoteDevelopment: Asynchronously call the development deployment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 503.
func (c *Client) AsyncRunRemoteDevelopment(ctx context.Context, body any) (*AsyncRunRemoteOutput, error) {
	return doJSON[AsyncRunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/development/async_run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncRunRemoteProduction: Asynchronously call the production environment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 503.
func (c *Client) AsyncRunRemoteProduction(ctx context.Context, body any) (*AsyncRunRemoteOutput, error) {
	return doJSON[AsyncRunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/production/async_run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// AsyncRunRemoteRegional: Asynchronously call a regional environment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 503.
func (c *Client) AsyncRunRemoteRegional(ctx context.Context, body any) (*AsyncRunRemoteOutput, error) {
	return doJSON[AsyncRunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/async_run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 201,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// CancelAsyncRequest: Cancel a queued async request.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) CancelAsyncRequest(ctx context.Context, requestId string) (*CancelAsyncRequestOutput, error) {
	return doJSON[CancelAsyncRequestOutput](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/async_request/%s",
		pathArgs:    []any{requestId},
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncQueueStatus: Get async queue status for a named environment.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncQueueStatus(ctx context.Context, envName string) (*GetAsyncQueueStatusOutput, error) {
	return doJSON[GetAsyncQueueStatusOutput](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/environments/%s/async_queue_status",
		pathArgs:    []any{envName},
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncQueueStatusDeployment: Get async queue status for a specific deployment.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncQueueStatusDeployment(ctx context.Context, deploymentId string) (*GetAsyncQueueStatusOutput, error) {
	return doJSON[GetAsyncQueueStatusOutput](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/deployment/%s/async_queue_status",
		pathArgs:    []any{deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncQueueStatusDevelopment: Get async queue status for the development deployment.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncQueueStatusDevelopment(ctx context.Context) (*GetAsyncQueueStatusOutput, error) {
	return doJSON[GetAsyncQueueStatusOutput](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/development/async_queue_status",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncQueueStatusProduction: Get async queue status for the production environment.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncQueueStatusProduction(ctx context.Context) (*GetAsyncQueueStatusOutput, error) {
	return doJSON[GetAsyncQueueStatusOutput](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/production/async_queue_status",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncQueueStatusRegional: Get async queue status for a regional environment.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncQueueStatusRegional(ctx context.Context) (*GetAsyncQueueStatusOutput, error) {
	return doJSON[GetAsyncQueueStatusOutput](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/async_queue_status",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// GetAsyncRequestStatus: Get the status of an async request.
//
// Returns [*ResponseErrorResponse] on HTTP 401, 429.
func (c *Client) GetAsyncRequestStatus(ctx context.Context, requestId string) (*AsyncRequestStatusResponse, error) {
	return doJSON[AsyncRequestStatusResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/async_request/%s",
		pathArgs:    []any{requestId},
		body:        nil,
		successCode: 200,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse, 429: errorTypeErrorResponse},
	})
}

// Predict: Call the model deployment associated with a specified environment.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) Predict(ctx context.Context, envName string, body any) (*PredictOutput, error) {
	return doJSON[PredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/environments/%s/predict",
		pathArgs:    []any{envName},
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// PredictDeployment: Call a specific deployment of a model by deployment ID.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) PredictDeployment(ctx context.Context, deploymentId string, body any) (*PredictOutput, error) {
	return doJSON[PredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/deployment/%s/predict",
		pathArgs:    []any{deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// PredictDevelopment: Call the development deployment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) PredictDevelopment(ctx context.Context, body any) (*PredictOutput, error) {
	return doJSON[PredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/development/predict",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// PredictProduction: Call the production environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) PredictProduction(ctx context.Context, body any) (*PredictOutput, error) {
	return doJSON[PredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/production/predict",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// PredictRegional: Call a regional environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) PredictRegional(ctx context.Context, body any) (*PredictOutput, error) {
	return doJSON[PredictOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/predict",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// RunRemote: Call the chain deployment associated with a specified environment.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) RunRemote(ctx context.Context, envName string, body any) (*RunRemoteOutput, error) {
	return doJSON[RunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/environments/%s/run_remote",
		pathArgs:    []any{envName},
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// RunRemoteDeployment: Call a specific chain deployment by deployment ID.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) RunRemoteDeployment(ctx context.Context, deploymentId string, body any) (*RunRemoteOutput, error) {
	return doJSON[RunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/deployment/%s/run_remote",
		pathArgs:    []any{deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// RunRemoteDevelopment: Call the development deployment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) RunRemoteDevelopment(ctx context.Context, body any) (*RunRemoteOutput, error) {
	return doJSON[RunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/development/run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// RunRemoteProduction: Call the production environment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) RunRemoteProduction(ctx context.Context, body any) (*RunRemoteOutput, error) {
	return doJSON[RunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/production/run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// RunRemoteRegional: Call a regional environment of a chain.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 401, 429, 502, 503, 504.
func (c *Client) RunRemoteRegional(ctx context.Context, body any) (*RunRemoteOutput, error) {
	return doJSON[RunRemoteOutput](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/run_remote",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  map[int]errorType{400: errorTypeErrorResponse, 401: errorTypeErrorResponse, 429: errorTypeErrorResponse, 502: errorTypeErrorResponse, 503: errorTypeErrorResponse, 504: errorTypeErrorResponse},
	})
}

// Wake: Wake a named environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 401.
func (c *Client) Wake(ctx context.Context, envName string) error {
	return c.doNoResponse(ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/environments/%s/wake",
		pathArgs:    []any{envName},
		body:        nil,
		successCode: 202,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse},
	})
}

// WakeDeployment: Wake a specific deployment of a model by deployment ID.
//
// Returns [*ResponseErrorResponse] on HTTP 401.
func (c *Client) WakeDeployment(ctx context.Context, deploymentId string) error {
	return c.doNoResponse(ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/deployment/%s/wake",
		pathArgs:    []any{deploymentId},
		body:        nil,
		successCode: 202,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse},
	})
}

// WakeDevelopment: Wake the development deployment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 401.
func (c *Client) WakeDevelopment(ctx context.Context) error {
	return c.doNoResponse(ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/development/wake",
		pathArgs:    nil,
		body:        nil,
		successCode: 202,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse},
	})
}

// WakeProduction: Wake the production environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 401.
func (c *Client) WakeProduction(ctx context.Context) error {
	return c.doNoResponse(ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/production/wake",
		pathArgs:    nil,
		body:        nil,
		successCode: 202,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse},
	})
}

// WakeRegional: Wake a regional environment of a model.
//
// Returns [*ResponseErrorResponse] on HTTP 401.
func (c *Client) WakeRegional(ctx context.Context) error {
	return c.doNoResponse(ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/wake",
		pathArgs:    nil,
		body:        nil,
		successCode: 202,
		errorCodes:  map[int]errorType{401: errorTypeErrorResponse},
	})
}

// errorType identifies a typed error schema for status-code-based dispatch.
type errorType int

const (
	errorTypeNone errorType = iota
	errorTypeErrorResponse
)

type apiRequest struct {
	method      string
	pathFmt     string
	pathArgs    []any
	body        any
	successCode int
	// errorCodes maps HTTP status codes to a typed error schema. Status codes
	// not in this map (or decode failures) fall back to [*ResponseError].
	errorCodes map[int]errorType
}

func (c *Client) do(ctx context.Context, r apiRequest) (*http.Response, error) {
	for i, p := range r.pathArgs {
		r.pathArgs[i] = url.PathEscape(fmt.Sprint(p))
	}
	path := fmt.Sprintf(r.pathFmt, r.pathArgs...)
	var bodyReader io.Reader
	if r.body != nil {
		b, err := json.Marshal(r.body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, r.method, c.BaseURL+path, bodyReader)
	if err != nil {
		return nil, err
	}
	if r.body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for key, vals := range c.Headers {
		for _, val := range vals {
			req.Header.Add(key, val)
		}
	}
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != r.successCode {
		defer resp.Body.Close()
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if et, ok := r.errorCodes[resp.StatusCode]; ok {
			if typedErr := decodeErrorType(et, resp.StatusCode, body); typedErr != nil {
				return nil, typedErr
			}
		}
		return nil, &ResponseError{StatusCode: resp.StatusCode, Body: string(body)}
	}
	return resp, nil
}

func decodeErrorType(et errorType, statusCode int, body []byte) error {
	switch et {
	case errorTypeErrorResponse:
		var detail ErrorResponse
		if err := json.Unmarshal(body, &detail); err == nil {
			return &ResponseErrorResponse{StatusCode: statusCode, ErrorResponse: detail}
		}
	}
	return nil
}

func doJSON[T any](c *Client, ctx context.Context, r apiRequest) (*T, error) {
	resp, err := c.do(ctx, r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		return nil, fmt.Errorf("unexpected content type %q, expected application/json", ct)
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var result T
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (c *Client) doNoResponse(ctx context.Context, r apiRequest) error {
	resp, err := c.do(ctx, r)
	if err != nil {
		return err
	}
	resp.Body.Close()
	return nil
}
