// Code generated by oapi-codegen. DO NOT EDIT.

package inferenceapi

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for AsyncRequestErrorCode.
const (
	ASYNCREQUESTNOTSUPPORTED AsyncRequestErrorCode = "ASYNC_REQUEST_NOT_SUPPORTED"
	INTERNALSERVERERROR      AsyncRequestErrorCode = "INTERNAL_SERVER_ERROR"
	MODELDOESNOTEXIST        AsyncRequestErrorCode = "MODEL_DOES_NOT_EXIST"
	MODELINVALIDINPUT        AsyncRequestErrorCode = "MODEL_INVALID_INPUT"
	MODELNOTREADY            AsyncRequestErrorCode = "MODEL_NOT_READY"
	MODELPREDICTERROR        AsyncRequestErrorCode = "MODEL_PREDICT_ERROR"
	MODELPREDICTTIMEOUT      AsyncRequestErrorCode = "MODEL_PREDICT_TIMEOUT"
	MODELUNAVAILABLE         AsyncRequestErrorCode = "MODEL_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the AsyncRequestErrorCode enum.
func (e AsyncRequestErrorCode) Valid() bool {
	switch e {
	case ASYNCREQUESTNOTSUPPORTED:
		return true
	case INTERNALSERVERERROR:
		return true
	case MODELDOESNOTEXIST:
		return true
	case MODELINVALIDINPUT:
		return true
	case MODELNOTREADY:
		return true
	case MODELPREDICTERROR:
		return true
	case MODELPREDICTTIMEOUT:
		return true
	case MODELUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for AsyncRequestStatusResponseStatus.
const (
	AsyncRequestStatusResponseStatusCANCELED      AsyncRequestStatusResponseStatus = "CANCELED"
	AsyncRequestStatusResponseStatusEXPIRED       AsyncRequestStatusResponseStatus = "EXPIRED"
	AsyncRequestStatusResponseStatusFAILED        AsyncRequestStatusResponseStatus = "FAILED"
	AsyncRequestStatusResponseStatusINPROGRESS    AsyncRequestStatusResponseStatus = "IN_PROGRESS"
	AsyncRequestStatusResponseStatusQUEUED        AsyncRequestStatusResponseStatus = "QUEUED"
	AsyncRequestStatusResponseStatusSUCCEEDED     AsyncRequestStatusResponseStatus = "SUCCEEDED"
	AsyncRequestStatusResponseStatusWEBHOOKFAILED AsyncRequestStatusResponseStatus = "WEBHOOK_FAILED"
)

// Valid indicates whether the value is a known member of the AsyncRequestStatusResponseStatus enum.
func (e AsyncRequestStatusResponseStatus) Valid() bool {
	switch e {
	case AsyncRequestStatusResponseStatusCANCELED:
		return true
	case AsyncRequestStatusResponseStatusEXPIRED:
		return true
	case AsyncRequestStatusResponseStatusFAILED:
		return true
	case AsyncRequestStatusResponseStatusINPROGRESS:
		return true
	case AsyncRequestStatusResponseStatusQUEUED:
		return true
	case AsyncRequestStatusResponseStatusSUCCEEDED:
		return true
	case AsyncRequestStatusResponseStatusWEBHOOKFAILED:
		return true
	default:
		return false
	}
}

// Defines values for AsyncRequestStatusResponseWebhookStatus.
const (
	AsyncRequestStatusResponseWebhookStatusCANCELED          AsyncRequestStatusResponseWebhookStatus = "CANCELED"
	AsyncRequestStatusResponseWebhookStatusFAILED            AsyncRequestStatusResponseWebhookStatus = "FAILED"
	AsyncRequestStatusResponseWebhookStatusNOWEBHOOKPROVIDED AsyncRequestStatusResponseWebhookStatus = "NO_WEBHOOK_PROVIDED"
	AsyncRequestStatusResponseWebhookStatusPENDING           AsyncRequestStatusResponseWebhookStatus = "PENDING"
	AsyncRequestStatusResponseWebhookStatusSUCCEEDED         AsyncRequestStatusResponseWebhookStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the AsyncRequestStatusResponseWebhookStatus enum.
func (e AsyncRequestStatusResponseWebhookStatus) Valid() bool {
	switch e {
	case AsyncRequestStatusResponseWebhookStatusCANCELED:
		return true
	case AsyncRequestStatusResponseWebhookStatusFAILED:
		return true
	case AsyncRequestStatusResponseWebhookStatusNOWEBHOOKPROVIDED:
		return true
	case AsyncRequestStatusResponseWebhookStatusPENDING:
		return true
	case AsyncRequestStatusResponseWebhookStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ApplicationError     ErrorResponseErrorCode = "application_error"
	ClientError          ErrorResponseErrorCode = "client_error"
	InternalBasetenError ErrorResponseErrorCode = "internal_baseten_error"
	ModelDoesNotExist    ErrorResponseErrorCode = "model_does_not_exist"
	ModelNotReady        ErrorResponseErrorCode = "model_not_ready"
	ModelUnavailable     ErrorResponseErrorCode = "model_unavailable"
	PayloadTooLarge      ErrorResponseErrorCode = "payload_too_large"
	RateLimited          ErrorResponseErrorCode = "rate_limited"
	Timeout              ErrorResponseErrorCode = "timeout"
	Unauthorized         ErrorResponseErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ApplicationError:
		return true
	case ClientError:
		return true
	case InternalBasetenError:
		return true
	case ModelDoesNotExist:
		return true
	case ModelNotReady:
		return true
	case ModelUnavailable:
		return true
	case PayloadTooLarge:
		return true
	case RateLimited:
		return true
	case Timeout:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// AsyncPredictRequest defines model for AsyncPredictRequest.
type AsyncPredictRequest struct {
	// InferenceRetryConfig Exponential backoff parameters for retrying predict requests.
	InferenceRetryConfig *InferenceRetryConfig `json:"inference_retry_config,omitempty"`

	// MaxTimeInQueueSeconds Maximum time in seconds a request will spend in the queue before expiring. Must be between 10 seconds and 72 hours.
	MaxTimeInQueueSeconds *int `json:"max_time_in_queue_seconds,omitempty"`

	// ModelInput JSON-serializable model input.
	ModelInput map[string]interface{} `json:"model_input"`

	// Priority Priority of the request. Lower values are higher priority.
	Priority *int `json:"priority,omitempty"`

	// WebhookEndpoint HTTPS URL to receive the prediction result via webhook. Both HTTP/2 and HTTP/1.1 are supported. If omitted, the model must save outputs so they can be accessed later.
	WebhookEndpoint *string `json:"webhook_endpoint,omitempty"`
}

// AsyncRequestError defines model for AsyncRequestError.
type AsyncRequestError struct {
	// Code The type of error that occurred.
	Code AsyncRequestErrorCode `json:"code"`

	// Message Details of the error.
	Message string `json:"message"`
}

// AsyncRequestErrorCode The type of error that occurred.
type AsyncRequestErrorCode string

// AsyncRequestStatusResponse defines model for AsyncRequestStatusResponse.
type AsyncRequestStatusResponse struct {
	// ChainId The ID of the chain that executed the request. Present for chain requests.
	ChainId *string `json:"chain_id,omitempty"`

	// CreatedAt The time in UTC at which the async request was created.
	CreatedAt string `json:"created_at"`

	// DeploymentId The ID of the deployment that executed the request.
	DeploymentId string `json:"deployment_id"`

	// Errors Errors that occurred while processing the async request. Empty if no errors occurred.
	Errors []AsyncRequestError `json:"errors"`

	// ModelId The ID of the model that executed the request. Present for model requests.
	ModelId *string `json:"model_id,omitempty"`

	// RequestId The ID of the async request.
	RequestId string `json:"request_id"`

	// Status The status of the async request.
	Status AsyncRequestStatusResponseStatus `json:"status"`

	// StatusAt The time in UTC at which the async request's status was last updated.
	StatusAt string `json:"status_at"`

	// WebhookStatus The status of sending the prediction result to the provided webhook.
	WebhookStatus AsyncRequestStatusResponseWebhookStatus `json:"webhook_status"`
}

// AsyncRequestStatusResponseStatus The status of the async request.
type AsyncRequestStatusResponseStatus string

// AsyncRequestStatusResponseWebhookStatus The status of sending the prediction result to the provided webhook.
type AsyncRequestStatusResponseWebhookStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail Additional error details, if available.
	Detail *string `json:"detail,omitempty"`

	// Error Human-readable error message.
	Error *string `json:"error,omitempty"`

	// ErrorCode Machine-readable error code.
	ErrorCode *ErrorResponseErrorCode `json:"error_code,omitempty"`
}

// ErrorResponseErrorCode Machine-readable error code.
type ErrorResponseErrorCode string

// InferenceRetryConfig Exponential backoff parameters for retrying predict requests.
type InferenceRetryConfig struct {
	// InitialDelayMs Minimum time between retries in milliseconds.
	InitialDelayMs *int `json:"initial_delay_ms,omitempty"`

	// MaxAttempts Number of predict request attempts.
	MaxAttempts *int `json:"max_attempts,omitempty"`

	// MaxDelayMs Maximum time between retries in milliseconds.
	MaxDelayMs *int `json:"max_delay_ms,omitempty"`
}

// DeploymentId defines model for deployment_id.
type DeploymentId = string

// EnvName defines model for env_name.
type EnvName = string

// RequestId defines model for request_id.
type RequestId = string

// AsyncPredictOutput defines model for AsyncPredictOutput.
type AsyncPredictOutput struct {
	// RequestId The ID of the async request.
	RequestId string `json:"request_id"`
}

// AsyncRunRemoteOutput defines model for AsyncRunRemoteOutput.
type AsyncRunRemoteOutput struct {
	// RequestId The ID of the async request.
	RequestId string `json:"request_id"`
}

// CancelAsyncRequestOutput defines model for CancelAsyncRequestOutput.
type CancelAsyncRequestOutput struct {
	// Canceled Whether the request was canceled.
	Canceled bool `json:"canceled"`

	// Message Additional details about whether the request was canceled.
	Message string `json:"message"`

	// RequestId The ID of the async request.
	RequestId string `json:"request_id"`
}

// Error defines model for Error.
type Error = ErrorResponse

// GetAsyncQueueStatusOutput defines model for GetAsyncQueueStatusOutput.
type GetAsyncQueueStatusOutput struct {
	// DeploymentId The ID of the deployment.
	DeploymentId string `json:"deployment_id"`

	// ModelId The ID of the model.
	ModelId string `json:"model_id"`

	// NumInProgressRequests Number of requests currently being processed by the model.
	NumInProgressRequests int `json:"num_in_progress_requests"`

	// NumQueuedRequests Number of requests with QUEUED status awaiting processing.
	NumQueuedRequests int `json:"num_queued_requests"`
}

// GetAsyncRequestStatusOutput defines model for GetAsyncRequestStatusOutput.
type GetAsyncRequestStatusOutput = AsyncRequestStatusResponse

// PredictOutput JSON-serializable output. The shape is defined by the model.
type PredictOutput = map[string]interface{}

// RunRemoteOutput JSON-serializable output. The shape is defined by the chain.
type RunRemoteOutput = map[string]interface{}

// AsyncPredictInput defines model for AsyncPredictInput.
type AsyncPredictInput = AsyncPredictRequest

// AsyncRunRemoteInput JSON input matching the chain's `run_remote` method signature.
type AsyncRunRemoteInput = map[string]interface{}

// PredictInput JSON-serializable model input. The shape is defined by the model's `predict` function.
type PredictInput = map[string]interface{}

// RunRemoteInput JSON input matching the chain's `run_remote` method signature.
type RunRemoteInput = map[string]interface{}

// AsyncRunRemoteRegionalJSONBody defines parameters for AsyncRunRemoteRegional.
type AsyncRunRemoteRegionalJSONBody = map[string]interface{}

// AsyncRunRemoteDeploymentJSONBody defines parameters for AsyncRunRemoteDeployment.
type AsyncRunRemoteDeploymentJSONBody = map[string]interface{}

// PredictDeploymentJSONBody defines parameters for PredictDeployment.
type PredictDeploymentJSONBody = map[string]interface{}

// PredictDeploymentMultipartBody defines parameters for PredictDeployment.
type PredictDeploymentMultipartBody = map[string]interface{}

// RunRemoteDeploymentJSONBody defines parameters for RunRemoteDeployment.
type RunRemoteDeploymentJSONBody = map[string]interface{}

// AsyncRunRemoteDevelopmentJSONBody defines parameters for AsyncRunRemoteDevelopment.
type AsyncRunRemoteDevelopmentJSONBody = map[string]interface{}

// PredictDevelopmentJSONBody defines parameters for PredictDevelopment.
type PredictDevelopmentJSONBody = map[string]interface{}

// PredictDevelopmentMultipartBody defines parameters for PredictDevelopment.
type PredictDevelopmentMultipartBody = map[string]interface{}

// RunRemoteDevelopmentJSONBody defines parameters for RunRemoteDevelopment.
type RunRemoteDevelopmentJSONBody = map[string]interface{}

// AsyncRunRemoteJSONBody defines parameters for AsyncRunRemote.
type AsyncRunRemoteJSONBody = map[string]interface{}

// PredictJSONBody defines parameters for Predict.
type PredictJSONBody = map[string]interface{}

// PredictMultipartBody defines parameters for Predict.
type PredictMultipartBody = map[string]interface{}

// RunRemoteJSONBody defines parameters for RunRemote.
type RunRemoteJSONBody = map[string]interface{}

// PredictRegionalJSONBody defines parameters for PredictRegional.
type PredictRegionalJSONBody = map[string]interface{}

// PredictRegionalMultipartBody defines parameters for PredictRegional.
type PredictRegionalMultipartBody = map[string]interface{}

// AsyncRunRemoteProductionJSONBody defines parameters for AsyncRunRemoteProduction.
type AsyncRunRemoteProductionJSONBody = map[string]interface{}

// PredictProductionJSONBody defines parameters for PredictProduction.
type PredictProductionJSONBody = map[string]interface{}

// PredictProductionMultipartBody defines parameters for PredictProduction.
type PredictProductionMultipartBody = map[string]interface{}

// RunRemoteProductionJSONBody defines parameters for RunRemoteProduction.
type RunRemoteProductionJSONBody = map[string]interface{}

// RunRemoteRegionalJSONBody defines parameters for RunRemoteRegional.
type RunRemoteRegionalJSONBody = map[string]interface{}

// AsyncPredictRegionalJSONRequestBody defines body for AsyncPredictRegional for application/json ContentType.
type AsyncPredictRegionalJSONRequestBody = AsyncPredictRequest

// AsyncRunRemoteRegionalJSONRequestBody defines body for AsyncRunRemoteRegional for application/json ContentType.
type AsyncRunRemoteRegionalJSONRequestBody = AsyncRunRemoteRegionalJSONBody

// AsyncPredictDeploymentJSONRequestBody defines body for AsyncPredictDeployment for application/json ContentType.
type AsyncPredictDeploymentJSONRequestBody = AsyncPredictRequest

// AsyncRunRemoteDeploymentJSONRequestBody defines body for AsyncRunRemoteDeployment for application/json ContentType.
type AsyncRunRemoteDeploymentJSONRequestBody = AsyncRunRemoteDeploymentJSONBody

// PredictDeploymentJSONRequestBody defines body for PredictDeployment for application/json ContentType.
type PredictDeploymentJSONRequestBody = PredictDeploymentJSONBody

// PredictDeploymentMultipartRequestBody defines body for PredictDeployment for multipart/form-data ContentType.
type PredictDeploymentMultipartRequestBody = PredictDeploymentMultipartBody

// RunRemoteDeploymentJSONRequestBody defines body for RunRemoteDeployment for application/json ContentType.
type RunRemoteDeploymentJSONRequestBody = RunRemoteDeploymentJSONBody

// AsyncPredictDevelopmentJSONRequestBody defines body for AsyncPredictDevelopment for application/json ContentType.
type AsyncPredictDevelopmentJSONRequestBody = AsyncPredictRequest

// AsyncRunRemoteDevelopmentJSONRequestBody defines body for AsyncRunRemoteDevelopment for application/json ContentType.
type AsyncRunRemoteDevelopmentJSONRequestBody = AsyncRunRemoteDevelopmentJSONBody

// PredictDevelopmentJSONRequestBody defines body for PredictDevelopment for application/json ContentType.
type PredictDevelopmentJSONRequestBody = PredictDevelopmentJSONBody

// PredictDevelopmentMultipartRequestBody defines body for PredictDevelopment for multipart/form-data ContentType.
type PredictDevelopmentMultipartRequestBody = PredictDevelopmentMultipartBody

// RunRemoteDevelopmentJSONRequestBody defines body for RunRemoteDevelopment for application/json ContentType.
type RunRemoteDevelopmentJSONRequestBody = RunRemoteDevelopmentJSONBody

// AsyncPredictJSONRequestBody defines body for AsyncPredict for application/json ContentType.
type AsyncPredictJSONRequestBody = AsyncPredictRequest

// AsyncRunRemoteJSONRequestBody defines body for AsyncRunRemote for application/json ContentType.
type AsyncRunRemoteJSONRequestBody = AsyncRunRemoteJSONBody

// PredictJSONRequestBody defines body for Predict for application/json ContentType.
type PredictJSONRequestBody = PredictJSONBody

// PredictMultipartRequestBody defines body for Predict for multipart/form-data ContentType.
type PredictMultipartRequestBody = PredictMultipartBody

// RunRemoteJSONRequestBody defines body for RunRemote for application/json ContentType.
type RunRemoteJSONRequestBody = RunRemoteJSONBody

// PredictRegionalJSONRequestBody defines body for PredictRegional for application/json ContentType.
type PredictRegionalJSONRequestBody = PredictRegionalJSONBody

// PredictRegionalMultipartRequestBody defines body for PredictRegional for multipart/form-data ContentType.
type PredictRegionalMultipartRequestBody = PredictRegionalMultipartBody

// AsyncPredictProductionJSONRequestBody defines body for AsyncPredictProduction for application/json ContentType.
type AsyncPredictProductionJSONRequestBody = AsyncPredictRequest

// AsyncRunRemoteProductionJSONRequestBody defines body for AsyncRunRemoteProduction for application/json ContentType.
type AsyncRunRemoteProductionJSONRequestBody = AsyncRunRemoteProductionJSONBody

// PredictProductionJSONRequestBody defines body for PredictProduction for application/json ContentType.
type PredictProductionJSONRequestBody = PredictProductionJSONBody

// PredictProductionMultipartRequestBody defines body for PredictProduction for multipart/form-data ContentType.
type PredictProductionMultipartRequestBody = PredictProductionMultipartBody

// RunRemoteProductionJSONRequestBody defines body for RunRemoteProduction for application/json ContentType.
type RunRemoteProductionJSONRequestBody = RunRemoteProductionJSONBody

// RunRemoteRegionalJSONRequestBody defines body for RunRemoteRegional for application/json ContentType.
type RunRemoteRegionalJSONRequestBody = RunRemoteRegionalJSONBody
