// Code generated by apigen/clientgen. DO NOT EDIT.

// Package sandboxapi is a generated client for the Baseten sandboxapi.
//
// Types and methods in this package are generated from the OpenAPI
// specification and are NOT covered by any stability or compatibility
// guarantees. They may change without notice between versions.
package sandboxapi

import (
	"bytes"
	"cmp"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"time"
)

// Client is a generated HTTP client for the sandboxapi API.
//
// On HTTP failure, methods return [*ResponseError] unless documented
// otherwise on the method.
type Client struct {
	BaseURL    string
	HTTPClient interface {
		Do(*http.Request) (*http.Response, error)
	}
	// Headers are added to every request.
	Headers http.Header
}

// ResponseError represents a non-success HTTP response whose body could not
// be decoded into a typed error.
type ResponseError struct {
	StatusCode int
	Body       string
}

func (e *ResponseError) Error() string {
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, e.Body)
}

// AdvancedRequest is the request body for an operation whose body is not JSON.
type AdvancedRequest struct {
	// Body is sent as is.
	Body io.Reader
	// ContentType overrides the content type the operation declares. Required
	// for multipart/form-data, since it carries the boundary.
	ContentType string
}

// ResponseErrorResponse is returned for non-success HTTP responses whose body
// decoded as [ErrorResponse].
type ResponseErrorResponse struct {
	StatusCode    int
	ErrorResponse ErrorResponse
}

func (e *ResponseErrorResponse) Error() string {
	b, _ := json.Marshal(e.ErrorResponse)
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, string(b))
}

// DeleteDrivesMount: Detach a drive from a local path
//
// Returns [*ResponseErrorResponse] on HTTP 400, 500.
func (c *Client) DeleteDrivesMount(ctx context.Context, mountPath string) (*DriveUnmountResponse, error) {
	return doJSON[DriveUnmountResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/drives/mount/%s",
		pathArgs:     []any{mountPath},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteFilesystem: Delete file or directory
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) DeleteFilesystem(ctx context.Context, path string, params DeleteFilesystemPathParams) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/filesystem/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteFilesystemMultipartAbort: Abort multipart upload
//
// Returns [*ResponseErrorResponse] on HTTP 400, 404, 500.
func (c *Client) DeleteFilesystemMultipartAbort(ctx context.Context, uploadId string) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/filesystem-multipart/%s/abort",
		pathArgs:     []any{uploadId},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 404: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteFilesystemTree: Delete directory tree
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) DeleteFilesystemTree(ctx context.Context, path string, params DeleteFilesystemTreePathParams) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/filesystem/tree/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteNetworkProcessMonitor: Stop monitoring ports for a process
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) DeleteNetworkProcessMonitor(ctx context.Context, pid string) (*DeleteNetworkProcessMonitorResponse, error) {
	return doJSON[DeleteNetworkProcessMonitorResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/network/process/%s/monitor",
		pathArgs:     []any{pid},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteNetworkTunnel: Disconnect tunnel
//
// Returns [*ResponseErrorResponse] on HTTP 400, 500.
func (c *Client) DeleteNetworkTunnel(ctx context.Context) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/network/tunnel",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteProcess: Stop a process
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) DeleteProcess(ctx context.Context, identifier string) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/process/%s",
		pathArgs:     []any{identifier},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteProcessKill: Kill a process
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) DeleteProcessKill(ctx context.Context, identifier string) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/process/%s/kill",
		pathArgs:     []any{identifier},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// DeleteProcessStdin: Close a process's stdin
//
// Returns [*ResponseErrorResponse] on HTTP 404, 409.
func (c *Client) DeleteProcessStdin(ctx context.Context, identifier string) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "DELETE",
		pathFmt:      "/process/%s/stdin",
		pathArgs:     []any{identifier},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 409: errorTypeErrorResponse},
	})
}

// GetArchiveStatus: Get the archive status
func (c *Client) GetArchiveStatus(ctx context.Context) (*QuiesceStatus, error) {
	return doJSON[QuiesceStatus](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/archive/status",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   nil,
	})
}

// GetCodegenReranking: Code reranking/semantic search
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 503.
func (c *Client) GetCodegenReranking(ctx context.Context, path string, params GetCodegenRerankingPathParams) (*RerankingResponse, error) {
	return doJSON[RerankingResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/codegen/reranking/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// GetDrivesMount: List currently mounted drives
//
// Returns [*ResponseErrorResponse] on HTTP 500.
func (c *Client) GetDrivesMount(ctx context.Context) (*DriveListResponse, error) {
	return doJSON[DriveListResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/drives/mount",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{500: errorTypeErrorResponse},
	})
}

// GetFilesystem: Get file or directory information
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) GetFilesystem(ctx context.Context, path string, params GetFilesystemPathParams) (*GetFilesystemResponse, error) {
	return doJSON[GetFilesystemResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemRaw: Get file or directory information
//
// Requests application/octet-stream and returns the response unread. The caller must close
// the response body.
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) GetFilesystemRaw(ctx context.Context, path string, params GetFilesystemPathParams) (*http.Response, error) {
	return c.do(ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		accept:       "application/octet-stream",
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemContentSearch: Search for text content in files
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) GetFilesystemContentSearch(ctx context.Context, path string, params GetFilesystemContentSearchPathParams) (*ContentSearchResponse, error) {
	return doJSON[ContentSearchResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem-content-search/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemFind: Find files and directories
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) GetFilesystemFind(ctx context.Context, path string, params GetFilesystemFindPathParams) (*FindResponse, error) {
	return doJSON[FindResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem-find/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemMultipart: List multipart uploads
//
// Returns [*ResponseErrorResponse] on HTTP 500.
func (c *Client) GetFilesystemMultipart(ctx context.Context) (*MultipartListUploadsResponse, error) {
	return doJSON[MultipartListUploadsResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem-multipart",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{500: errorTypeErrorResponse},
	})
}

// GetFilesystemMultipartParts: List parts
//
// Returns [*ResponseErrorResponse] on HTTP 400, 404, 500.
func (c *Client) GetFilesystemMultipartParts(ctx context.Context, uploadId string) (*MultipartListPartsResponse, error) {
	return doJSON[MultipartListPartsResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem-multipart/%s/parts",
		pathArgs:     []any{uploadId},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 404: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemSearch: Fuzzy search for files and directories
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) GetFilesystemSearch(ctx context.Context, path string, params GetFilesystemSearchPathParams) (*FuzzySearchResponse, error) {
	return doJSON[FuzzySearchResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem-search/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetFilesystemTree: Get directory tree
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) GetFilesystemTree(ctx context.Context, path string) (*GetFilesystemTreeResponse, error) {
	return doJSON[GetFilesystemTreeResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/filesystem/tree/%s",
		pathArgs:     []any{path},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetHealth: Health check
func (c *Client) GetHealth(ctx context.Context) (*HealthResponse, error) {
	return doJSON[HealthResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/health",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   nil,
	})
}

// GetNetworkProcessPorts: Get open ports for a process
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) GetNetworkProcessPorts(ctx context.Context, pid string) (*GetNetworkProcessPortsResponse, error) {
	return doJSON[GetNetworkProcessPortsResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/network/process/%s/ports",
		pathArgs:     []any{pid},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetProcess: List all processes
func (c *Client) GetProcess(ctx context.Context) (*GetProcessResponse, error) {
	return doJSON[GetProcessResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/process",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   nil,
	})
}

// GetProcessIdentifier: Get process by identifier
//
// Returns [*ResponseErrorResponse] on HTTP 404.
func (c *Client) GetProcessIdentifier(ctx context.Context, identifier string) (*ProcessResponse, error) {
	return doJSON[ProcessResponse](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/process/%s",
		pathArgs:     []any{identifier},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse},
	})
}

// GetProcessLogs: Get process logs
//
// Returns [*ResponseErrorResponse] on HTTP 404, 422, 500.
func (c *Client) GetProcessLogs(ctx context.Context, identifier string) (*ProcessLogs, error) {
	return doJSON[ProcessLogs](c, ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/process/%s/logs",
		pathArgs:     []any{identifier},
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// GetProcessLogsStreamRaw: Stream process logs in real time
//
// Requests text/plain and returns the response unread. The caller must close
// the response body.
func (c *Client) GetProcessLogsStreamRaw(ctx context.Context, identifier string) (*http.Response, error) {
	return c.do(ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/process/%s/logs/stream",
		pathArgs:     []any{identifier},
		accept:       "text/plain",
		successCodes: []int{200},
		errorCodes:   nil,
	})
}

// GetWatchFilesystemRaw: Stream file modification events in a directory
//
// Requests text/plain and returns the response unread. The caller must close
// the response body.
func (c *Client) GetWatchFilesystemRaw(ctx context.Context, path string, params GetWatchFilesystemPathParams) (*http.Response, error) {
	return c.do(ctx, apiRequest{
		method:       "GET",
		pathFmt:      "/watch/filesystem/%s",
		pathArgs:     []any{path},
		queryParams:  params,
		accept:       "text/plain",
		successCodes: []int{200},
		errorCodes:   nil,
	})
}

// PostArchiveExportResponse is the result of [Client.PostArchiveExport]. Only the JSON field for
// StatusCode is set.
type PostArchiveExportResponse struct {
	StatusCode int
	JSON200    *ExportResult
	JSON202    *ExportProgress
}

// PostArchiveExport: Export the filesystem changes to a presigned URL
//
// Returns [*ResponseErrorResponse] on HTTP 400, 409, 500.
func (c *Client) PostArchiveExport(ctx context.Context, body ExportOptions) (*PostArchiveExportResponse, error) {
	status, respBody, err := c.doJSONWithStatus(ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/archive/export",
		pathArgs:     nil,
		body:         body,
		successCodes: []int{200, 202},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 409: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
	if err != nil {
		return nil, err
	}
	result := &PostArchiveExportResponse{StatusCode: status}
	switch status {
	case 200:
		result.JSON200 = new(ExportResult)
		err = json.Unmarshal(respBody, result.JSON200)
	case 202:
		result.JSON202 = new(ExportProgress)
		err = json.Unmarshal(respBody, result.JSON202)
	}
	if err != nil {
		return nil, err
	}
	return result, nil
}

// PostArchiveResume: Lift the archive freeze
//
// Returns [*ResponseErrorResponse] on HTTP 409, 500.
func (c *Client) PostArchiveResume(ctx context.Context) (*QuiesceStatus, error) {
	return doJSON[QuiesceStatus](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/archive/resume",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{409: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostDrivesMount: Attach a drive to a local path
//
// Returns [*ResponseErrorResponse] on HTTP 400, 403, 409, 500.
func (c *Client) PostDrivesMount(ctx context.Context, body DriveMountRequest) (*DriveMountResponse, error) {
	return doJSON[DriveMountResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/drives/mount",
		pathArgs:     nil,
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 403: errorTypeErrorResponse, 409: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostEnvironmentReload: Reload environment from guest metadata
//
// Returns [*ResponseErrorResponse] on HTTP 404, 500.
func (c *Client) PostEnvironmentReload(ctx context.Context) (*HandlerReloadResponse, error) {
	return doJSON[HandlerReloadResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/environment/reload",
		pathArgs:     nil,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{404: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostFilesystemMultipartComplete: Complete multipart upload
//
// Returns [*ResponseErrorResponse] on HTTP 400, 404, 500.
func (c *Client) PostFilesystemMultipartComplete(ctx context.Context, uploadId string, body MultipartCompleteRequest) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/filesystem-multipart/%s/complete",
		pathArgs:     []any{uploadId},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 404: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostFilesystemMultipartInitiate: Initiate multipart upload
//
// Returns [*ResponseErrorResponse] on HTTP 400, 500.
func (c *Client) PostFilesystemMultipartInitiate(ctx context.Context, path string, body MultipartInitiateRequest) (*MultipartInitiateResponse, error) {
	return doJSON[MultipartInitiateResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/filesystem-multipart/initiate/%s",
		pathArgs:     []any{path},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostNetworkProcessMonitor: Start monitoring ports for a process
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PostNetworkProcessMonitor(ctx context.Context, pid string, body PortMonitorRequest) (*PostNetworkProcessMonitorResponse, error) {
	return doJSON[PostNetworkProcessMonitorResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/network/process/%s/monitor",
		pathArgs:     []any{pid},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostProcess: Execute a command
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PostProcess(ctx context.Context, body ProcessRequest) (*ProcessResponse, error) {
	return doJSON[ProcessResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/process",
		pathArgs:     nil,
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostProcessRaw: Execute a command
//
// Requests text/event-stream and returns the response unread. The caller must close
// the response body.
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PostProcessRaw(ctx context.Context, body ProcessRequest) (*http.Response, error) {
	return c.do(ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/process",
		pathArgs:     nil,
		body:         body,
		accept:       "text/event-stream",
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PostProcessStdin: Write to a process's stdin
//
// Returns [*ResponseErrorResponse] on HTTP 404, 409, 413, 500, 503.
func (c *Client) PostProcessStdin(ctx context.Context, identifier string, req AdvancedRequest) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:          "POST",
		pathFmt:         "/process/%s/stdin",
		pathArgs:        []any{identifier},
		rawBody:         req.Body,
		bodyContentType: cmp.Or(req.ContentType, "application/octet-stream"),
		successCodes:    []int{200},
		errorCodes:      map[int]errorType{404: errorTypeErrorResponse, 409: errorTypeErrorResponse, 413: errorTypeErrorResponse, 500: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// PostUpgrade: Upgrade the sandbox-api
//
// Returns [*ResponseErrorResponse] on HTTP 500.
func (c *Client) PostUpgrade(ctx context.Context, body UpgradeRequest) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "POST",
		pathFmt:      "/upgrade",
		pathArgs:     nil,
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{500: errorTypeErrorResponse},
	})
}

// PutCodegenFastapply: Apply code edit
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 503.
func (c *Client) PutCodegenFastapply(ctx context.Context, path string, body ApplyEditRequest) (*ApplyEditResponse, error) {
	return doJSON[ApplyEditResponse](c, ctx, apiRequest{
		method:       "PUT",
		pathFmt:      "/codegen/fastapply/%s",
		pathArgs:     []any{path},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 503: errorTypeErrorResponse},
	})
}

// PutFilesystem: Create or update a file or directory
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PutFilesystem(ctx context.Context, path string, body FileRequest) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "PUT",
		pathFmt:      "/filesystem/%s",
		pathArgs:     []any{path},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PutFilesystemMultipartPart: Upload part
//
// Returns [*ResponseErrorResponse] on HTTP 400, 404, 500.
func (c *Client) PutFilesystemMultipartPart(ctx context.Context, uploadId string, params PutFilesystemMultipartUploadIdPartParams, req AdvancedRequest) (*MultipartUploadPartResponse, error) {
	return doJSON[MultipartUploadPartResponse](c, ctx, apiRequest{
		method:          "PUT",
		pathFmt:         "/filesystem-multipart/%s/part",
		pathArgs:        []any{uploadId},
		queryParams:     params,
		rawBody:         req.Body,
		bodyContentType: cmp.Or(req.ContentType, "multipart/form-data"),
		successCodes:    []int{200},
		errorCodes:      map[int]errorType{400: errorTypeErrorResponse, 404: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PutFilesystemTree: Create or update directory tree
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PutFilesystemTree(ctx context.Context, path string, body TreeRequest) (*PutFilesystemTreeResponse, error) {
	return doJSON[PutFilesystemTreeResponse](c, ctx, apiRequest{
		method:       "PUT",
		pathFmt:      "/filesystem/tree/%s",
		pathArgs:     []any{path},
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// PutNetworkTunnelConfig: Update tunnel configuration
//
// Returns [*ResponseErrorResponse] on HTTP 400, 422, 500.
func (c *Client) PutNetworkTunnelConfig(ctx context.Context, body TunnelConfigRequest) (*SuccessResponse, error) {
	return doJSON[SuccessResponse](c, ctx, apiRequest{
		method:       "PUT",
		pathFmt:      "/network/tunnel/config",
		pathArgs:     nil,
		body:         body,
		successCodes: []int{200},
		errorCodes:   map[int]errorType{400: errorTypeErrorResponse, 422: errorTypeErrorResponse, 500: errorTypeErrorResponse},
	})
}

// errorType identifies a typed error schema for status-code-based dispatch.
type errorType int

const (
	errorTypeNone errorType = iota
	errorTypeErrorResponse
)

type apiRequest struct {
	method      string
	pathFmt     string
	pathArgs    []any
	queryParams any
	// body is marshaled as JSON. rawBody is sent as is, with bodyContentType.
	// At most one of them is set.
	body            any
	rawBody         io.Reader
	bodyContentType string
	// accept is the Accept header to send. Empty when the response is JSON.
	accept       string
	successCodes []int
	// errorCodes maps HTTP status codes to a typed error schema. Status codes
	// not in this map (or decode failures) fall back to [*ResponseError].
	errorCodes map[int]errorType
}

func (c *Client) do(ctx context.Context, r apiRequest) (*http.Response, error) {
	for i, p := range r.pathArgs {
		r.pathArgs[i] = url.PathEscape(fmt.Sprint(p))
	}
	path := fmt.Sprintf(r.pathFmt, r.pathArgs...)
	if r.queryParams != nil {
		if q := encodeQuery(r.queryParams); len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	bodyReader, contentType := r.rawBody, r.bodyContentType
	if r.body != nil {
		b, err := json.Marshal(r.body)
		if err != nil {
			return nil, err
		}
		bodyReader, contentType = bytes.NewReader(b), "application/json"
	}
	req, err := http.NewRequestWithContext(ctx, r.method, c.BaseURL+path, bodyReader)
	if err != nil {
		return nil, err
	}
	for key, vals := range c.Headers {
		for _, val := range vals {
			req.Header.Add(key, val)
		}
	}
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	if r.accept != "" {
		req.Header.Set("Accept", r.accept)
	}
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	if !slices.Contains(r.successCodes, resp.StatusCode) {
		defer resp.Body.Close()
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if et, ok := r.errorCodes[resp.StatusCode]; ok {
			if typedErr := decodeErrorType(et, resp.StatusCode, body); typedErr != nil {
				return nil, typedErr
			}
		}
		return nil, &ResponseError{StatusCode: resp.StatusCode, Body: string(body)}
	}
	return resp, nil
}

func decodeErrorType(et errorType, statusCode int, body []byte) error {
	switch et {
	case errorTypeErrorResponse:
		var detail ErrorResponse
		if err := json.Unmarshal(body, &detail); err == nil {
			return &ResponseErrorResponse{StatusCode: statusCode, ErrorResponse: detail}
		}
	}
	return nil
}

// encodeQuery walks a Params struct emitted by oapi-codegen and renders its
// fields as url.Values using the "form" struct tag. Pointer fields that are
// nil are skipped. time.Time values are rendered as RFC 3339. Slice fields
// (including named-element slices like []Enum) are exploded into one repeated
// query parameter per element.
func encodeQuery(p any) url.Values {
	q := url.Values{}
	v := reflect.ValueOf(p)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		tag := t.Field(i).Tag.Get("form")
		if tag == "" || tag == "-" {
			continue
		}
		name := strings.SplitN(tag, ",", 2)[0]
		if name == "" {
			continue
		}
		fv := v.Field(i)
		if fv.Kind() == reflect.Ptr {
			if fv.IsNil() {
				continue
			}
			fv = fv.Elem()
		}
		if fv.Kind() == reflect.Slice {
			for j := 0; j < fv.Len(); j++ {
				q.Add(name, fmt.Sprint(fv.Index(j).Interface()))
			}
			continue
		}
		switch x := fv.Interface().(type) {
		case time.Time:
			q.Set(name, x.Format(time.RFC3339))
		default:
			switch fv.Kind() {
			case reflect.String:
				q.Set(name, fv.String())
			case reflect.Bool:
				q.Set(name, strconv.FormatBool(fv.Bool()))
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				q.Set(name, strconv.FormatInt(fv.Int(), 10))
			case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
				q.Set(name, strconv.FormatUint(fv.Uint(), 10))
			case reflect.Float32, reflect.Float64:
				q.Set(name, strconv.FormatFloat(fv.Float(), 'g', -1, 64))
			default:
				q.Set(name, fmt.Sprint(fv.Interface()))
			}
		}
	}
	return q
}

func doJSON[T any](c *Client, ctx context.Context, r apiRequest) (*T, error) {
	resp, err := c.do(ctx, r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		return nil, fmt.Errorf("unexpected content type %q, expected application/json", ct)
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var result T
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// doJSONWithStatus reads a JSON body and pairs it with the status, for
// operations whose success statuses return different types.
func (c *Client) doJSONWithStatus(ctx context.Context, r apiRequest) (int, []byte, error) {
	resp, err := c.do(ctx, r)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		return 0, nil, fmt.Errorf("unexpected content type %q, expected application/json", ct)
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, nil, err
	}
	return resp.StatusCode, respBody, nil
}
