// Code generated by oapi-codegen. DO NOT EDIT.

package sandboxapi

import (
	"encoding/json"
)

// Defines values for ArchiveChangeKind.
const (
	ArchiveChangeKind_added    ArchiveChangeKind = "added"
	ArchiveChangeKind_deleted  ArchiveChangeKind = "deleted"
	ArchiveChangeKind_modified ArchiveChangeKind = "modified"
)

// Valid indicates whether the value is a known member of the ArchiveChangeKind enum.
func (e ArchiveChangeKind) Valid() bool {
	switch e {
	case ArchiveChangeKind_added:
		return true
	case ArchiveChangeKind_deleted:
		return true
	case ArchiveChangeKind_modified:
		return true
	default:
		return false
	}
}

// Defines values for ArchiveExportState.
const (
	ArchiveExportState_failed    ArchiveExportState = "failed"
	ArchiveExportState_running   ArchiveExportState = "running"
	ArchiveExportState_succeeded ArchiveExportState = "succeeded"
)

// Valid indicates whether the value is a known member of the ArchiveExportState enum.
func (e ArchiveExportState) Valid() bool {
	switch e {
	case ArchiveExportState_failed:
		return true
	case ArchiveExportState_running:
		return true
	case ArchiveExportState_succeeded:
		return true
	default:
		return false
	}
}

// Defines values for ArchiveQuiesceState.
const (
	ArchiveQuiesceState_active    ArchiveQuiesceState = "active"
	ArchiveQuiesceState_quiesced  ArchiveQuiesceState = "quiesced"
	ArchiveQuiesceState_quiescing ArchiveQuiesceState = "quiescing"
	ArchiveQuiesceState_restoring ArchiveQuiesceState = "restoring"
)

// Valid indicates whether the value is a known member of the ArchiveQuiesceState enum.
func (e ArchiveQuiesceState) Valid() bool {
	switch e {
	case ArchiveQuiesceState_active:
		return true
	case ArchiveQuiesceState_quiesced:
		return true
	case ArchiveQuiesceState_quiescing:
		return true
	case ArchiveQuiesceState_restoring:
		return true
	default:
		return false
	}
}

// Defines values for ArchiveRestoreState.
const (
	ArchiveRestoreState_downloading ArchiveRestoreState = "downloading"
	ArchiveRestoreState_extracting  ArchiveRestoreState = "extracting"
	ArchiveRestoreState_failed      ArchiveRestoreState = "failed"
	ArchiveRestoreState_relaunching ArchiveRestoreState = "relaunching"
	ArchiveRestoreState_succeeded   ArchiveRestoreState = "succeeded"
)

// Valid indicates whether the value is a known member of the ArchiveRestoreState enum.
func (e ArchiveRestoreState) Valid() bool {
	switch e {
	case ArchiveRestoreState_downloading:
		return true
	case ArchiveRestoreState_extracting:
		return true
	case ArchiveRestoreState_failed:
		return true
	case ArchiveRestoreState_relaunching:
		return true
	case ArchiveRestoreState_succeeded:
		return true
	default:
		return false
	}
}

// Defines values for ProcessResponseStatus.
const (
	ProcessResponseStatus_completed ProcessResponseStatus = "completed"
	ProcessResponseStatus_failed    ProcessResponseStatus = "failed"
	ProcessResponseStatus_killed    ProcessResponseStatus = "killed"
	ProcessResponseStatus_running   ProcessResponseStatus = "running"
	ProcessResponseStatus_stopped   ProcessResponseStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ProcessResponseStatus enum.
func (e ProcessResponseStatus) Valid() bool {
	switch e {
	case ProcessResponseStatus_completed:
		return true
	case ProcessResponseStatus_failed:
		return true
	case ProcessResponseStatus_killed:
		return true
	case ProcessResponseStatus_running:
		return true
	case ProcessResponseStatus_stopped:
		return true
	default:
		return false
	}
}

// Defines values for ProcessUpgradeState.
const (
	ProcessUpgradeState_completed ProcessUpgradeState = "completed"
	ProcessUpgradeState_failed    ProcessUpgradeState = "failed"
	ProcessUpgradeState_idle      ProcessUpgradeState = "idle"
	ProcessUpgradeState_running   ProcessUpgradeState = "running"
)

// Valid indicates whether the value is a known member of the ProcessUpgradeState enum.
func (e ProcessUpgradeState) Valid() bool {
	switch e {
	case ProcessUpgradeState_completed:
		return true
	case ProcessUpgradeState_failed:
		return true
	case ProcessUpgradeState_idle:
		return true
	case ProcessUpgradeState_running:
		return true
	default:
		return false
	}
}

// ApplyEditRequest defines model for ApplyEditRequest.
type ApplyEditRequest struct {
	CodeEdit string  `json:"codeEdit"`
	Model    *string `json:"model,omitempty"`
}

// ApplyEditResponse defines model for ApplyEditResponse.
type ApplyEditResponse struct {
	Message         *string `json:"message,omitempty"`
	OriginalContent *string `json:"originalContent,omitempty"`
	Path            *string `json:"path,omitempty"`
	Provider        *string `json:"provider,omitempty"`
	Success         *bool   `json:"success,omitempty"`
	UpdatedContent  *string `json:"updatedContent,omitempty"`
}

// ArchiveChange defines model for ArchiveChange.
type ArchiveChange struct {
	Kind ArchiveChangeKind `json:"kind"`

	// Path Path is relative to the root, without a leading slash.
	Path string `json:"path"`

	// Size Size is the file content size in bytes, 0 for anything but a regular file.
	Size *int `json:"size,omitempty"`
}

// ArchiveChangeKind defines model for ArchiveChangeKind.
type ArchiveChangeKind string

// ArchiveExportState defines model for ArchiveExportState.
type ArchiveExportState string

// ArchiveManifest defines model for ArchiveManifest.
type ArchiveManifest struct {
	// Added Added and Modified count the archive's payload members.
	Added *int `json:"added,omitempty"`

	// ApiVersion APIVersion is the sandbox-api build that produced the archive.
	ApiVersion *string `json:"apiVersion,omitempty"`
	CreatedAt  string  `json:"createdAt"`

	// Deleted Deleted are paths the image has and the sandbox deleted. Tar cannot carry
	// a deletion, so import applies these from the manifest.
	Deleted *[]string `json:"deleted,omitempty"`

	// Excludes Excludes are the paths left out of the comparison.
	Excludes *[]string `json:"excludes,omitempty"`

	// ImageDevice ImageDevice is the device the pristine image was read from, for the record:
	// it says where the sandbox that exported the archive found its image.
	ImageDevice *string `json:"imageDevice,omitempty"`
	Modified    *int    `json:"modified,omitempty"`

	// PayloadBytes PayloadBytes is the total content size of the payload members.
	PayloadBytes *int `json:"payloadBytes,omitempty"`

	// Processes Processes tells whether ProcessesName is present.
	Processes *bool `json:"processes,omitempty"`

	// Root Root is the directory the paths are relative to.
	Root    string `json:"root"`
	Version int    `json:"version"`
}

// ArchiveQuiesceState defines model for ArchiveQuiesceState.
type ArchiveQuiesceState string

// ArchiveRestoreState defines model for ArchiveRestoreState.
type ArchiveRestoreState string

// ContentSearchMatch defines model for ContentSearchMatch.
type ContentSearchMatch struct {
	Column  int     `json:"column"`
	Context *string `json:"context,omitempty"`
	Line    int     `json:"line"`
	Path    string  `json:"path"`
	Text    string  `json:"text"`
}

// ContentSearchResponse defines model for ContentSearchResponse.
type ContentSearchResponse struct {
	Matches []ContentSearchMatch `json:"matches"`
	Query   string               `json:"query"`
	Total   int                  `json:"total"`
}

// DeleteNetworkProcessMonitorResponse defines model for DeleteNetworkProcessMonitorResponse.
type DeleteNetworkProcessMonitorResponse map[string]interface{}

// Directory defines model for Directory.
type Directory struct {
	Files []File `json:"files"`
	Name  string `json:"name"`
	Path  string `json:"path"`

	// Subdirectories @name Subdirectories
	Subdirectories []Subdirectory `json:"subdirectories"`
}

// DriveListResponse defines model for DriveListResponse.
type DriveListResponse struct {
	Mounts *[]DriveMountInfo `json:"mounts,omitempty"`
}

// DriveMountInfo defines model for DriveMountInfo.
type DriveMountInfo struct {
	DriveName *string `json:"driveName,omitempty"`
	DrivePath *string `json:"drivePath,omitempty"`

	// GidMap The local GID used for this mount
	GidMap    *string `json:"gidMap,omitempty"`
	MountPath *string `json:"mountPath,omitempty"`
	ReadOnly  *bool   `json:"readOnly,omitempty"`

	// UidMap The local UID used for this mount
	UidMap *string `json:"uidMap,omitempty"`
}

// DriveMountRequest defines model for DriveMountRequest.
type DriveMountRequest struct {
	DriveName string `json:"driveName"`

	// DrivePath Optional, defaults to "/"
	DrivePath *string `json:"drivePath,omitempty"`

	// GidMap Optional, local GID to map (filer GID is always 0)
	GidMap    *string `json:"gidMap,omitempty"`
	MountPath string  `json:"mountPath"`

	// ReadOnly Optional, defaults to false
	ReadOnly *bool `json:"readOnly,omitempty"`

	// UidMap Optional, local UID to map (filer UID is always 0)
	UidMap *string `json:"uidMap,omitempty"`
}

// DriveMountResponse defines model for DriveMountResponse.
type DriveMountResponse struct {
	DriveName *string `json:"driveName,omitempty"`
	DrivePath *string `json:"drivePath,omitempty"`

	// GidMap The local GID used for this mount
	GidMap    *string `json:"gidMap,omitempty"`
	Message   *string `json:"message,omitempty"`
	MountPath *string `json:"mountPath,omitempty"`
	ReadOnly  *bool   `json:"readOnly,omitempty"`
	Success   *bool   `json:"success,omitempty"`

	// UidMap The local UID used for this mount
	UidMap *string `json:"uidMap,omitempty"`
}

// DriveUnmountResponse defines model for DriveUnmountResponse.
type DriveUnmountResponse struct {
	Message   *string `json:"message,omitempty"`
	MountPath *string `json:"mountPath,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExportOptions defines model for ExportOptions.
type ExportOptions struct {
	// Async Async starts the export and answers immediately, leaving it to run: an
	// archive of a large filesystem takes longer than a request may be held
	// open. Its progress is reported by /archive/status.
	Async *bool `json:"async,omitempty"`

	// DryRun DryRun reports what would be archived, and its exact size, without
	// stopping anything and without uploading.
	DryRun *bool `json:"dryRun,omitempty"`

	// Excludes Excludes are added to the paths excluded by default.
	Excludes *[]string `json:"excludes,omitempty"`

	// Headers Headers are sent with the upload request as given. A presigned URL only
	// accepts the headers it was signed for, so these have to match what the
	// caller signed: sending one that was not signed, or signing one that is not
	// sent, is rejected as a signature mismatch. Typical use is a storage class,
	// x-amz-storage-class: GLACIER_IR.
	Headers *map[string]string `json:"headers,omitempty"`

	// ImageDevice ImageDevice is the device holding the pristine image. It is found on its
	// own, wherever the sandbox booted from attached it, and naming one here
	// only overrides that.
	ImageDevice *string `json:"imageDevice,omitempty"`

	// ImageMountPoint ImageMountPoint is a directory where the pristine image is already mounted.
	// When set the image device is neither mounted nor unmounted.
	ImageMountPoint *string `json:"imageMountPoint,omitempty"`

	// Multipart Multipart uploads the archive part by part instead, which is how an
	// archive larger than the 5 GB a single PUT accepts is stored. It takes
	// precedence over URL.
	Multipart *MultipartUpload `json:"multipart,omitempty"`

	// SaveProcesses SaveProcesses stores the process list in the archive so restore can
	// relaunch the workload. Defaults to true; set it to false to archive
	// storage only.
	SaveProcesses *bool `json:"saveProcesses,omitempty"`

	// StopTimeoutSeconds StopTimeoutSeconds bounds the graceful stop of each process.
	StopTimeoutSeconds *int `json:"stopTimeoutSeconds,omitempty"`

	// Url URL is a presigned S3 PUT URL the archive is streamed to. Empty is only
	// valid with DryRun, or with Multipart.
	Url *string `json:"url,omitempty"`
}

// ExportProgress defines model for ExportProgress.
type ExportProgress struct {
	// Error Error is why the export failed, without the presigned URL it used.
	Error      *string `json:"error,omitempty"`
	FinishedAt *string `json:"finishedAt,omitempty"`

	// Size Size is the archive's exact size, known once the filesystem is scanned.
	Size      *int                `json:"size,omitempty"`
	StartedAt *string             `json:"startedAt,omitempty"`
	State     *ArchiveExportState `json:"state,omitempty"`

	// Uploaded Uploaded reports whether the storage holds the archive.
	Uploaded *bool `json:"uploaded,omitempty"`
}

// ExportResult defines model for ExportResult.
type ExportResult struct {
	// Changes Changes lists every path in the archive. Only filled for a dry run,
	// where it is the point of the call.
	Changes  *[]ArchiveChange `json:"changes,omitempty"`
	Duration *string          `json:"duration,omitempty"`
	Manifest ArchiveManifest  `json:"manifest"`

	// Size Size is the exact number of bytes uploaded, known before the upload
	// starts since the archive is not compressed.
	Size *int `json:"size,omitempty"`

	// StoppedProcesses StoppedProcesses are the processes stopped to freeze the filesystem.
	StoppedProcesses *[]string `json:"stoppedProcesses,omitempty"`

	// Uploaded Uploaded is false for a dry run.
	Uploaded *bool `json:"uploaded,omitempty"`
}

// File defines model for File.
type File struct {
	Group        string `json:"group"`
	LastModified string `json:"lastModified"`
	Name         string `json:"name"`
	Owner        string `json:"owner"`
	Path         string `json:"path"`
	Permissions  string `json:"permissions"`
	Size         int    `json:"size"`
}

// FileRequest defines model for FileRequest.
type FileRequest struct {
	Content     *string `json:"content,omitempty"`
	IsDirectory *bool   `json:"isDirectory,omitempty"`
	Permissions *string `json:"permissions,omitempty"`
}

// FileWithContent defines model for FileWithContent.
type FileWithContent struct {
	Content      string `json:"content"`
	Group        string `json:"group"`
	LastModified string `json:"lastModified"`
	Name         string `json:"name"`
	Owner        string `json:"owner"`
	Path         string `json:"path"`
	Permissions  string `json:"permissions"`
	Size         int    `json:"size"`
}

// FilesystemMultipartUpload defines model for FilesystemMultipartUpload.
type FilesystemMultipartUpload struct {
	InitiatedAt *string                            `json:"initiatedAt,omitempty"`
	Parts       *map[string]FilesystemUploadedPart `json:"parts,omitempty"`
	Path        *string                            `json:"path,omitempty"`
	Permissions *int                               `json:"permissions,omitempty"`
	UploadId    *string                            `json:"uploadId,omitempty"`
}

// FilesystemUploadedPart defines model for FilesystemUploadedPart.
type FilesystemUploadedPart struct {
	Etag       *string `json:"etag,omitempty"`
	PartNumber *int    `json:"partNumber,omitempty"`
	Size       *int    `json:"size,omitempty"`
	UploadedAt *string `json:"uploadedAt,omitempty"`
}

// FindMatch defines model for FindMatch.
type FindMatch struct {
	Path string `json:"path"`

	// Type "file" or "directory"
	Type string `json:"type"`
}

// FindResponse defines model for FindResponse.
type FindResponse struct {
	Matches []FindMatch `json:"matches"`
	Total   int         `json:"total"`
}

// FuzzySearchMatch defines model for FuzzySearchMatch.
type FuzzySearchMatch struct {
	Path  string `json:"path"`
	Score int    `json:"score"`

	// Type "file" or "directory"
	Type string `json:"type"`
}

// FuzzySearchResponse defines model for FuzzySearchResponse.
type FuzzySearchResponse struct {
	Matches []FuzzySearchMatch `json:"matches"`
	Total   int                `json:"total"`
}

// GetFilesystemResponse defines model for GetFilesystemResponse.
type GetFilesystemResponse struct {
	union json.RawMessage
}

// GetFilesystemResponse2 defines model for .
type GetFilesystemResponse2 = []byte

// GetFilesystemTreeResponse defines model for GetFilesystemTreeResponse.
type GetFilesystemTreeResponse struct {
	union json.RawMessage
}

// GetFilesystemTreeResponse2 defines model for .
type GetFilesystemTreeResponse2 = []byte

// GetNetworkProcessPortsResponse defines model for GetNetworkProcessPortsResponse.
type GetNetworkProcessPortsResponse map[string]interface{}

// GetProcessResponse defines model for GetProcessResponse.
type GetProcessResponse = []ProcessResponse

// HandlerReloadResponse defines model for HandlerReloadResponse.
type HandlerReloadResponse struct {
	Applied    *int `json:"applied,omitempty"`
	Generation *int `json:"generation,omitempty"`
	Removed    *int `json:"removed,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Arch          string        `json:"arch"`
	BuildTime     string        `json:"buildTime"`
	GitCommit     string        `json:"gitCommit"`
	GoVersion     string        `json:"goVersion"`
	LastUpgrade   UpgradeStatus `json:"lastUpgrade"`
	Os            string        `json:"os"`
	StartedAt     string        `json:"startedAt"`
	Status        string        `json:"status"`
	UpgradeCount  int           `json:"upgradeCount"`
	Uptime        string        `json:"uptime"`
	UptimeSeconds float32       `json:"uptimeSeconds"`
	Version       string        `json:"version"`
}

// MultipartCompleteRequest defines model for MultipartCompleteRequest.
type MultipartCompleteRequest struct {
	Parts *[]MultipartPartInfo `json:"parts,omitempty"`
}

// MultipartInitiateRequest defines model for MultipartInitiateRequest.
type MultipartInitiateRequest struct {
	Permissions *string `json:"permissions,omitempty"`
}

// MultipartInitiateResponse defines model for MultipartInitiateResponse.
type MultipartInitiateResponse struct {
	Path     *string `json:"path,omitempty"`
	UploadId *string `json:"uploadId,omitempty"`
}

// MultipartListPartsResponse defines model for MultipartListPartsResponse.
type MultipartListPartsResponse struct {
	Parts    *[]FilesystemUploadedPart `json:"parts,omitempty"`
	UploadId *string                   `json:"uploadId,omitempty"`
}

// MultipartListUploadsResponse defines model for MultipartListUploadsResponse.
type MultipartListUploadsResponse struct {
	Uploads *[]FilesystemMultipartUpload `json:"uploads,omitempty"`
}

// MultipartPartInfo defines model for MultipartPartInfo.
type MultipartPartInfo struct {
	Etag       *string `json:"etag,omitempty"`
	PartNumber *int    `json:"partNumber,omitempty"`
}

// MultipartUpload defines model for MultipartUpload.
type MultipartUpload struct {
	// AbortUrl AbortURL is a presigned DELETE URL that discards the parts already
	// uploaded. Without it a failed export leaves them on the storage until a
	// lifecycle rule removes them.
	AbortUrl *string `json:"abortUrl,omitempty"`

	// CompleteUrl CompleteURL is a presigned POST URL that assembles the parts.
	CompleteUrl *string `json:"completeUrl,omitempty"`

	// PartSize PartSize is the number of bytes sent to every part but the last.
	PartSize *int `json:"partSize,omitempty"`

	// PartUrls PartURLs are presigned PUT URLs, one per part, in order. Extra ones are
	// left unused.
	PartUrls *[]string `json:"partUrls,omitempty"`
}

// MultipartUploadPartResponse defines model for MultipartUploadPartResponse.
type MultipartUploadPartResponse struct {
	Etag       *string `json:"etag,omitempty"`
	PartNumber *int    `json:"partNumber,omitempty"`
	Size       *int    `json:"size,omitempty"`
}

// PortMonitorRequest defines model for PortMonitorRequest.
type PortMonitorRequest struct {
	// Callback URL to call when a new port is detected
	Callback *string `json:"callback,omitempty"`
}

// PostNetworkProcessMonitorResponse defines model for PostNetworkProcessMonitorResponse.
type PostNetworkProcessMonitorResponse map[string]interface{}

// ProcessLogs defines model for ProcessLogs.
type ProcessLogs struct {
	Logs   string `json:"logs"`
	Stderr string `json:"stderr"`
	Stdout string `json:"stdout"`
}

// ProcessRequest defines model for ProcessRequest.
type ProcessRequest struct {
	Command string             `json:"command"`
	Env     *map[string]string `json:"env,omitempty"`

	// KeepAlive Disable scale-to-zero while process runs. Default timeout is 600s (10 minutes). Set timeout to 0 for infinite.
	KeepAlive *bool `json:"keepAlive,omitempty"`

	// MaxRestarts Maximum number of restarts on failure. Set to a negative value (e.g. -1) for unlimited restarts.
	MaxRestarts      *int    `json:"maxRestarts,omitempty"`
	Name             *string `json:"name,omitempty"`
	RestartOnFailure *bool   `json:"restartOnFailure,omitempty"`

	// Stdin Open a writable stdin pipe, fed via POST /process/{identifier}/stdin and closed via DELETE. The pipe does not survive a sandbox-api restart: the process then sees EOF.
	Stdin *bool `json:"stdin,omitempty"`

	// Timeout Timeout in seconds. When keepAlive is true, defaults to 600s (10 minutes). Set to 0 for infinite (no auto-kill).
	Timeout           *int    `json:"timeout,omitempty"`
	WaitForCompletion *bool   `json:"waitForCompletion,omitempty"`
	WaitForPorts      *[]int  `json:"waitForPorts,omitempty"`
	WorkingDir        *string `json:"workingDir,omitempty"`
}

// ProcessResponse defines model for ProcessResponse.
type ProcessResponse struct {
	Command     string `json:"command"`
	CompletedAt string `json:"completedAt"`
	ExitCode    int    `json:"exitCode"`

	// KeepAlive Whether scale-to-zero is disabled for this process
	KeepAlive        *bool                 `json:"keepAlive,omitempty"`
	Logs             string                `json:"logs"`
	MaxRestarts      *int                  `json:"maxRestarts,omitempty"`
	Name             string                `json:"name"`
	Pid              string                `json:"pid"`
	RestartCount     *int                  `json:"restartCount,omitempty"`
	RestartOnFailure *bool                 `json:"restartOnFailure,omitempty"`
	StartedAt        string                `json:"startedAt"`
	Status           ProcessResponseStatus `json:"status"`
	Stderr           string                `json:"stderr"`

	// Stdin Whether the process was started with a writable stdin pipe
	Stdin      *bool  `json:"stdin,omitempty"`
	Stdout     string `json:"stdout"`
	WorkingDir string `json:"workingDir"`
}

// ProcessResponseStatus defines model for ProcessResponse.Status.
type ProcessResponseStatus string

// ProcessUpgradeState defines model for ProcessUpgradeState.
type ProcessUpgradeState string

// PutFilesystemTreeResponse defines model for PutFilesystemTreeResponse.
type PutFilesystemTreeResponse struct {
	union json.RawMessage
}

// PutFilesystemTreeResponse2 defines model for .
type PutFilesystemTreeResponse2 = []byte

// QuiesceStatus defines model for QuiesceStatus.
type QuiesceStatus struct {
	// Export Export reports the export started asynchronously, if there was one. It is
	// how a caller that did not wait for the export learns that the archive is
	// on the storage, or why it is not.
	Export *ExportProgress `json:"export,omitempty"`

	// ReadOnlyRoot ReadOnlyRoot reports whether the root mount was remounted read-only, which
	// is what actually stops writes; false means the freeze relies only on the
	// API refusing calls, and the reason says why.
	ReadOnlyRoot *bool `json:"readOnlyRoot,omitempty"`

	// Reason Reason is a human readable explanation of why the sandbox is frozen.
	Reason *string `json:"reason,omitempty"`

	// Restore Restore reports the archive this sandbox was started from, if it was
	// started from one: how far its restore has got, and how it ended.
	Restore *RestoreProgress `json:"restore,omitempty"`

	// Since Since is when the sandbox left StateActive.
	Since *string             `json:"since,omitempty"`
	State ArchiveQuiesceState `json:"state"`

	// StoppedProcesses StoppedProcesses are the process identifiers stopped while quiescing.
	StoppedProcesses *[]string `json:"stoppedProcesses,omitempty"`
}

// RankedFile defines model for RankedFile.
type RankedFile struct {
	Content *string  `json:"content,omitempty"`
	Path    *string  `json:"path,omitempty"`
	Score   *float32 `json:"score,omitempty"`
}

// RerankingResponse defines model for RerankingResponse.
type RerankingResponse struct {
	Files   *[]RankedFile `json:"files,omitempty"`
	Message *string       `json:"message,omitempty"`
	Success *bool         `json:"success,omitempty"`
}

// RestoreProgress defines model for RestoreProgress.
type RestoreProgress struct {
	Deleted *int `json:"deleted,omitempty"`

	// Downloaded Downloaded is how much of the archive has been read so far.
	Downloaded *int `json:"downloaded,omitempty"`

	// Error Error is why the restore failed, without the presigned URL it used.
	Error      *string `json:"error,omitempty"`
	FinishedAt *string `json:"finishedAt,omitempty"`

	// Restored Restored and Deleted count what the archive changed on the filesystem.
	Restored *int `json:"restored,omitempty"`

	// Size Size is the archive's size as the storage announced it, and zero when it
	// announced none - a client showing a percentage has to allow for that.
	Size      *int                 `json:"size,omitempty"`
	StartedAt *string              `json:"startedAt,omitempty"`
	State     *ArchiveRestoreState `json:"state,omitempty"`
}

// Subdirectory defines model for Subdirectory.
type Subdirectory struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Message string  `json:"message"`
	Path    *string `json:"path,omitempty"`
}

// TreeRequest defines model for TreeRequest.
type TreeRequest struct {
	Files *map[string]string `json:"files,omitempty"`
}

// TunnelConfigRequest defines model for TunnelConfigRequest.
type TunnelConfigRequest struct {
	// Config Base64-encoded tunnel config JSON
	Config string `json:"config"`
}

// UpgradeRequest defines model for UpgradeRequest.
type UpgradeRequest struct {
	// BaseUrl Base URL for releases (useful for forks)
	BaseUrl *string `json:"baseUrl,omitempty"`

	// Version Version to upgrade to: "latest" (default), "develop", "main", or specific tag like "v1.0.0"
	Version *string `json:"version,omitempty"`
}

// UpgradeStatus defines model for UpgradeStatus.
type UpgradeStatus struct {
	// BinaryPath Path to downloaded binary
	BinaryPath *string `json:"binaryPath,omitempty"`

	// BytesDownloaded Bytes downloaded
	BytesDownloaded *int `json:"bytesDownloaded,omitempty"`

	// DownloadUrl URL used for download
	DownloadUrl *string `json:"downloadUrl,omitempty"`

	// Error Error message if failed
	Error *string `json:"error,omitempty"`

	// LastAttempt When the upgrade was attempted
	LastAttempt *string `json:"lastAttempt,omitempty"`

	// Status Current state (idle, running, completed, failed)
	Status ProcessUpgradeState `json:"status"`

	// Step Current/last step (none, starting, download, validate, replace, completed, skipped)
	Step string `json:"step"`

	// Version Version being upgraded to
	Version string `json:"version"`
}

// GetCodegenRerankingPathParams defines parameters for GetCodegenRerankingPath.
type GetCodegenRerankingPathParams struct {
	// Query Natural language query to search for
	Query string `form:"query" json:"query"`

	// ScoreThreshold Minimum relevance score (default: 0.5)
	ScoreThreshold *float32 `form:"scoreThreshold,omitempty" json:"scoreThreshold,omitempty"`

	// TokenLimit Maximum tokens to return (default: 30000)
	TokenLimit *int `form:"tokenLimit,omitempty" json:"tokenLimit,omitempty"`

	// FilePattern Regex pattern to filter files (e.g., .*\\.ts$ for TypeScript files)
	FilePattern *string `form:"filePattern,omitempty" json:"filePattern,omitempty"`
}

// GetFilesystemContentSearchPathParams defines parameters for GetFilesystemContentSearchPath.
type GetFilesystemContentSearchPathParams struct {
	// Query Text to search for
	Query string `form:"query" json:"query"`

	// CaseSensitive Case sensitive search (default: false)
	CaseSensitive *bool `form:"caseSensitive,omitempty" json:"caseSensitive,omitempty"`

	// MaxResults Maximum number of results to return (default: 100)
	MaxResults *int `form:"maxResults,omitempty" json:"maxResults,omitempty"`

	// FilePattern File pattern to include (e.g., *.go)
	FilePattern *string `form:"filePattern,omitempty" json:"filePattern,omitempty"`

	// ExcludeDirs Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage)
	ExcludeDirs *string `form:"excludeDirs,omitempty" json:"excludeDirs,omitempty"`
}

// GetFilesystemFindPathParams defines parameters for GetFilesystemFindPath.
type GetFilesystemFindPathParams struct {
	// Type Type of search (file or directory)
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Patterns Comma-separated file patterns to include (e.g., *.go,*.js)
	Patterns *string `form:"patterns,omitempty" json:"patterns,omitempty"`

	// MaxResults Maximum number of results to return (default: 20). If set to 0, all results will be returned.
	MaxResults *int `form:"maxResults,omitempty" json:"maxResults,omitempty"`

	// ExcludeDirs Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories.
	ExcludeDirs *string `form:"excludeDirs,omitempty" json:"excludeDirs,omitempty"`

	// ExcludeHidden Exclude hidden files and directories (default: true)
	ExcludeHidden *bool `form:"excludeHidden,omitempty" json:"excludeHidden,omitempty"`
}

// PutFilesystemMultipartUploadIdPartMultipartBody defines parameters for PutFilesystemMultipartUploadIdPart.
type PutFilesystemMultipartUploadIdPartMultipartBody struct {
	// File Part data
	File []byte `json:"file"`
}

// PutFilesystemMultipartUploadIdPartParams defines parameters for PutFilesystemMultipartUploadIdPart.
type PutFilesystemMultipartUploadIdPartParams struct {
	// PartNumber Part number (1-10000)
	PartNumber int `form:"partNumber" json:"partNumber"`
}

// GetFilesystemSearchPathParams defines parameters for GetFilesystemSearchPath.
type GetFilesystemSearchPathParams struct {
	// MaxResults Maximum number of results to return (default: 20)
	MaxResults *int `form:"maxResults,omitempty" json:"maxResults,omitempty"`

	// Patterns Comma-separated file patterns to include (e.g., *.go,*.js)
	Patterns *string `form:"patterns,omitempty" json:"patterns,omitempty"`

	// ExcludeDirs Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories.
	ExcludeDirs *string `form:"excludeDirs,omitempty" json:"excludeDirs,omitempty"`

	// ExcludeHidden Exclude hidden files and directories (default: true)
	ExcludeHidden *bool `form:"excludeHidden,omitempty" json:"excludeHidden,omitempty"`
}

// DeleteFilesystemTreePathParams defines parameters for DeleteFilesystemTreePath.
type DeleteFilesystemTreePathParams struct {
	// Recursive Delete directory recursively
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// DeleteFilesystemPathParams defines parameters for DeleteFilesystemPath.
type DeleteFilesystemPathParams struct {
	// Recursive Delete directory recursively
	Recursive *bool `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// GetFilesystemPathParams defines parameters for GetFilesystemPath.
type GetFilesystemPathParams struct {
	// Download Force download mode for files
	Download *bool `form:"download,omitempty" json:"download,omitempty"`
}

// GetWatchFilesystemPathParams defines parameters for GetWatchFilesystemPath.
type GetWatchFilesystemPathParams struct {
	// Ignore Ignore patterns (comma-separated)
	Ignore *string `form:"ignore,omitempty" json:"ignore,omitempty"`
}

// PostArchiveExportJSONRequestBody defines body for PostArchiveExport for application/json ContentType.
type PostArchiveExportJSONRequestBody = ExportOptions

// PutCodegenFastapplyPathJSONRequestBody defines body for PutCodegenFastapplyPath for application/json ContentType.
type PutCodegenFastapplyPathJSONRequestBody = ApplyEditRequest

// PostDrivesMountJSONRequestBody defines body for PostDrivesMount for application/json ContentType.
type PostDrivesMountJSONRequestBody = DriveMountRequest

// PostFilesystemMultipartInitiatePathJSONRequestBody defines body for PostFilesystemMultipartInitiatePath for application/json ContentType.
type PostFilesystemMultipartInitiatePathJSONRequestBody = MultipartInitiateRequest

// PostFilesystemMultipartUploadIdCompleteJSONRequestBody defines body for PostFilesystemMultipartUploadIdComplete for application/json ContentType.
type PostFilesystemMultipartUploadIdCompleteJSONRequestBody = MultipartCompleteRequest

// PutFilesystemMultipartUploadIdPartMultipartRequestBody defines body for PutFilesystemMultipartUploadIdPart for multipart/form-data ContentType.
type PutFilesystemMultipartUploadIdPartMultipartRequestBody PutFilesystemMultipartUploadIdPartMultipartBody

// PutFilesystemTreePathJSONRequestBody defines body for PutFilesystemTreePath for application/json ContentType.
type PutFilesystemTreePathJSONRequestBody = TreeRequest

// PutFilesystemPathJSONRequestBody defines body for PutFilesystemPath for application/json ContentType.
type PutFilesystemPathJSONRequestBody = FileRequest

// PostNetworkProcessPidMonitorJSONRequestBody defines body for PostNetworkProcessPidMonitor for application/json ContentType.
type PostNetworkProcessPidMonitorJSONRequestBody = PortMonitorRequest

// PutNetworkTunnelConfigJSONRequestBody defines body for PutNetworkTunnelConfig for application/json ContentType.
type PutNetworkTunnelConfigJSONRequestBody = TunnelConfigRequest

// PostProcessJSONRequestBody defines body for PostProcess for application/json ContentType.
type PostProcessJSONRequestBody = ProcessRequest

// PostUpgradeJSONRequestBody defines body for PostUpgrade for application/json ContentType.
type PostUpgradeJSONRequestBody = UpgradeRequest

// AsDirectory returns the union data inside the GetFilesystemResponse as a Directory
func (t GetFilesystemResponse) AsDirectory() (Directory, error) {
	var body Directory
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDirectory overwrites any union data inside the GetFilesystemResponse as the provided Directory
func (t *GetFilesystemResponse) FromDirectory(v Directory) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsFileWithContent returns the union data inside the GetFilesystemResponse as a FileWithContent
func (t GetFilesystemResponse) AsFileWithContent() (FileWithContent, error) {
	var body FileWithContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileWithContent overwrites any union data inside the GetFilesystemResponse as the provided FileWithContent
func (t *GetFilesystemResponse) FromFileWithContent(v FileWithContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsGetFilesystemResponse2 returns the union data inside the GetFilesystemResponse as a GetFilesystemResponse2
func (t GetFilesystemResponse) AsGetFilesystemResponse2() (GetFilesystemResponse2, error) {
	var body GetFilesystemResponse2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetFilesystemResponse2 overwrites any union data inside the GetFilesystemResponse as the provided GetFilesystemResponse2
func (t *GetFilesystemResponse) FromGetFilesystemResponse2(v GetFilesystemResponse2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t GetFilesystemResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetFilesystemResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDirectory returns the union data inside the GetFilesystemTreeResponse as a Directory
func (t GetFilesystemTreeResponse) AsDirectory() (Directory, error) {
	var body Directory
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDirectory overwrites any union data inside the GetFilesystemTreeResponse as the provided Directory
func (t *GetFilesystemTreeResponse) FromDirectory(v Directory) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsFileWithContent returns the union data inside the GetFilesystemTreeResponse as a FileWithContent
func (t GetFilesystemTreeResponse) AsFileWithContent() (FileWithContent, error) {
	var body FileWithContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileWithContent overwrites any union data inside the GetFilesystemTreeResponse as the provided FileWithContent
func (t *GetFilesystemTreeResponse) FromFileWithContent(v FileWithContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsGetFilesystemTreeResponse2 returns the union data inside the GetFilesystemTreeResponse as a GetFilesystemTreeResponse2
func (t GetFilesystemTreeResponse) AsGetFilesystemTreeResponse2() (GetFilesystemTreeResponse2, error) {
	var body GetFilesystemTreeResponse2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGetFilesystemTreeResponse2 overwrites any union data inside the GetFilesystemTreeResponse as the provided GetFilesystemTreeResponse2
func (t *GetFilesystemTreeResponse) FromGetFilesystemTreeResponse2(v GetFilesystemTreeResponse2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t GetFilesystemTreeResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetFilesystemTreeResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDirectory returns the union data inside the PutFilesystemTreeResponse as a Directory
func (t PutFilesystemTreeResponse) AsDirectory() (Directory, error) {
	var body Directory
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDirectory overwrites any union data inside the PutFilesystemTreeResponse as the provided Directory
func (t *PutFilesystemTreeResponse) FromDirectory(v Directory) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsFileWithContent returns the union data inside the PutFilesystemTreeResponse as a FileWithContent
func (t PutFilesystemTreeResponse) AsFileWithContent() (FileWithContent, error) {
	var body FileWithContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFileWithContent overwrites any union data inside the PutFilesystemTreeResponse as the provided FileWithContent
func (t *PutFilesystemTreeResponse) FromFileWithContent(v FileWithContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsPutFilesystemTreeResponse2 returns the union data inside the PutFilesystemTreeResponse as a PutFilesystemTreeResponse2
func (t PutFilesystemTreeResponse) AsPutFilesystemTreeResponse2() (PutFilesystemTreeResponse2, error) {
	var body PutFilesystemTreeResponse2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPutFilesystemTreeResponse2 overwrites any union data inside the PutFilesystemTreeResponse as the provided PutFilesystemTreeResponse2
func (t *PutFilesystemTreeResponse) FromPutFilesystemTreeResponse2(v PutFilesystemTreeResponse2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t PutFilesystemTreeResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PutFilesystemTreeResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
