// Code generated by apigen/clientgen. DO NOT EDIT.

// Package managementapi is a generated client for the Baseten managementapi.
//
// Types and methods in this package are generated from the OpenAPI
// specification and are NOT covered by any stability or compatibility
// guarantees. They may change without notice between versions.
package managementapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"strconv"
	"strings"
	"time"
)

// Client is a generated HTTP client for the managementapi API.
//
// On HTTP failure, methods return [*ResponseError] unless documented
// otherwise on the method.
type Client struct {
	BaseURL    string
	HTTPClient interface {
		Do(*http.Request) (*http.Response, error)
	}
	// Headers are added to every request.
	Headers http.Header
}

// ResponseError represents a non-success HTTP response whose body could not
// be decoded into a typed error.
type ResponseError struct {
	StatusCode int
	Body       string
}

func (e *ResponseError) Error() string {
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, e.Body)
}

// DeleteApiKeys: Deletes an API key by prefix
func (c *Client) DeleteApiKeys(ctx context.Context, apiKeyPrefix string) (*APIKeyTombstone, error) {
	return doJSON[APIKeyTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/api_keys/%s",
		pathArgs:    []any{apiKeyPrefix},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteChains: Deletes a chain by ID
func (c *Client) DeleteChains(ctx context.Context, chainId string) (*ChainTombstone, error) {
	return doJSON[ChainTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/chains/%s",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteChainsDeployments: Deletes a chain deployment by ID
func (c *Client) DeleteChainsDeployments(ctx context.Context, chainId string, chainDeploymentId string) (*ChainDeploymentTombstone, error) {
	return doJSON[ChainDeploymentTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/chains/%s/deployments/%s",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteLibraryListings: Deletes a library listing
func (c *Client) DeleteLibraryListings(ctx context.Context, userDefinedListingId string) (*LibraryListingTombstone, error) {
	return doJSON[LibraryListingTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteLibraryListingsVersions: Deletes a library listing version
func (c *Client) DeleteLibraryListingsVersions(ctx context.Context, userDefinedListingId string, versionTag string) (*LibraryListingVersionTombstone, error) {
	return doJSON[LibraryListingVersionTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModels: Deletes a model by ID
func (c *Client) DeleteModels(ctx context.Context, modelId string) (*ModelTombstone, error) {
	return doJSON[ModelTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModelsDeployments: Deletes a model's deployment by ID
func (c *Client) DeleteModelsDeployments(ctx context.Context, modelId string, deploymentId string) (*DeploymentTombstone, error) {
	return doJSON[DeploymentTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s/deployments/%s",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModelsDeploymentsReplicas: Terminates a replica in a deployment
func (c *Client) DeleteModelsDeploymentsReplicas(ctx context.Context, modelId string, deploymentId string, replicaId string) (*TerminateReplicaResponse, error) {
	return doJSON[TerminateReplicaResponse](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s/deployments/%s/replicas/%s",
		pathArgs:    []any{modelId, deploymentId, replicaId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteSecrets: Deletes a secret by name
func (c *Client) DeleteSecrets(ctx context.Context, secretName string) (*SecretTombstone, error) {
	return doJSON[SecretTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/secrets/%s",
		pathArgs:    []any{secretName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteTeamsSecrets: Deletes a secret by name
func (c *Client) DeleteTeamsSecrets(ctx context.Context, teamId string, secretName string) (*SecretTombstone, error) {
	return doJSON[SecretTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/teams/%s/secrets/%s",
		pathArgs:    []any{teamId, secretName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteTrainingProjects: Delete a training project.
func (c *Client) DeleteTrainingProjects(ctx context.Context, trainingProjectId string) (*TrainingProjectTombstone, error) {
	return doJSON[TrainingProjectTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/training_projects/%s",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteTrainingProjectsJobs: Delete a training job.
func (c *Client) DeleteTrainingProjectsJobs(ctx context.Context, trainingProjectId string, trainingJobId string) (*TrainingJobTombstone, error) {
	return doJSON[TrainingJobTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/training_projects/%s/jobs/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetApiKeys: Lists the user's API keys (metadata only, no plain text keys)
func (c *Client) GetApiKeys(ctx context.Context) (*APIKeys, error) {
	return doJSON[APIKeys](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/api_keys",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBillingUsageSummary: Gets billing usage summary for a date range
func (c *Client) GetBillingUsageSummary(ctx context.Context, params GetV1BillingUsageSummaryParams) (*UsageSummary, error) {
	return doJSON[UsageSummary](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/billing/usage_summary",
		pathArgs:    nil,
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBlobsCredentialsModel: Get blob credentials for models.
func (c *Client) GetBlobsCredentialsModel(ctx context.Context) (*GetBlobCredentialsResponse, error) {
	return doJSON[GetBlobCredentialsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/blobs/credentials/model",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBlobsCredentialsTrain: Get blob credentials for training.
func (c *Client) GetBlobsCredentialsTrain(ctx context.Context) (*GetBlobCredentialsResponse, error) {
	return doJSON[GetBlobCredentialsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/blobs/credentials/train",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChains: Gets all chains
func (c *Client) GetChains(ctx context.Context) (*Chains, error) {
	return doJSON[Chains](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsChainId: Gets a chain by ID
func (c *Client) GetChainsChainId(ctx context.Context, chainId string) (*Chain, error) {
	return doJSON[Chain](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsDeployments: Gets all chain deployments
func (c *Client) GetChainsDeployments(ctx context.Context, chainId string) (*ChainDeployments, error) {
	return doJSON[ChainDeployments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/deployments",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsDeploymentsChainDeploymentId: Gets a chain deployment by ID
func (c *Client) GetChainsDeploymentsChainDeploymentId(ctx context.Context, chainId string, chainDeploymentId string) (*ChainDeployment, error) {
	return doJSON[ChainDeployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/deployments/%s",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsDeploymentsChainletsLogs: Gets the logs for a chainlet within a chain deployment.
func (c *Client) GetChainsDeploymentsChainletsLogs(ctx context.Context, chainId string, chainDeploymentId string, chainletId string, params GetV1ChainsChainIdDeploymentsChainDeploymentIdChainletsChainletIdLogsParams) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/deployments/%s/chainlets/%s/logs",
		pathArgs:    []any{chainId, chainDeploymentId, chainletId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsEnvironments: Get all chain environments
func (c *Client) GetChainsEnvironments(ctx context.Context, chainId string) (*Environments, error) {
	return doJSON[Environments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/environments",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsEnvironmentsEnvName: Get a chain environment's details
func (c *Client) GetChainsEnvironmentsEnvName(ctx context.Context, chainId string, envName string) (*ChainEnvironment, error) {
	return doJSON[ChainEnvironment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/environments/%s",
		pathArgs:    []any{chainId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetGatewayGroups: List groups
func (c *Client) GetGatewayGroups(ctx context.Context) (*GroupsResponse, error) {
	return doJSON[GroupsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/gateway/groups",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetGatewayGroupsApiKeys: List API keys for a group
func (c *Client) GetGatewayGroupsApiKeys(ctx context.Context, groupId string) (*KeysForGroupResponse, error) {
	return doJSON[KeysForGroupResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/gateway/groups/%s/api_keys",
		pathArgs:    []any{groupId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetGatewayGroupsApiKeysApiKeyPrefix: Get an API key for a group
func (c *Client) GetGatewayGroupsApiKeysApiKeyPrefix(ctx context.Context, groupId string, apiKeyPrefix string) (*GatewayKeyInfo, error) {
	return doJSON[GatewayKeyInfo](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/gateway/groups/%s/api_keys/%s",
		pathArgs:    []any{groupId, apiKeyPrefix},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetGatewayGroupsGroupId: Get a group
func (c *Client) GetGatewayGroupsGroupId(ctx context.Context, groupId string) (*Group, error) {
	return doJSON[Group](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/gateway/groups/%s",
		pathArgs:    []any{groupId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetInstanceTypePrices: Gets prices for available instance types.
func (c *Client) GetInstanceTypePrices(ctx context.Context) (*InstanceTypePrices, error) {
	return doJSON[InstanceTypePrices](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/instance_type_prices",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetInstanceTypes: Gets all available instance types
func (c *Client) GetInstanceTypes(ctx context.Context) (*InstanceTypes, error) {
	return doJSON[InstanceTypes](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/instance_types",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListings: Gets all library listings
func (c *Client) GetLibraryListings(ctx context.Context) (*LibraryListings, error) {
	return doJSON[LibraryListings](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsUserDefinedListingId: Gets a library listing
func (c *Client) GetLibraryListingsUserDefinedListingId(ctx context.Context, userDefinedListingId string) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsVersions: Gets all versions for a library listing
func (c *Client) GetLibraryListingsVersions(ctx context.Context, userDefinedListingId string) (*LibraryListingVersions, error) {
	return doJSON[LibraryListingVersions](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s/versions",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsVersionsVersionTag: Gets a library listing version
func (c *Client) GetLibraryListingsVersionsVersionTag(ctx context.Context, userDefinedListingId string, versionTag string) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsCapabilities: Get Loops server capabilities.
func (c *Client) GetLoopsCapabilities(ctx context.Context) (*GetLoopsCapabilitiesResponse, error) {
	return doJSON[GetLoopsCapabilitiesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/capabilities",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsCheckpoints: List Loops checkpoints.
func (c *Client) GetLoopsCheckpoints(ctx context.Context, params GetV1LoopsCheckpointsParams) (*ListLoopsCheckpointsResponse, error) {
	return doJSON[ListLoopsCheckpointsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/checkpoints",
		pathArgs:    nil,
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsCheckpointsFiles: Get Loops checkpoint files.
func (c *Client) GetLoopsCheckpointsFiles(ctx context.Context, checkpointId string) (*LoopsCheckpointFilesResponse, error) {
	return doJSON[LoopsCheckpointFilesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/checkpoints/%s/files",
		pathArgs:    []any{checkpointId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsDeployments: List Loops deployments.
func (c *Client) GetLoopsDeployments(ctx context.Context) (*ListLoopsDeploymentsResponse, error) {
	return doJSON[ListLoopsDeploymentsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/deployments",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsDeploymentsDeploymentId: Get a Loops deployment.
func (c *Client) GetLoopsDeploymentsDeploymentId(ctx context.Context, deploymentId string) (*GetLoopsDeploymentResponse, error) {
	return doJSON[GetLoopsDeploymentResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/deployments/%s",
		pathArgs:    []any{deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsDeploymentsLogs: Get logs for a Loops trainer deployment.
func (c *Client) GetLoopsDeploymentsLogs(ctx context.Context, deploymentId string, params GetV1LoopsDeploymentsDeploymentIdLogsParams) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/deployments/%s/logs",
		pathArgs:    []any{deploymentId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsRuns: List Loops runs.
func (c *Client) GetLoopsRuns(ctx context.Context, params GetV1LoopsRunsParams) (*ListLoopsRunsResponse, error) {
	return doJSON[ListLoopsRunsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/runs",
		pathArgs:    nil,
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsRunsRunId: Get a Loops run.
func (c *Client) GetLoopsRunsRunId(ctx context.Context, runId string) (*GetLoopsRunResponse, error) {
	return doJSON[GetLoopsRunResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/runs/%s",
		pathArgs:    []any{runId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsSamplers: List Loops samplers.
func (c *Client) GetLoopsSamplers(ctx context.Context) (*ListLoopsSamplersResponse, error) {
	return doJSON[ListLoopsSamplersResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/samplers",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsSamplersSamplerId: Get a Loops sampler.
func (c *Client) GetLoopsSamplersSamplerId(ctx context.Context, samplerId string) (*GetLoopsSamplerResponse, error) {
	return doJSON[GetLoopsSamplerResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/samplers/%s",
		pathArgs:    []any{samplerId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLoopsSessions: Get a Loops session.
func (c *Client) GetLoopsSessions(ctx context.Context, sessionId string) (*GetLoopsSessionResponse, error) {
	return doJSON[GetLoopsSessionResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/loops/sessions/%s",
		pathArgs:    []any{sessionId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelApisSnapshots: Get the latest model weight snapshot
func (c *Client) GetModelApisSnapshots(ctx context.Context) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/model_apis/snapshots",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelApisSnapshotsModelId: Get the latest model weight snapshot
func (c *Client) GetModelApisSnapshotsModelId(ctx context.Context, modelId string) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/model_apis/snapshots/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModels: Gets all models
func (c *Client) GetModels(ctx context.Context) (*Models, error) {
	return doJSON[Models](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeployments: Gets all deployments of a model
func (c *Client) GetModelsDeployments(ctx context.Context, modelId string) (*Deployments, error) {
	return doJSON[Deployments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsConfig: Gets a deployment's config
func (c *Client) GetModelsDeploymentsConfig(ctx context.Context, modelId string, deploymentId string, params GetV1ModelsModelIdDeploymentsDeploymentIdConfigParams) (*DeploymentConfigResponse, error) {
	return doJSON[DeploymentConfigResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/%s/config",
		pathArgs:    []any{modelId, deploymentId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsDeploymentId: Gets a model's deployment by ID
func (c *Client) GetModelsDeploymentsDeploymentId(ctx context.Context, modelId string, deploymentId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/%s",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsDevelopment: Gets a model's development deployment
func (c *Client) GetModelsDeploymentsDevelopment(ctx context.Context, modelId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/development",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsDownload: Gets a presigned download URL for a deployment's truss
func (c *Client) GetModelsDeploymentsDownload(ctx context.Context, modelId string, deploymentId string) (*DownloadDeploymentResponse, error) {
	return doJSON[DownloadDeploymentResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/%s/download",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsLogs: Gets the logs for a model deployment.
func (c *Client) GetModelsDeploymentsLogs(ctx context.Context, modelId string, deploymentId string, params GetV1ModelsModelIdDeploymentsDeploymentIdLogsParams) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/%s/logs",
		pathArgs:    []any{modelId, deploymentId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsProduction: Gets a model's production deployment
func (c *Client) GetModelsDeploymentsProduction(ctx context.Context, modelId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/production",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsEnvironments: Get all environments
func (c *Client) GetModelsEnvironments(ctx context.Context, modelId string) (*Environments, error) {
	return doJSON[Environments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/environments",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsEnvironmentsEnvName: Get an environment's details
func (c *Client) GetModelsEnvironmentsEnvName(ctx context.Context, modelId string, envName string) (*Environment, error) {
	return doJSON[Environment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/environments/%s",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsModelId: Gets a model by ID
func (c *Client) GetModelsModelId(ctx context.Context, modelId string) (*Model, error) {
	return doJSON[Model](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetSecrets: Gets all secrets (metadata only, no plain text keys)
func (c *Client) GetSecrets(ctx context.Context) (*Secrets, error) {
	return doJSON[Secrets](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/secrets",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTeams: Lists all teams
func (c *Client) GetTeams(ctx context.Context) (*Teams, error) {
	return doJSON[Teams](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/teams",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTeamsModels: Gets all models
func (c *Client) GetTeamsModels(ctx context.Context, teamId string) (*Models, error) {
	return doJSON[Models](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/teams/%s/models",
		pathArgs:    []any{teamId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTeamsSecrets: Gets all secrets for a team (metadata only, no plain text keys)
func (c *Client) GetTeamsSecrets(ctx context.Context, teamId string) (*Secrets, error) {
	return doJSON[Secrets](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/teams/%s/secrets",
		pathArgs:    []any{teamId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainerSessionsTrainersCheckpoints: List trainer server checkpoints.
func (c *Client) GetTrainerSessionsTrainersCheckpoints(ctx context.Context, sessionId string, trainerId string) (*GetTrainerServerCheckpointsResponse, error) {
	return doJSON[GetTrainerServerCheckpointsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/trainer_sessions/%s/trainers/%s/checkpoints",
		pathArgs:    []any{sessionId, trainerId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainerSessionsTrainersCheckpointsFiles: Get trainer server checkpoint files.
func (c *Client) GetTrainerSessionsTrainersCheckpointsFiles(ctx context.Context, sessionId string, trainerId string, checkpointId string) (*GetTrainerServerCheckpointFilesResponse, error) {
	return doJSON[GetTrainerServerCheckpointFilesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/trainer_sessions/%s/trainers/%s/checkpoints/%s/files",
		pathArgs:    []any{sessionId, trainerId, checkpointId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingCapacity: Get training GPU capacity.
func (c *Client) GetTrainingCapacity(ctx context.Context) (*GetTrainingGpuCapacityResponse, error) {
	return doJSON[GetTrainingGpuCapacityResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training/capacity",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjects: List training projects.
func (c *Client) GetTrainingProjects(ctx context.Context) (*ListTrainingProjectsResponse, error) {
	return doJSON[ListTrainingProjectsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsCacheSummary: Get training project cache summary.
func (c *Client) GetTrainingProjectsCacheSummary(ctx context.Context, trainingProjectId string) (*GetCacheSummaryResponse, error) {
	return doJSON[GetCacheSummaryResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/cache/summary",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobs: List training jobs.
func (c *Client) GetTrainingProjectsJobs(ctx context.Context, trainingProjectId string) (*ListTrainingJobsResponse, error) {
	return doJSON[ListTrainingJobsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsAuthCodes: Get auth codes for a training job.
func (c *Client) GetTrainingProjectsJobsAuthCodes(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetAuthCodesResponse, error) {
	return doJSON[GetAuthCodesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/auth_codes",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsCheckpointFiles: Get training job checkpoint files.
func (c *Client) GetTrainingProjectsJobsCheckpointFiles(ctx context.Context, trainingProjectId string, trainingJobId string, params GetV1TrainingProjectsTrainingProjectIdJobsTrainingJobIdCheckpointFilesParams) (*GetTrainingJobCheckpointFilesResponse, error) {
	return doJSON[GetTrainingJobCheckpointFilesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/checkpoint_files",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsCheckpoints: Get training job checkpoints.
func (c *Client) GetTrainingProjectsJobsCheckpoints(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetTrainingJobCheckpointsResponse, error) {
	return doJSON[GetTrainingJobCheckpointsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/checkpoints",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsDownload: Get the uploaded training job as a S3 Artifact
func (c *Client) GetTrainingProjectsJobsDownload(ctx context.Context, trainingProjectId string, trainingJobId string) (*DownloadTrainingJobResponse, error) {
	return doJSON[DownloadTrainingJobResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/download",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsLogs: Get the logs for a training job.
func (c *Client) GetTrainingProjectsJobsLogs(ctx context.Context, trainingProjectId string, trainingJobId string, params GetV1TrainingProjectsTrainingProjectIdJobsTrainingJobIdLogsParams) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/logs",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsMetrics: Get the metrics for a training job.
func (c *Client) GetTrainingProjectsJobsMetrics(ctx context.Context, trainingProjectId string, trainingJobId string, params GetV1TrainingProjectsTrainingProjectIdJobsTrainingJobIdMetricsParams) (*GetTrainingJobMetricsResponse, error) {
	return doJSON[GetTrainingJobMetricsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/metrics",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		queryParams: params,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsTrainingJobId: Get a training job.
func (c *Client) GetTrainingProjectsJobsTrainingJobId(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetTrainingJobResponse, error) {
	return doJSON[GetTrainingJobResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsTrainingProjectId: Get a training project.
func (c *Client) GetTrainingProjectsTrainingProjectId(ctx context.Context, trainingProjectId string) (*GetTrainingProjectResponse, error) {
	return doJSON[GetTrainingProjectResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetUsers: Gets a user by ID
func (c *Client) GetUsers(ctx context.Context, userId string) (*UserInfo, error) {
	return doJSON[UserInfo](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/users/%s",
		pathArgs:    []any{userId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchChainsEnvironments: Update a chain environment's settings
func (c *Client) PatchChainsEnvironments(ctx context.Context, chainId string, envName string, body UpdateChainEnvironmentRequest) (*UpdateChainEnvironmentResponse, error) {
	return doJSON[UpdateChainEnvironmentResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/chains/%s/environments/%s",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchChainsEnvironmentsChainletSettingsAutoscalingSettings: Update a chainlet environment's autoscaling settings
func (c *Client) PatchChainsEnvironmentsChainletSettingsAutoscalingSettings(ctx context.Context, chainId string, envName string, body UpdateChainletEnvironmentAutoscalingSettingsRequest) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/chains/%s/environments/%s/chainlet_settings/autoscaling_settings",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchGatewayGroups: Update a group
func (c *Client) PatchGatewayGroups(ctx context.Context, groupId string, body UpdateGroupRequest) (*Group, error) {
	return doJSON[Group](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/gateway/groups/%s",
		pathArgs:    []any{groupId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchLibraryListings: Updates a library listing
func (c *Client) PatchLibraryListings(ctx context.Context, userDefinedListingId string, body UpdateLibraryListingRequest) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchLibraryListingsVersions: Updates a library listing version
func (c *Client) PatchLibraryListingsVersions(ctx context.Context, userDefinedListingId string, versionTag string, body UpdateLibraryListingVersionRequest) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsAutoscalingSettings: Updates a deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsAutoscalingSettings(ctx context.Context, modelId string, deploymentId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/%s/autoscaling_settings",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsDevelopmentAutoscalingSettings: Updates a development deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsDevelopmentAutoscalingSettings(ctx context.Context, modelId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/development/autoscaling_settings",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsProductionAutoscalingSettings: Updates a production deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsProductionAutoscalingSettings(ctx context.Context, modelId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/production/autoscaling_settings",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsEnvironments: Update an environment's settings
func (c *Client) PatchModelsEnvironments(ctx context.Context, modelId string, envName string, body UpdateEnvironmentRequest) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/environments/%s",
		pathArgs:    []any{modelId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchTrainingProjectsJobsInteractiveSessions: Patch an interactive session.
func (c *Client) PatchTrainingProjectsJobsInteractiveSessions(ctx context.Context, trainingProjectId string, trainingJobId string, sessionId string, body PatchInteractiveSessionRequest) (*PatchInteractiveSessionResponse, error) {
	return doJSON[PatchInteractiveSessionResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/interactive_sessions/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId, sessionId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostApiKeys: Creates an API key
func (c *Client) PostApiKeys(ctx context.Context, body CreateAPIKeyRequest) (*APIKey, error) {
	return doJSON[APIKey](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/api_keys",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsDeploymentsDeactivate: Deactivates a chain deployment
func (c *Client) PostChainsDeploymentsDeactivate(ctx context.Context, chainId string, chainDeploymentId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/deployments/%s/deactivate",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironments: Create a chain environment
func (c *Client) PostChainsEnvironments(ctx context.Context, chainId string, body CreateChainEnvironmentRequest) (*ChainEnvironment, error) {
	return doJSON[ChainEnvironment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments",
		pathArgs:    []any{chainId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironmentsChainletSettingsInstanceTypesUpdate: Update a chainlet environment's instance type settings.
func (c *Client) PostChainsEnvironmentsChainletSettingsInstanceTypesUpdate(ctx context.Context, chainId string, envName string, body UpdateChainletEnvironmentInstanceTypeRequest) (*UpdateChainletEnvironmentInstanceTypeResponse, error) {
	return doJSON[UpdateChainletEnvironmentInstanceTypeResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments/%s/chainlet_settings/instance_types/update",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironmentsPromote: Promotes a chain deployment to an environment
func (c *Client) PostChainsEnvironmentsPromote(ctx context.Context, chainId string, envName string, body PromoteToChainEnvironmentRequest) (*ChainDeployment, error) {
	return doJSON[ChainDeployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments/%s/promote",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostGatewayGroups: Create a group
func (c *Client) PostGatewayGroups(ctx context.Context, body CreateGroupRequest) (*Group, error) {
	return doJSON[Group](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/gateway/groups",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostGatewayGroupsApiKeys: Create an API key for a group
func (c *Client) PostGatewayGroupsApiKeys(ctx context.Context, groupId string, body CreateApiKeyForGroupRequest) (*CreateApiKeyForGroupResponse, error) {
	return doJSON[CreateApiKeyForGroupResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/gateway/groups/%s/api_keys",
		pathArgs:    []any{groupId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostGatewayGroupsApiKeysRegister: Register an API key for a group
func (c *Client) PostGatewayGroupsApiKeysRegister(ctx context.Context, groupId string, body RegisterAPIKeyRequest) (*RegisterAPIKeyResponse, error) {
	return doJSON[RegisterAPIKeyResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/gateway/groups/%s/api_keys/register",
		pathArgs:    []any{groupId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLibraryListings: Creates a new library listing
func (c *Client) PostLibraryListings(ctx context.Context, body CreateLibraryListingRequest) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/library_listings",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLibraryListingsVersions: Creates a new library listing version
func (c *Client) PostLibraryListingsVersions(ctx context.Context, userDefinedListingId string, body CreateLibraryListingVersionRequest) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/library_listings/%s/versions",
		pathArgs:    []any{userDefinedListingId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLlmModels: Creates a new BIS LLM deployment
func (c *Client) PostLlmModels(ctx context.Context, body CreateLLMModelRequest) (*LLMModelHandle, error) {
	return doJSON[LLMModelHandle](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/llm_models",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLlmModelsDeployments: Creates a new BIS LLM deployment version
func (c *Client) PostLlmModelsDeployments(ctx context.Context, modelId string, body CreateLLMModelVersionRequest) (*LLMModelHandle, error) {
	return doJSON[LLMModelHandle](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/llm_models/%s/deployments",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsCheckpointsValidate: Validate a Loops checkpoint bt:// URI.
func (c *Client) PostLoopsCheckpointsValidate(ctx context.Context, body ValidateLoopsCheckpointRequest) (*ValidateLoopsCheckpointResponse, error) {
	return doJSON[ValidateLoopsCheckpointResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/checkpoints/validate",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsDeploymentsDeactivate: Deactivate a Loops deployment.
func (c *Client) PostLoopsDeploymentsDeactivate(ctx context.Context, deploymentId string) (*DeactivateLoopsDeploymentResponse, error) {
	return doJSON[DeactivateLoopsDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/deployments/%s/deactivate",
		pathArgs:    []any{deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsDeploymentsMetrics: Get metrics for a Loops trainer deployment.
func (c *Client) PostLoopsDeploymentsMetrics(ctx context.Context, deploymentId string, body GetLoopsDeploymentMetricsRequest) (*GetLoopsDeploymentMetricsResponse, error) {
	return doJSON[GetLoopsDeploymentMetricsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/deployments/%s/metrics",
		pathArgs:    []any{deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsRuns: Create a Loops run.
func (c *Client) PostLoopsRuns(ctx context.Context, body CreateLoopsRunRequest) (*CreateLoopsRunResponse, error) {
	return doJSON[CreateLoopsRunResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/runs",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsSamplers: Create a Loops sampler.
func (c *Client) PostLoopsSamplers(ctx context.Context, body CreateLoopsSamplerRequest) (*CreateLoopsSamplerResponse, error) {
	return doJSON[CreateLoopsSamplerResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/samplers",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLoopsSessions: Create a Loops session.
func (c *Client) PostLoopsSessions(ctx context.Context, body CreateLoopsSessionRequest) (*CreateLoopsSessionResponse, error) {
	return doJSON[CreateLoopsSessionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/loops/sessions",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelApisSnapshots: Create a model weight snapshot
func (c *Client) PostModelApisSnapshots(ctx context.Context, body CreateModelWeightSnapshotRequest) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/model_apis/snapshots",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelApisSnapshotsModelId: Create a model weight snapshot
func (c *Client) PostModelApisSnapshotsModelId(ctx context.Context, modelId string, body CreateModelWeightSnapshotRequest) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/model_apis/snapshots/%s",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModels: Creates a new model from a source
func (c *Client) PostModels(ctx context.Context, body CreateModelRequest) (*CreatedModelDeployment, error) {
	return doJSON[CreatedModelDeployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeployments: Adds a new deployment to a model
func (c *Client) PostModelsDeployments(ctx context.Context, modelId string, body CreateModelDeploymentRequest) (*CreatedModelDeployment, error) {
	return doJSON[CreatedModelDeployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsActivate: Activates a deployment
func (c *Client) PostModelsDeploymentsActivate(ctx context.Context, modelId string, deploymentId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/activate",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDeactivate: Deactivates a deployment
func (c *Client) PostModelsDeploymentsDeactivate(ctx context.Context, modelId string, deploymentId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/deactivate",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentActivate: Activates a development deployment
func (c *Client) PostModelsDeploymentsDevelopmentActivate(ctx context.Context, modelId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/activate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentDeactivate: Deactivates a development deployment
func (c *Client) PostModelsDeploymentsDevelopmentDeactivate(ctx context.Context, modelId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/deactivate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentPromote: Promotes a development deployment to production
func (c *Client) PostModelsDeploymentsDevelopmentPromote(ctx context.Context, modelId string, body PromoteRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/promote",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentRetry: Retries a failed development deployment
func (c *Client) PostModelsDeploymentsDevelopmentRetry(ctx context.Context, modelId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/retry",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsLogs: Gets the logs for a model deployment (deprecated; use GET).
func (c *Client) PostModelsDeploymentsLogs(ctx context.Context, modelId string, deploymentId string, body GetDeploymentLogsRequest) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/logs",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionActivate: Activates a production deployment
func (c *Client) PostModelsDeploymentsProductionActivate(ctx context.Context, modelId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/activate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionDeactivate: Deactivates a production deployment
func (c *Client) PostModelsDeploymentsProductionDeactivate(ctx context.Context, modelId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/deactivate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionRetry: Retries a failed production deployment
func (c *Client) PostModelsDeploymentsProductionRetry(ctx context.Context, modelId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/retry",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsPromote: Promotes a deployment to production
func (c *Client) PostModelsDeploymentsPromote(ctx context.Context, modelId string, deploymentId string, body PromoteRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/promote",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsRetry: Retries a failed deployment
func (c *Client) PostModelsDeploymentsRetry(ctx context.Context, modelId string, deploymentId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/retry",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsSshSign: Sign an SSH certificate for an inference model.
func (c *Client) PostModelsDeploymentsSshSign(ctx context.Context, modelId string, deploymentId string, body SignSSHCertificateRequest) (*SignSSHCertificateResponse, error) {
	return doJSON[SignSSHCertificateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/ssh/sign",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironments: Create an environment
func (c *Client) PostModelsEnvironments(ctx context.Context, modelId string, body CreateEnvironmentRequest) (*Environment, error) {
	return doJSON[Environment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsActivate: Activates a deployment associated with an environment
func (c *Client) PostModelsEnvironmentsActivate(ctx context.Context, modelId string, envName string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/activate",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsCancelPromotion: Cancels a promotion to an environment
func (c *Client) PostModelsEnvironmentsCancelPromotion(ctx context.Context, modelId string, envName string) (*CancelPromotionResponse, error) {
	return doJSON[CancelPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/cancel_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsDeactivate: Deactivates a deployment associated with an environment
func (c *Client) PostModelsEnvironmentsDeactivate(ctx context.Context, modelId string, envName string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/deactivate",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsForceCancelPromotion: Force cancels a rolling promotion
func (c *Client) PostModelsEnvironmentsForceCancelPromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/force_cancel_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsForceRollForwardPromotion: Force rolls forward a rolling promotion
func (c *Client) PostModelsEnvironmentsForceRollForwardPromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/force_roll_forward_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsPausePromotion: Pauses a rolling promotion
func (c *Client) PostModelsEnvironmentsPausePromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/pause_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsPromote: Promotes a deployment to an environment
func (c *Client) PostModelsEnvironmentsPromote(ctx context.Context, modelId string, envName string, body PromoteToEnvironmentRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/promote",
		pathArgs:    []any{modelId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsResumePromotion: Resumes a paused rolling promotion
func (c *Client) PostModelsEnvironmentsResumePromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/resume_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostPrepareModelUpload: Validates a model push payload and issues upload credentials
func (c *Client) PostPrepareModelUpload(ctx context.Context, body PrepareModelUploadRequest) (*PrepareModelUploadResponse, error) {
	return doJSON[PrepareModelUploadResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/prepare_model_upload",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostSecrets: Upserts a secret
func (c *Client) PostSecrets(ctx context.Context, body UpsertSecretRequest) (*Secret, error) {
	return doJSON[Secret](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/secrets",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsApiKeys: Creates a team API key
func (c *Client) PostTeamsApiKeys(ctx context.Context, teamId string, body CreateAPIKeyRequest) (*APIKey, error) {
	return doJSON[APIKey](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/api_keys",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsLlmModels: Creates a new BIS LLM deployment
func (c *Client) PostTeamsLlmModels(ctx context.Context, teamId string, body CreateLLMModelRequest) (*LLMModelHandle, error) {
	return doJSON[LLMModelHandle](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/llm_models",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsModels: Creates a new model from a source
func (c *Client) PostTeamsModels(ctx context.Context, teamId string, body CreateModelRequest) (*CreatedModelDeployment, error) {
	return doJSON[CreatedModelDeployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/models",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsSecrets: Upserts a secret in a team
func (c *Client) PostTeamsSecrets(ctx context.Context, teamId string, body UpsertSecretRequest) (*Secret, error) {
	return doJSON[Secret](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/secrets",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsTrainingProjects: Upsert a training project in a specific team.
func (c *Client) PostTeamsTrainingProjects(ctx context.Context, teamId string, body UpsertTrainingProjectRequest) (*UpsertTrainingProjectResponse, error) {
	return doJSON[UpsertTrainingProjectResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/training_projects",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainerSessions: Create a trainer session.
func (c *Client) PostTrainerSessions(ctx context.Context, body CreateTrainerSessionRequest) (*CreateTrainerSessionResponse, error) {
	return doJSON[CreateTrainerSessionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/trainer_sessions",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainerSessionsSamplers: Create a sampling server.
func (c *Client) PostTrainerSessionsSamplers(ctx context.Context, sessionId string, body CreateSamplingServerRequest) (*CreateSamplingServerResponse, error) {
	return doJSON[CreateSamplingServerResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/trainer_sessions/%s/samplers",
		pathArgs:    []any{sessionId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainerSessionsTrainers: Create a trainer server.
func (c *Client) PostTrainerSessionsTrainers(ctx context.Context, sessionId string, body CreateTrainerServerRequest) (*CreateTrainerServerResponse, error) {
	return doJSON[CreateTrainerServerResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/trainer_sessions/%s/trainers",
		pathArgs:    []any{sessionId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainersCheckpointsSearch: Look up trainer checkpoint info by bt:// URI.
func (c *Client) PostTrainersCheckpointsSearch(ctx context.Context, body CheckpointSearchRequest) (*CheckpointSearchResponse, error) {
	return doJSON[CheckpointSearchResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/trainers/checkpoints/search",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainersSearch: Search trainers.
func (c *Client) PostTrainersSearch(ctx context.Context, body SearchTrainersRequest) (*SearchTrainersResponse, error) {
	return doJSON[SearchTrainersResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/trainers/search",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingJobsSearch: Search training jobs.
func (c *Client) PostTrainingJobsSearch(ctx context.Context, body SearchTrainingJobsRequest) (*SearchTrainingJobsResponse, error) {
	return doJSON[SearchTrainingJobsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_jobs/search",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjects: Upsert a training project.
func (c *Client) PostTrainingProjects(ctx context.Context, body UpsertTrainingProjectRequest) (*UpsertTrainingProjectResponse, error) {
	return doJSON[UpsertTrainingProjectResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobs: Create a training job.
func (c *Client) PostTrainingProjectsJobs(ctx context.Context, trainingProjectId string, body CreateTrainingJobRequest) (*CreateTrainingJobResponse, error) {
	return doJSON[CreateTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs",
		pathArgs:    []any{trainingProjectId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsLogs: Get the logs for a training job (deprecated; use GET).
func (c *Client) PostTrainingProjectsJobsLogs(ctx context.Context, trainingProjectId string, trainingJobId string, body GetTrainingJobLogsRequest) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/logs",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsMetrics: Get the metrics for a training job (deprecated; use GET).
func (c *Client) PostTrainingProjectsJobsMetrics(ctx context.Context, trainingProjectId string, trainingJobId string, body GetTrainingJobMetricsRequest) (*GetTrainingJobMetricsResponse, error) {
	return doJSON[GetTrainingJobMetricsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/metrics",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsRecreate: Recreate a training job
func (c *Client) PostTrainingProjectsJobsRecreate(ctx context.Context, trainingProjectId string, trainingJobId string) (*RecreateTrainingJobResponse, error) {
	return doJSON[RecreateTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/recreate",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsSshSign: Sign an SSH certificate for a training job.
func (c *Client) PostTrainingProjectsJobsSshSign(ctx context.Context, trainingProjectId string, trainingJobId string, body SignSSHCertificateRequest) (*SignSSHCertificateResponse, error) {
	return doJSON[SignSSHCertificateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/ssh/sign",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsStop: Stop a training job.
func (c *Client) PostTrainingProjectsJobsStop(ctx context.Context, trainingProjectId string, trainingJobId string, body StopTrainingJobRequest) (*StopTrainingJobResponse, error) {
	return doJSON[StopTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/stop",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// errorType identifies a typed error schema for status-code-based dispatch.
type errorType int

const (
	errorTypeNone errorType = iota
)

type apiRequest struct {
	method      string
	pathFmt     string
	pathArgs    []any
	queryParams any
	body        any
	successCode int
	// errorCodes maps HTTP status codes to a typed error schema. Status codes
	// not in this map (or decode failures) fall back to [*ResponseError].
	errorCodes map[int]errorType
}

func (c *Client) do(ctx context.Context, r apiRequest) (*http.Response, error) {
	for i, p := range r.pathArgs {
		r.pathArgs[i] = url.PathEscape(fmt.Sprint(p))
	}
	path := fmt.Sprintf(r.pathFmt, r.pathArgs...)
	if r.queryParams != nil {
		if q := encodeQuery(r.queryParams); len(q) > 0 {
			path += "?" + q.Encode()
		}
	}
	var bodyReader io.Reader
	if r.body != nil {
		b, err := json.Marshal(r.body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, r.method, c.BaseURL+path, bodyReader)
	if err != nil {
		return nil, err
	}
	if r.body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for key, vals := range c.Headers {
		for _, val := range vals {
			req.Header.Add(key, val)
		}
	}
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != r.successCode {
		defer resp.Body.Close()
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if et, ok := r.errorCodes[resp.StatusCode]; ok {
			if typedErr := decodeErrorType(et, resp.StatusCode, body); typedErr != nil {
				return nil, typedErr
			}
		}
		return nil, &ResponseError{StatusCode: resp.StatusCode, Body: string(body)}
	}
	return resp, nil
}

func decodeErrorType(et errorType, statusCode int, body []byte) error {
	switch et {
	}
	return nil
}

// encodeQuery walks a Params struct emitted by oapi-codegen and renders its
// fields as url.Values using the "form" struct tag. Pointer fields that are
// nil are skipped. time.Time values are rendered as RFC 3339.
func encodeQuery(p any) url.Values {
	q := url.Values{}
	v := reflect.ValueOf(p)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return q
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return q
	}
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		tag := t.Field(i).Tag.Get("form")
		if tag == "" || tag == "-" {
			continue
		}
		name := strings.SplitN(tag, ",", 2)[0]
		if name == "" {
			continue
		}
		fv := v.Field(i)
		if fv.Kind() == reflect.Ptr {
			if fv.IsNil() {
				continue
			}
			fv = fv.Elem()
		}
		switch x := fv.Interface().(type) {
		case time.Time:
			q.Set(name, x.Format(time.RFC3339))
		case []string:
			for _, s := range x {
				q.Add(name, s)
			}
		default:
			switch fv.Kind() {
			case reflect.String:
				q.Set(name, fv.String())
			case reflect.Bool:
				q.Set(name, strconv.FormatBool(fv.Bool()))
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				q.Set(name, strconv.FormatInt(fv.Int(), 10))
			case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
				q.Set(name, strconv.FormatUint(fv.Uint(), 10))
			case reflect.Float32, reflect.Float64:
				q.Set(name, strconv.FormatFloat(fv.Float(), 'g', -1, 64))
			default:
				q.Set(name, fmt.Sprint(fv.Interface()))
			}
		}
	}
	return q
}

func doJSON[T any](c *Client, ctx context.Context, r apiRequest) (*T, error) {
	resp, err := c.do(ctx, r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		return nil, fmt.Errorf("unexpected content type %q, expected application/json", ct)
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var result T
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
