// Code generated by apigen/clientgen. DO NOT EDIT.

// Package managementapi is a generated client for the Baseten managementapi.
//
// Types and methods in this package are generated from the OpenAPI
// specification and are NOT covered by any stability or compatibility
// guarantees. They may change without notice between versions.
package managementapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Client is a generated HTTP client for the managementapi API.
//
// On HTTP failure, methods return [*ResponseError] unless documented
// otherwise on the method.
type Client struct {
	BaseURL    string
	HTTPClient interface {
		Do(*http.Request) (*http.Response, error)
	}
	// Headers are added to every request.
	Headers http.Header
}

// ResponseError represents a non-success HTTP response whose body could not
// be decoded into a typed error.
type ResponseError struct {
	StatusCode int
	Body       string
}

func (e *ResponseError) Error() string {
	return fmt.Sprintf("baseten API error (HTTP %d): %s", e.StatusCode, e.Body)
}

// DeleteApiKeys: Deletes an API key by prefix
func (c *Client) DeleteApiKeys(ctx context.Context, apiKeyPrefix string) (*APIKeyTombstone, error) {
	return doJSON[APIKeyTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/api_keys/%s",
		pathArgs:    []any{apiKeyPrefix},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteChains: Deletes a chain by ID
func (c *Client) DeleteChains(ctx context.Context, chainId string) (*ChainTombstone, error) {
	return doJSON[ChainTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/chains/%s",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteChainsDeployments: Deletes a chain deployment by ID
func (c *Client) DeleteChainsDeployments(ctx context.Context, chainId string, chainDeploymentId string) (*ChainDeploymentTombstone, error) {
	return doJSON[ChainDeploymentTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/chains/%s/deployments/%s",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteLibraryListings: Deletes a library listing
func (c *Client) DeleteLibraryListings(ctx context.Context, userDefinedListingId string) (*LibraryListingTombstone, error) {
	return doJSON[LibraryListingTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteLibraryListingsVersions: Deletes a library listing version
func (c *Client) DeleteLibraryListingsVersions(ctx context.Context, userDefinedListingId string, versionTag string) (*LibraryListingVersionTombstone, error) {
	return doJSON[LibraryListingVersionTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModels: Deletes a model by ID
func (c *Client) DeleteModels(ctx context.Context, modelId string) (*ModelTombstone, error) {
	return doJSON[ModelTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModelsDeployments: Deletes a model's deployment by ID
func (c *Client) DeleteModelsDeployments(ctx context.Context, modelId string, deploymentId string) (*DeploymentTombstone, error) {
	return doJSON[DeploymentTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s/deployments/%s",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteModelsDeploymentsReplicas: Terminates a replica in a deployment
func (c *Client) DeleteModelsDeploymentsReplicas(ctx context.Context, modelId string, deploymentId string, replicaId string) (*TerminateReplicaResponse, error) {
	return doJSON[TerminateReplicaResponse](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/models/%s/deployments/%s/replicas/%s",
		pathArgs:    []any{modelId, deploymentId, replicaId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteTrainingProjects: Delete a training project.
func (c *Client) DeleteTrainingProjects(ctx context.Context, trainingProjectId string) (*TrainingProjectTombstone, error) {
	return doJSON[TrainingProjectTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/training_projects/%s",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// DeleteTrainingProjectsJobs: Delete a training job.
func (c *Client) DeleteTrainingProjectsJobs(ctx context.Context, trainingProjectId string, trainingJobId string) (*TrainingJobTombstone, error) {
	return doJSON[TrainingJobTombstone](c, ctx, apiRequest{
		method:      "DELETE",
		pathFmt:     "/v1/training_projects/%s/jobs/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetApiKeys: Lists the user's API keys
func (c *Client) GetApiKeys(ctx context.Context) (*APIKeys, error) {
	return doJSON[APIKeys](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/api_keys",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBillingUsageSummary: Gets billing usage summary for a date range
func (c *Client) GetBillingUsageSummary(ctx context.Context) (*UsageSummary, error) {
	return doJSON[UsageSummary](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/billing/usage_summary",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBlobsCredentialsModel: Get blob credentials for models.
func (c *Client) GetBlobsCredentialsModel(ctx context.Context) (*GetBlobCredentialsResponse, error) {
	return doJSON[GetBlobCredentialsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/blobs/credentials/model",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetBlobsCredentialsTrain: Get blob credentials for training.
func (c *Client) GetBlobsCredentialsTrain(ctx context.Context) (*GetBlobCredentialsResponse, error) {
	return doJSON[GetBlobCredentialsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/blobs/credentials/train",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChains: Gets all chains
func (c *Client) GetChains(ctx context.Context) (*Chains, error) {
	return doJSON[Chains](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsChainId: Gets a chain by ID
func (c *Client) GetChainsChainId(ctx context.Context, chainId string) (*Chain, error) {
	return doJSON[Chain](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsDeployments: Gets all chain deployments
func (c *Client) GetChainsDeployments(ctx context.Context, chainId string) (*ChainDeployments, error) {
	return doJSON[ChainDeployments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/deployments",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsDeploymentsChainDeploymentId: Gets a chain deployment by ID
func (c *Client) GetChainsDeploymentsChainDeploymentId(ctx context.Context, chainId string, chainDeploymentId string) (*ChainDeployment, error) {
	return doJSON[ChainDeployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/deployments/%s",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsEnvironments: Get all chain environments
func (c *Client) GetChainsEnvironments(ctx context.Context, chainId string) (*Environments, error) {
	return doJSON[Environments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/environments",
		pathArgs:    []any{chainId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetChainsEnvironmentsEnvName: Get a chain environment's details
func (c *Client) GetChainsEnvironmentsEnvName(ctx context.Context, chainId string, envName string) (*ChainEnvironment, error) {
	return doJSON[ChainEnvironment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/chains/%s/environments/%s",
		pathArgs:    []any{chainId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetInstanceTypePrices: Gets prices for available instance types.
func (c *Client) GetInstanceTypePrices(ctx context.Context) (*InstanceTypePrices, error) {
	return doJSON[InstanceTypePrices](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/instance_type_prices",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetInstanceTypes: Gets all available instance types
func (c *Client) GetInstanceTypes(ctx context.Context) (*InstanceTypes, error) {
	return doJSON[InstanceTypes](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/instance_types",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListings: Gets all library listings
func (c *Client) GetLibraryListings(ctx context.Context) (*LibraryListings, error) {
	return doJSON[LibraryListings](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsUserDefinedListingId: Gets a library listing
func (c *Client) GetLibraryListingsUserDefinedListingId(ctx context.Context, userDefinedListingId string) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsVersions: Gets all versions for a library listing
func (c *Client) GetLibraryListingsVersions(ctx context.Context, userDefinedListingId string) (*LibraryListingVersions, error) {
	return doJSON[LibraryListingVersions](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s/versions",
		pathArgs:    []any{userDefinedListingId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetLibraryListingsVersionsVersionTag: Gets a library listing version
func (c *Client) GetLibraryListingsVersionsVersionTag(ctx context.Context, userDefinedListingId string, versionTag string) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelApisSnapshots: Get the latest model weight snapshot
func (c *Client) GetModelApisSnapshots(ctx context.Context) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/model_apis/snapshots",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelApisSnapshotsModelId: Get the latest model weight snapshot
func (c *Client) GetModelApisSnapshotsModelId(ctx context.Context, modelId string) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/model_apis/snapshots/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModels: Gets all models
func (c *Client) GetModels(ctx context.Context) (*Models, error) {
	return doJSON[Models](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeployments: Gets all deployments of a model
func (c *Client) GetModelsDeployments(ctx context.Context, modelId string) (*Deployments, error) {
	return doJSON[Deployments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsDeploymentId: Gets a model's deployment by ID
func (c *Client) GetModelsDeploymentsDeploymentId(ctx context.Context, modelId string, deploymentId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/%s",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsDevelopment: Gets a model's development deployment
func (c *Client) GetModelsDeploymentsDevelopment(ctx context.Context, modelId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/development",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsDeploymentsProduction: Gets a model's production deployment
func (c *Client) GetModelsDeploymentsProduction(ctx context.Context, modelId string) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/deployments/production",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsEnvironments: Get all environments
func (c *Client) GetModelsEnvironments(ctx context.Context, modelId string) (*Environments, error) {
	return doJSON[Environments](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/environments",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsEnvironmentsEnvName: Get an environment's details
func (c *Client) GetModelsEnvironmentsEnvName(ctx context.Context, modelId string, envName string) (*Environment, error) {
	return doJSON[Environment](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s/environments/%s",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetModelsModelId: Gets a model by ID
func (c *Client) GetModelsModelId(ctx context.Context, modelId string) (*Model, error) {
	return doJSON[Model](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/models/%s",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetSecrets: Gets all secrets
func (c *Client) GetSecrets(ctx context.Context) (*Secrets, error) {
	return doJSON[Secrets](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/secrets",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTeams: Lists all teams
func (c *Client) GetTeams(ctx context.Context) (*Teams, error) {
	return doJSON[Teams](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/teams",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTeamsSecrets: Gets all secrets for a team
func (c *Client) GetTeamsSecrets(ctx context.Context, teamId string) (*Secrets, error) {
	return doJSON[Secrets](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/teams/%s/secrets",
		pathArgs:    []any{teamId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjects: List training projects.
func (c *Client) GetTrainingProjects(ctx context.Context) (*ListTrainingProjectsResponse, error) {
	return doJSON[ListTrainingProjectsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects",
		pathArgs:    nil,
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsCacheSummary: Get training project cache summary.
func (c *Client) GetTrainingProjectsCacheSummary(ctx context.Context, trainingProjectId string) (*GetCacheSummaryResponse, error) {
	return doJSON[GetCacheSummaryResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/cache/summary",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobs: List training jobs.
func (c *Client) GetTrainingProjectsJobs(ctx context.Context, trainingProjectId string) (*ListTrainingJobsResponse, error) {
	return doJSON[ListTrainingJobsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsAuthCodes: Get auth codes for a training job.
func (c *Client) GetTrainingProjectsJobsAuthCodes(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetAuthCodesResponse, error) {
	return doJSON[GetAuthCodesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/auth_codes",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsCheckpointFiles: Get training job checkpoint files.
func (c *Client) GetTrainingProjectsJobsCheckpointFiles(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetTrainingJobCheckpointFilesResponse, error) {
	return doJSON[GetTrainingJobCheckpointFilesResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/checkpoint_files",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsCheckpoints: Get training job checkpoints.
func (c *Client) GetTrainingProjectsJobsCheckpoints(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetTrainingJobCheckpointsResponse, error) {
	return doJSON[GetTrainingJobCheckpointsResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/checkpoints",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsDownload: Get the uploaded training job as a S3 Artifact
func (c *Client) GetTrainingProjectsJobsDownload(ctx context.Context, trainingProjectId string, trainingJobId string) (*DownloadTrainingJobResponse, error) {
	return doJSON[DownloadTrainingJobResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/download",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsJobsTrainingJobId: Get a training job.
func (c *Client) GetTrainingProjectsJobsTrainingJobId(ctx context.Context, trainingProjectId string, trainingJobId string) (*GetTrainingJobResponse, error) {
	return doJSON[GetTrainingJobResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s/jobs/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// GetTrainingProjectsTrainingProjectId: Get a training project.
func (c *Client) GetTrainingProjectsTrainingProjectId(ctx context.Context, trainingProjectId string) (*GetTrainingProjectResponse, error) {
	return doJSON[GetTrainingProjectResponse](c, ctx, apiRequest{
		method:      "GET",
		pathFmt:     "/v1/training_projects/%s",
		pathArgs:    []any{trainingProjectId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchChainsEnvironments: Update a chain environment's settings
func (c *Client) PatchChainsEnvironments(ctx context.Context, chainId string, envName string, body UpdateChainEnvironmentRequest) (*UpdateChainEnvironmentResponse, error) {
	return doJSON[UpdateChainEnvironmentResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/chains/%s/environments/%s",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchChainsEnvironmentsChainletSettingsAutoscalingSettings: Update a chainlet environment's autoscaling settings
func (c *Client) PatchChainsEnvironmentsChainletSettingsAutoscalingSettings(ctx context.Context, chainId string, envName string, body UpdateChainletEnvironmentAutoscalingSettingsRequest) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/chains/%s/environments/%s/chainlet_settings/autoscaling_settings",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchLibraryListings: Updates a library listing
func (c *Client) PatchLibraryListings(ctx context.Context, userDefinedListingId string, body UpdateLibraryListingRequest) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/library_listings/%s",
		pathArgs:    []any{userDefinedListingId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchLibraryListingsVersions: Updates a library listing version
func (c *Client) PatchLibraryListingsVersions(ctx context.Context, userDefinedListingId string, versionTag string, body UpdateLibraryListingVersionRequest) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/library_listings/%s/versions/%s",
		pathArgs:    []any{userDefinedListingId, versionTag},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsAutoscalingSettings: Updates a deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsAutoscalingSettings(ctx context.Context, modelId string, deploymentId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/%s/autoscaling_settings",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsDevelopmentAutoscalingSettings: Updates a development deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsDevelopmentAutoscalingSettings(ctx context.Context, modelId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/development/autoscaling_settings",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsDeploymentsProductionAutoscalingSettings: Updates a production deployment's autoscaling settings
func (c *Client) PatchModelsDeploymentsProductionAutoscalingSettings(ctx context.Context, modelId string, body UpdateAutoscalingSettings) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/deployments/production/autoscaling_settings",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchModelsEnvironments: Update an environment's settings
func (c *Client) PatchModelsEnvironments(ctx context.Context, modelId string, envName string, body UpdateEnvironmentRequest) (*UpdateAutoscalingSettingsResponse, error) {
	return doJSON[UpdateAutoscalingSettingsResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/models/%s/environments/%s",
		pathArgs:    []any{modelId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PatchTrainingProjectsJobsInteractiveSessions: Patch an interactive session.
func (c *Client) PatchTrainingProjectsJobsInteractiveSessions(ctx context.Context, trainingProjectId string, trainingJobId string, sessionId string, body PatchInteractiveSessionRequest) (*PatchInteractiveSessionResponse, error) {
	return doJSON[PatchInteractiveSessionResponse](c, ctx, apiRequest{
		method:      "PATCH",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/interactive_sessions/%s",
		pathArgs:    []any{trainingProjectId, trainingJobId, sessionId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostApiKeys: Creates an API key
func (c *Client) PostApiKeys(ctx context.Context, body CreateAPIKeyRequest) (*APIKey, error) {
	return doJSON[APIKey](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/api_keys",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsDeploymentsDeactivate: Deactivates a chain deployment
func (c *Client) PostChainsDeploymentsDeactivate(ctx context.Context, chainId string, chainDeploymentId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/deployments/%s/deactivate",
		pathArgs:    []any{chainId, chainDeploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironments: Create a chain environment
func (c *Client) PostChainsEnvironments(ctx context.Context, chainId string, body CreateChainEnvironmentRequest) (*ChainEnvironment, error) {
	return doJSON[ChainEnvironment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments",
		pathArgs:    []any{chainId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironmentsChainletSettingsInstanceTypesUpdate: Update a chainlet environment's instance type settings.
func (c *Client) PostChainsEnvironmentsChainletSettingsInstanceTypesUpdate(ctx context.Context, chainId string, envName string, body UpdateChainletEnvironmentInstanceTypeRequest) (*UpdateChainletEnvironmentInstanceTypeResponse, error) {
	return doJSON[UpdateChainletEnvironmentInstanceTypeResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments/%s/chainlet_settings/instance_types/update",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostChainsEnvironmentsPromote: Promotes a chain deployment to an environment
func (c *Client) PostChainsEnvironmentsPromote(ctx context.Context, chainId string, envName string, body PromoteToChainEnvironmentRequest) (*ChainDeployment, error) {
	return doJSON[ChainDeployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/chains/%s/environments/%s/promote",
		pathArgs:    []any{chainId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLibraryListings: Creates a new library listing
func (c *Client) PostLibraryListings(ctx context.Context, body CreateLibraryListingRequest) (*LibraryListing, error) {
	return doJSON[LibraryListing](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/library_listings",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLibraryListingsVersions: Creates a new library listing version
func (c *Client) PostLibraryListingsVersions(ctx context.Context, userDefinedListingId string, body CreateLibraryListingVersionRequest) (*LibraryListingVersion, error) {
	return doJSON[LibraryListingVersion](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/library_listings/%s/versions",
		pathArgs:    []any{userDefinedListingId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLlmModels: Creates a new BIS LLM deployment
func (c *Client) PostLlmModels(ctx context.Context, body CreateLLMModelRequest) (*LLMModel, error) {
	return doJSON[LLMModel](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/llm_models",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostLlmModelsDeployments: Creates a new BIS LLM deployment version
func (c *Client) PostLlmModelsDeployments(ctx context.Context, modelId string, body CreateLLMModelVersionRequest) (*LLMModelVersion, error) {
	return doJSON[LLMModelVersion](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/llm_models/%s/deployments",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelApisSnapshots: Create a model weight snapshot
func (c *Client) PostModelApisSnapshots(ctx context.Context, body CreateModelWeightSnapshotRequest) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/model_apis/snapshots",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelApisSnapshotsModelId: Create a model weight snapshot
func (c *Client) PostModelApisSnapshotsModelId(ctx context.Context, modelId string, body CreateModelWeightSnapshotRequest) (*ModelWeightSnapshot, error) {
	return doJSON[ModelWeightSnapshot](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/model_apis/snapshots/%s",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsActivate: Activates a deployment
func (c *Client) PostModelsDeploymentsActivate(ctx context.Context, modelId string, deploymentId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/activate",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDeactivate: Deactivates a deployment
func (c *Client) PostModelsDeploymentsDeactivate(ctx context.Context, modelId string, deploymentId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/deactivate",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentActivate: Activates a development deployment
func (c *Client) PostModelsDeploymentsDevelopmentActivate(ctx context.Context, modelId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/activate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentDeactivate: Deactivates a development deployment
func (c *Client) PostModelsDeploymentsDevelopmentDeactivate(ctx context.Context, modelId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/deactivate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentPromote: Promotes a development deployment to production
func (c *Client) PostModelsDeploymentsDevelopmentPromote(ctx context.Context, modelId string, body PromoteRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/promote",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsDevelopmentRetry: Retries a failed development deployment
func (c *Client) PostModelsDeploymentsDevelopmentRetry(ctx context.Context, modelId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/development/retry",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsLogs: Gets the logs for a model deployment.
func (c *Client) PostModelsDeploymentsLogs(ctx context.Context, modelId string, deploymentId string, body GetDeploymentLogsRequest) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/logs",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionActivate: Activates a production deployment
func (c *Client) PostModelsDeploymentsProductionActivate(ctx context.Context, modelId string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/activate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionDeactivate: Deactivates a production deployment
func (c *Client) PostModelsDeploymentsProductionDeactivate(ctx context.Context, modelId string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/deactivate",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsProductionRetry: Retries a failed production deployment
func (c *Client) PostModelsDeploymentsProductionRetry(ctx context.Context, modelId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/production/retry",
		pathArgs:    []any{modelId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsPromote: Promotes a deployment to production
func (c *Client) PostModelsDeploymentsPromote(ctx context.Context, modelId string, deploymentId string, body PromoteRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/promote",
		pathArgs:    []any{modelId, deploymentId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsDeploymentsRetry: Retries a failed deployment
func (c *Client) PostModelsDeploymentsRetry(ctx context.Context, modelId string, deploymentId string) (*RetryDeploymentResponse, error) {
	return doJSON[RetryDeploymentResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/deployments/%s/retry",
		pathArgs:    []any{modelId, deploymentId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironments: Create an environment
func (c *Client) PostModelsEnvironments(ctx context.Context, modelId string, body CreateEnvironmentRequest) (*Environment, error) {
	return doJSON[Environment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments",
		pathArgs:    []any{modelId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsActivate: Activates a deployment associated with an environment
func (c *Client) PostModelsEnvironmentsActivate(ctx context.Context, modelId string, envName string) (*ActivateResponse, error) {
	return doJSON[ActivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/activate",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsCancelPromotion: Cancels a promotion to an environment
func (c *Client) PostModelsEnvironmentsCancelPromotion(ctx context.Context, modelId string, envName string) (*CancelPromotionResponse, error) {
	return doJSON[CancelPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/cancel_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsDeactivate: Deactivates a deployment associated with an environment
func (c *Client) PostModelsEnvironmentsDeactivate(ctx context.Context, modelId string, envName string) (*DeactivateResponse, error) {
	return doJSON[DeactivateResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/deactivate",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsForceCancelPromotion: Force cancels a rolling promotion
func (c *Client) PostModelsEnvironmentsForceCancelPromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/force_cancel_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsForceRollForwardPromotion: Force rolls forward a rolling promotion
func (c *Client) PostModelsEnvironmentsForceRollForwardPromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/force_roll_forward_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsPausePromotion: Pauses a rolling promotion
func (c *Client) PostModelsEnvironmentsPausePromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/pause_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsPromote: Promotes a deployment to an environment
func (c *Client) PostModelsEnvironmentsPromote(ctx context.Context, modelId string, envName string, body PromoteToEnvironmentRequest) (*Deployment, error) {
	return doJSON[Deployment](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/promote",
		pathArgs:    []any{modelId, envName},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostModelsEnvironmentsResumePromotion: Resumes a paused rolling promotion
func (c *Client) PostModelsEnvironmentsResumePromotion(ctx context.Context, modelId string, envName string) (*SignalPromotionResponse, error) {
	return doJSON[SignalPromotionResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/models/%s/environments/%s/resume_promotion",
		pathArgs:    []any{modelId, envName},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostSecrets: Upserts a secret
func (c *Client) PostSecrets(ctx context.Context, body UpsertSecretRequest) (*Secret, error) {
	return doJSON[Secret](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/secrets",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsApiKeys: Creates a team API key
func (c *Client) PostTeamsApiKeys(ctx context.Context, teamId string, body CreateAPIKeyRequest) (*APIKey, error) {
	return doJSON[APIKey](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/api_keys",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsSecrets: Upserts a secret in a team
func (c *Client) PostTeamsSecrets(ctx context.Context, teamId string, body UpsertSecretRequest) (*Secret, error) {
	return doJSON[Secret](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/secrets",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTeamsTrainingProjects: Upsert a training project in a specific team.
func (c *Client) PostTeamsTrainingProjects(ctx context.Context, teamId string, body UpsertTrainingProjectRequest) (*UpsertTrainingProjectResponse, error) {
	return doJSON[UpsertTrainingProjectResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/teams/%s/training_projects",
		pathArgs:    []any{teamId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingJobsSearch: Search training jobs.
func (c *Client) PostTrainingJobsSearch(ctx context.Context, body SearchTrainingJobsRequest) (*SearchTrainingJobsResponse, error) {
	return doJSON[SearchTrainingJobsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_jobs/search",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjects: Upsert a training project.
func (c *Client) PostTrainingProjects(ctx context.Context, body UpsertTrainingProjectRequest) (*UpsertTrainingProjectResponse, error) {
	return doJSON[UpsertTrainingProjectResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects",
		pathArgs:    nil,
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobs: Create a training job.
func (c *Client) PostTrainingProjectsJobs(ctx context.Context, trainingProjectId string, body CreateTrainingJobRequest) (*CreateTrainingJobResponse, error) {
	return doJSON[CreateTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs",
		pathArgs:    []any{trainingProjectId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsLogs: Get the logs for a training job.
func (c *Client) PostTrainingProjectsJobsLogs(ctx context.Context, trainingProjectId string, trainingJobId string, body GetTrainingJobLogsRequest) (*GetLogsResponse, error) {
	return doJSON[GetLogsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/logs",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsMetrics: Get the metrics for a training job.
func (c *Client) PostTrainingProjectsJobsMetrics(ctx context.Context, trainingProjectId string, trainingJobId string, body GetTrainingJobMetricsRequest) (*GetTrainingJobMetricsResponse, error) {
	return doJSON[GetTrainingJobMetricsResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/metrics",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsRecreate: Recreate a training job
func (c *Client) PostTrainingProjectsJobsRecreate(ctx context.Context, trainingProjectId string, trainingJobId string) (*RecreateTrainingJobResponse, error) {
	return doJSON[RecreateTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/recreate",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        nil,
		successCode: 200,
		errorCodes:  nil,
	})
}

// PostTrainingProjectsJobsStop: Stop a training job.
func (c *Client) PostTrainingProjectsJobsStop(ctx context.Context, trainingProjectId string, trainingJobId string, body StopTrainingJobRequest) (*StopTrainingJobResponse, error) {
	return doJSON[StopTrainingJobResponse](c, ctx, apiRequest{
		method:      "POST",
		pathFmt:     "/v1/training_projects/%s/jobs/%s/stop",
		pathArgs:    []any{trainingProjectId, trainingJobId},
		body:        body,
		successCode: 200,
		errorCodes:  nil,
	})
}

// errorType identifies a typed error schema for status-code-based dispatch.
type errorType int

const (
	errorTypeNone errorType = iota
)

type apiRequest struct {
	method      string
	pathFmt     string
	pathArgs    []any
	body        any
	successCode int
	// errorCodes maps HTTP status codes to a typed error schema. Status codes
	// not in this map (or decode failures) fall back to [*ResponseError].
	errorCodes map[int]errorType
}

func (c *Client) do(ctx context.Context, r apiRequest) (*http.Response, error) {
	for i, p := range r.pathArgs {
		r.pathArgs[i] = url.PathEscape(fmt.Sprint(p))
	}
	path := fmt.Sprintf(r.pathFmt, r.pathArgs...)
	var bodyReader io.Reader
	if r.body != nil {
		b, err := json.Marshal(r.body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, r.method, c.BaseURL+path, bodyReader)
	if err != nil {
		return nil, err
	}
	if r.body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	for key, vals := range c.Headers {
		for _, val := range vals {
			req.Header.Add(key, val)
		}
	}
	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != r.successCode {
		defer resp.Body.Close()
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		if et, ok := r.errorCodes[resp.StatusCode]; ok {
			if typedErr := decodeErrorType(et, resp.StatusCode, body); typedErr != nil {
				return nil, typedErr
			}
		}
		return nil, &ResponseError{StatusCode: resp.StatusCode, Body: string(body)}
	}
	return resp, nil
}

func decodeErrorType(et errorType, statusCode int, body []byte) error {
	switch et {
	}
	return nil
}

func doJSON[T any](c *Client, ctx context.Context, r apiRequest) (*T, error) {
	resp, err := c.do(ctx, r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if ct := resp.Header.Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		return nil, fmt.Errorf("unexpected content type %q, expected application/json", ct)
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var result T
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
