// Code generated by github.com/atombender/go-jsonschema. DO NOT EDIT.

// Package modelconfig contains generated types for Baseten model
// configuration (also known as Truss config).
//
// Types in this package are generated from the Truss config JSON Schema and
// are NOT covered by any stability or compatibility guarantees. They may
// change without notice between versions.
package modelconfig

type AcceleratorSpec string

// Additional autoscaling configuration for in-flight token metrics.
type AdditionalAutoscalingConfig struct {
	// List of metric targets for autoscaling.
	Metrics []AutoscalingMetric `json:"metrics" yaml:"metrics"`
}

type Arguments map[string]interface{}

type AutoscalingMetric struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name"`

	// Target corresponds to the JSON schema field "target".
	Target float64 `json:"target" yaml:"target"`
}

// Configuration options for BIS LLM deployments.
type BISLLM struct {
	// Additional autoscaling configuration
	AdditionalAutoscalingConfig *AdditionalAutoscalingConfig `json:"additional_autoscaling_config,omitempty,omitzero" yaml:"additional_autoscaling_config,omitempty"`

	// Configuration options for BIS LLM deployments.
	Config Config `json:"config,omitempty,omitzero" yaml:"config,omitempty"`

	// The version of the BIS LLM deployment stack.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Use base_image to deploy a custom Docker image.
type BaseImage struct {
	// Authentication configuration for a private Docker registry.
	DockerAuth *DockerAuthSettings `json:"docker_auth,omitempty,omitzero" yaml:"docker_auth,omitempty"`

	// The path to the Docker image.
	Image string `json:"image,omitempty,omitzero" yaml:"image,omitempty"`

	// A path to the Python executable on the image.
	PythonExecutablePath string `json:"python_executable_path,omitempty,omitzero" yaml:"python_executable_path,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Build-time configuration, including secret access during Docker builds.
type Build struct {
	// Arguments corresponds to the JSON schema field "arguments".
	Arguments Arguments `json:"arguments,omitempty,omitzero" yaml:"arguments,omitempty"`

	// ModelServer corresponds to the JSON schema field "model_server".
	ModelServer ModelServer `json:"model_server,omitempty,omitzero" yaml:"model_server,omitempty"`

	// NoCache corresponds to the JSON schema field "no_cache".
	NoCache bool `json:"no_cache,omitempty,omitzero" yaml:"no_cache,omitempty"`

	// Grants access to secrets during the build. Provide a mapping between a secret
	// and a path on the image.
	SecretToPathMapping SecretToPathMapping `json:"secret_to_path_mapping,omitempty,omitzero" yaml:"secret_to_path_mapping,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CacheInternal []ModelRepoCacheInternal

type CheckpointList struct {
	// ArtifactReferences corresponds to the JSON schema field "artifact_references".
	ArtifactReferences []TrainingArtifactReference `json:"artifact_references,omitempty,omitzero" yaml:"artifact_references,omitempty"`

	// The folder to download the checkpoints to.
	DownloadFolder string `json:"download_folder,omitempty,omitzero" yaml:"download_folder,omitempty"`

	// Loops checkpoint IDs to deploy. Mutually exclusive with artifact_references.
	LoopsCheckpointIds []string `json:"loops_checkpoint_ids,omitempty,omitzero" yaml:"loops_checkpoint_ids,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CheckpointRepository struct {
	// Repo corresponds to the JSON schema field "repo".
	Repo string `json:"repo" yaml:"repo"`

	// Revision corresponds to the JSON schema field "revision".
	Revision *string `json:"revision,omitempty,omitzero" yaml:"revision,omitempty"`

	// RuntimeSecretName corresponds to the JSON schema field "runtime_secret_name".
	RuntimeSecretName string `json:"runtime_secret_name,omitempty,omitzero" yaml:"runtime_secret_name,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source CheckpointSource `json:"source" yaml:"source"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CheckpointSource string

const CheckpointSourceAZURE CheckpointSource = "AZURE"
const CheckpointSourceBASETENTRAINING CheckpointSource = "BASETEN_TRAINING"
const CheckpointSourceGCS CheckpointSource = "GCS"
const CheckpointSourceHF CheckpointSource = "HF"
const CheckpointSourceLOCAL CheckpointSource = "LOCAL"
const CheckpointSourceREMOTEURL CheckpointSource = "REMOTE_URL"
const CheckpointSourceS3 CheckpointSource = "S3"

// Configuration options for BIS LLM deployments.
type Config map[string]interface{}

// Provides information about how to authenticate to the docker registry containing
// the custom base image.
type DockerAuthSettings struct {
	// AuthMethod corresponds to the JSON schema field "auth_method".
	AuthMethod DockerAuthType `json:"auth_method" yaml:"auth_method"`

	// AwsAccessKeyIdSecretName corresponds to the JSON schema field
	// "aws_access_key_id_secret_name".
	AwsAccessKeyIdSecretName string `json:"aws_access_key_id_secret_name,omitempty,omitzero" yaml:"aws_access_key_id_secret_name,omitempty"`

	// AWS region for OIDC authentication.
	AwsOidcRegion *string `json:"aws_oidc_region,omitempty,omitzero" yaml:"aws_oidc_region,omitempty"`

	// AWS IAM role ARN for OIDC authentication.
	AwsOidcRoleArn *string `json:"aws_oidc_role_arn,omitempty,omitzero" yaml:"aws_oidc_role_arn,omitempty"`

	// AwsSecretAccessKeySecretName corresponds to the JSON schema field
	// "aws_secret_access_key_secret_name".
	AwsSecretAccessKeySecretName string `json:"aws_secret_access_key_secret_name,omitempty,omitzero" yaml:"aws_secret_access_key_secret_name,omitempty"`

	// GCP service account name for OIDC authentication.
	GcpOidcServiceAccount *string `json:"gcp_oidc_service_account,omitempty,omitzero" yaml:"gcp_oidc_service_account,omitempty"`

	// GCP workload identity provider for OIDC authentication.
	GcpOidcWorkloadIdProvider *string `json:"gcp_oidc_workload_id_provider,omitempty,omitzero" yaml:"gcp_oidc_workload_id_provider,omitempty"`

	// Registry corresponds to the JSON schema field "registry".
	Registry string `json:"registry,omitempty,omitzero" yaml:"registry,omitempty"`

	// SecretName corresponds to the JSON schema field "secret_name".
	SecretName *string `json:"secret_name,omitempty,omitzero" yaml:"secret_name,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type DockerAuthType string

const DockerAuthTypeAWSIAM DockerAuthType = "AWS_IAM"
const DockerAuthTypeAWSOIDC DockerAuthType = "AWS_OIDC"
const DockerAuthTypeGCPOIDC DockerAuthType = "GCP_OIDC"
const DockerAuthTypeGCPSERVICEACCOUNTJSON DockerAuthType = "GCP_SERVICE_ACCOUNT_JSON"
const DockerAuthTypeREGISTRYSECRET DockerAuthType = "REGISTRY_SECRET"

// Deploy a custom Docker image that has its own HTTP server, without writing a
// Model class.
type DockerServer struct {
	// The endpoint for liveness probes. Determines if the container needs to be
	// restarted.
	LivenessEndpoint string `json:"liveness_endpoint" yaml:"liveness_endpoint"`

	// Skip the build step and deploy the base image as-is. Baseten copies the image
	// to its container registry without running docker build or modifying the image
	// in any way.
	NoBuild *bool `json:"no_build,omitempty,omitzero" yaml:"no_build,omitempty"`

	// The endpoint for inference requests. This is mapped to Baseten's /predict
	// route.
	PredictEndpoint string `json:"predict_endpoint" yaml:"predict_endpoint"`

	// The endpoint for readiness probes. Determines when the container can accept
	// traffic.
	ReadinessEndpoint string `json:"readiness_endpoint" yaml:"readiness_endpoint"`

	// The Linux UID to run the server process as inside the container. Use this when
	// your base image expects a specific non-root user (for example, NVIDIA NIM
	// containers).
	RunAsUserId *int `json:"run_as_user_id,omitempty,omitzero" yaml:"run_as_user_id,omitempty"`

	// The port where the server runs. Port 8080 is reserved by Baseten's internal
	// reverse proxy and cannot be used.
	ServerPort int `json:"server_port" yaml:"server_port"`

	// The command to start the server. Required when no_build is not true.
	StartCommand *string `json:"start_command,omitempty,omitzero" yaml:"start_command,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Key-value pairs exposed to the environment that the model executes in. Do not
// store secret values here.
type EnvironmentVariables map[string]string

// [Experimental] External data is data that is not contained in the Truss folder.
//
// Typically, this will be data stored remotely. This data is guaranteed to be made
// available under the data directory of the truss.
type ExternalData []ExternalDataItem

// A piece of remote data, to be made available to the Truss at serving time.
//
// Remote data is downloaded and stored under Truss's data directory. Care should
// be taken
// to avoid conflicts. This will get precedence if there's overlap.
type ExternalDataItem struct {
	// Download backend to use. Defaults to 'http_public'.
	Backend string `json:"backend,omitempty,omitzero" yaml:"backend,omitempty"`

	// Path relative to the data directory where the remote file will be downloaded.
	LocalDataPath string `json:"local_data_path" yaml:"local_data_path"`

	// Optional name for the download. Path relative to data directory.
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty"`

	// URL to download the data from. Currently only files are allowed.
	Url string `json:"url" yaml:"url"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type GRPCOptions struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`
}

type HTTPOptions struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`
}

// Custom health check configuration for your deployments.
type HealthChecks struct {
	// The delay in seconds before starting restart checks. Defaults to
	// platform-determined value when not set.
	RestartCheckDelaySeconds *int `json:"restart_check_delay_seconds,omitempty,omitzero" yaml:"restart_check_delay_seconds,omitempty"`

	// The time in seconds after which an unhealthy instance is restarted. Defaults to
	// platform-determined value when not set.
	RestartThresholdSeconds *int `json:"restart_threshold_seconds,omitempty,omitzero" yaml:"restart_threshold_seconds,omitempty"`

	// The time in seconds to wait for a model to start before marking it as
	// unhealthy. Defaults to platform-determined value when not set.
	StartupThresholdSeconds *int `json:"startup_threshold_seconds,omitempty,omitzero" yaml:"startup_threshold_seconds,omitempty"`

	// The time in seconds after which traffic is stopped to an unhealthy instance.
	// Defaults to platform-determined value when not set.
	StopTrafficThresholdSeconds *int `json:"stop_traffic_threshold_seconds,omitempty,omitzero" yaml:"stop_traffic_threshold_seconds,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type LoraAdapters map[string]interface{}

type ModelCache []ModelRepo

// Configuration for a Truss model deployment.
type ModelConfig struct {
	// Whether to apply library patches for improved compatibility.
	ApplyLibraryPatches bool `json:"apply_library_patches,omitempty,omitzero" yaml:"apply_library_patches,omitempty"`

	// Use a custom Docker base image instead of the default Truss image.
	BaseImage *BaseImage `json:"base_image,omitempty,omitzero" yaml:"base_image,omitempty"`

	// Configuration options for BIS LLM deployments. This field may change in the
	// future.
	BisLlm *BISLLM `json:"bis_llm,omitempty,omitzero" yaml:"bis_llm,omitempty"`

	// Build corresponds to the JSON schema field "build".
	Build *Build `json:"build,omitempty,omitzero" yaml:"build,omitempty"`

	// A list of shell commands to run during Docker build. These commands execute
	// after system packages and Python requirements are installed.
	BuildCommands []string `json:"build_commands,omitempty,omitzero" yaml:"build_commands,omitempty"`

	// The folder for custom packages in your Truss.
	BundledPackagesDir string `json:"bundled_packages_dir,omitempty,omitzero" yaml:"bundled_packages_dir,omitempty"`

	// CacheInternal corresponds to the JSON schema field "cache_internal".
	CacheInternal CacheInternal `json:"cache_internal,omitempty,omitzero" yaml:"cache_internal,omitempty"`

	// The folder for data files in your Truss.
	DataDir string `json:"data_dir,omitempty,omitzero" yaml:"data_dir,omitempty"`

	// A description of your model.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty"`

	// Deploy a custom Docker image that has its own HTTP server, without writing a
	// Model class.
	DockerServer *DockerServer `json:"docker_server,omitempty,omitzero" yaml:"docker_server,omitempty"`

	// Key-value pairs exposed to the environment that the model executes in. Do not
	// store secret values here.
	EnvironmentVariables EnvironmentVariables `json:"environment_variables,omitempty,omitzero" yaml:"environment_variables,omitempty"`

	// Path to a file containing example model inputs.
	ExamplesFilename string `json:"examples_filename,omitempty,omitzero" yaml:"examples_filename,omitempty"`

	// External data to be downloaded and made available under the data directory at
	// serving time.
	ExternalData ExternalData `json:"external_data,omitempty,omitzero" yaml:"external_data,omitempty"`

	// Use external_package_dirs to access custom packages located outside your Truss.
	// This lets multiple Trusses share the same package.
	ExternalPackageDirs []string `json:"external_package_dirs,omitempty,omitzero" yaml:"external_package_dirs,omitempty"`

	// InputType corresponds to the JSON schema field "input_type".
	InputType string `json:"input_type,omitempty,omitzero" yaml:"input_type,omitempty"`

	// If true, changes to your model code are automatically reloaded without
	// restarting the server.
	LiveReload bool `json:"live_reload,omitempty,omitzero" yaml:"live_reload,omitempty"`

	// Deprecated. Use 'weights' instead. Bundle model weights into your image at
	// build time.
	ModelCache ModelCache `json:"model_cache,omitempty,omitzero" yaml:"model_cache,omitempty"`

	// ModelClassFilename corresponds to the JSON schema field "model_class_filename".
	ModelClassFilename string `json:"model_class_filename,omitempty,omitzero" yaml:"model_class_filename,omitempty"`

	// The name of the class that defines your Truss model. This class must implement
	// at least a predict method.
	ModelClassName string `json:"model_class_name,omitempty,omitzero" yaml:"model_class_name,omitempty"`

	// ModelFramework corresponds to the JSON schema field "model_framework".
	ModelFramework string `json:"model_framework,omitempty,omitzero" yaml:"model_framework,omitempty"`

	// A flexible field for additional metadata. The entire config file is available
	// to your model at runtime.
	ModelMetadata *ModelMetadata `json:"model_metadata,omitempty,omitzero" yaml:"model_metadata,omitempty"`

	// The folder containing your model class.
	ModelModuleDir string `json:"model_module_dir,omitempty,omitzero" yaml:"model_module_dir,omitempty"`

	// The name of your model. This is displayed in the model details page in the
	// Baseten UI.
	ModelName *string `json:"model_name,omitempty,omitzero" yaml:"model_name,omitempty"`

	// ModelType corresponds to the JSON schema field "model_type".
	ModelType string `json:"model_type,omitempty,omitzero" yaml:"model_type,omitempty"`

	// The Python version to use.
	PythonVersion string `json:"python_version,omitempty,omitzero" yaml:"python_version,omitempty"`

	// A list of Python dependencies in pip requirements file format. Mutually
	// exclusive with 'requirements_file'.
	Requirements []string `json:"requirements,omitempty,omitzero" yaml:"requirements,omitempty"`

	// Path to a dependency file. Supports requirements.txt, pyproject.toml, and
	// uv.lock. Mutually exclusive with 'requirements'.
	RequirementsFile *string `json:"requirements_file,omitempty,omitzero" yaml:"requirements_file,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *Resources `json:"resources,omitempty,omitzero" yaml:"resources,omitempty"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime *Runtime `json:"runtime,omitempty,omitzero" yaml:"runtime,omitempty"`

	// Declare secrets your model needs at runtime, such as API keys or access tokens.
	// Use null as a placeholder; store actual values in your organization settings.
	Secrets Secrets `json:"secrets,omitempty,omitzero" yaml:"secrets,omitempty"`

	// SpecVersion corresponds to the JSON schema field "spec_version".
	SpecVersion string `json:"spec_version,omitempty,omitzero" yaml:"spec_version,omitempty"`

	// System packages that you would typically install using apt on a Debian
	// operating system.
	SystemPackages []string `json:"system_packages,omitempty,omitzero" yaml:"system_packages,omitempty"`

	// Configuration for deploying from training checkpoints.
	TrainingCheckpoints *CheckpointList `json:"training_checkpoints,omitempty,omitzero" yaml:"training_checkpoints,omitempty"`

	// TensorRT-LLM configuration for optimized LLM inference.
	TrtLlm TRTLLMConfiguration `json:"trt_llm,omitempty,omitzero" yaml:"trt_llm,omitempty"`

	// UseLocalSrc corresponds to the JSON schema field "use_local_src".
	UseLocalSrc bool `json:"use_local_src,omitempty,omitzero" yaml:"use_local_src,omitempty"`

	// Configure Baseten Delivery Network (BDN) for model weight delivery with
	// multi-tier caching.
	Weights Weights `json:"weights,omitempty,omitzero" yaml:"weights,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// A flexible field for additional metadata. The entire config file is available to
// your model at runtime.
type ModelMetadata struct {
	// Sample input that populates the Baseten playground.
	ExampleModelInput interface{} `json:"example_model_input,omitempty,omitzero" yaml:"example_model_input,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelRepo struct {
	// AllowPatterns corresponds to the JSON schema field "allow_patterns".
	AllowPatterns []string `json:"allow_patterns,omitempty,omitzero" yaml:"allow_patterns,omitempty"`

	// IgnorePatterns corresponds to the JSON schema field "ignore_patterns".
	IgnorePatterns []string `json:"ignore_patterns,omitempty,omitzero" yaml:"ignore_patterns,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ModelRepoSourceKind `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`

	// RepoId corresponds to the JSON schema field "repo_id".
	RepoId string `json:"repo_id" yaml:"repo_id"`

	// Revision corresponds to the JSON schema field "revision".
	Revision string `json:"revision,omitempty,omitzero" yaml:"revision,omitempty"`

	// RuntimeSecretName corresponds to the JSON schema field "runtime_secret_name".
	RuntimeSecretName string `json:"runtime_secret_name,omitempty,omitzero" yaml:"runtime_secret_name,omitempty"`

	// UseVolume corresponds to the JSON schema field "use_volume".
	UseVolume bool `json:"use_volume" yaml:"use_volume"`

	// VolumeFolder corresponds to the JSON schema field "volume_folder".
	VolumeFolder *string `json:"volume_folder,omitempty,omitzero" yaml:"volume_folder,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelRepoCacheInternal struct {
	// AllowPatterns corresponds to the JSON schema field "allow_patterns".
	AllowPatterns []string `json:"allow_patterns,omitempty,omitzero" yaml:"allow_patterns,omitempty"`

	// IgnorePatterns corresponds to the JSON schema field "ignore_patterns".
	IgnorePatterns []string `json:"ignore_patterns,omitempty,omitzero" yaml:"ignore_patterns,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ModelRepoSourceKind `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`

	// RepoId corresponds to the JSON schema field "repo_id".
	RepoId string `json:"repo_id" yaml:"repo_id"`

	// Revision corresponds to the JSON schema field "revision".
	Revision string `json:"revision,omitempty,omitzero" yaml:"revision,omitempty"`

	// RuntimeSecretName corresponds to the JSON schema field "runtime_secret_name".
	RuntimeSecretName string `json:"runtime_secret_name,omitempty,omitzero" yaml:"runtime_secret_name,omitempty"`

	// UseVolume corresponds to the JSON schema field "use_volume".
	UseVolume bool `json:"use_volume,omitempty,omitzero" yaml:"use_volume,omitempty"`

	// VolumeFolder corresponds to the JSON schema field "volume_folder".
	VolumeFolder *string `json:"volume_folder,omitempty,omitzero" yaml:"volume_folder,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelRepoSourceKind string

const ModelRepoSourceKindAzure ModelRepoSourceKind = "azure"
const ModelRepoSourceKindGcs ModelRepoSourceKind = "gcs"
const ModelRepoSourceKindHf ModelRepoSourceKind = "hf"
const ModelRepoSourceKindS3 ModelRepoSourceKind = "s3"

type ModelServer string

const ModelServerTRTLLM ModelServer = "TRT_LLM"
const ModelServerTrussServer ModelServer = "TrussServer"

type ModelSpecDecMode string

const ModelSpecDecModeDRAFTTOKENSEXTERNAL ModelSpecDecMode = "DRAFT_TOKENS_EXTERNAL"
const ModelSpecDecModeLOOKAHEADDECODING ModelSpecDecMode = "LOOKAHEAD_DECODING"

type ModelSpeculatorConfiguration struct {
	// Build corresponds to the JSON schema field "build".
	Build *ModelTRTLLMBuildConfiguration `json:"build,omitempty,omitzero" yaml:"build,omitempty"`

	// CheckpointRepository corresponds to the JSON schema field
	// "checkpoint_repository".
	CheckpointRepository *CheckpointRepository `json:"checkpoint_repository,omitempty,omitzero" yaml:"checkpoint_repository,omitempty"`

	// EnableB10Lookahead corresponds to the JSON schema field "enable_b10_lookahead".
	EnableB10Lookahead bool `json:"enable_b10_lookahead,omitempty,omitzero" yaml:"enable_b10_lookahead,omitempty"`

	// LookaheadNgramSize corresponds to the JSON schema field "lookahead_ngram_size".
	LookaheadNgramSize *int `json:"lookahead_ngram_size,omitempty,omitzero" yaml:"lookahead_ngram_size,omitempty"`

	// LookaheadVerificationSetSize corresponds to the JSON schema field
	// "lookahead_verification_set_size".
	LookaheadVerificationSetSize *int `json:"lookahead_verification_set_size,omitempty,omitzero" yaml:"lookahead_verification_set_size,omitempty"`

	// LookaheadWindowsSize corresponds to the JSON schema field
	// "lookahead_windows_size".
	LookaheadWindowsSize *int `json:"lookahead_windows_size,omitempty,omitzero" yaml:"lookahead_windows_size,omitempty"`

	// NumDraftTokens corresponds to the JSON schema field "num_draft_tokens".
	NumDraftTokens *int `json:"num_draft_tokens,omitempty,omitzero" yaml:"num_draft_tokens,omitempty"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime ModelTRTLLMRuntimeConfiguration `json:"runtime,omitempty,omitzero" yaml:"runtime,omitempty"`

	// SpeculativeDecodingMode corresponds to the JSON schema field
	// "speculative_decoding_mode".
	SpeculativeDecodingMode ModelSpecDecMode `json:"speculative_decoding_mode,omitempty,omitzero" yaml:"speculative_decoding_mode,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelTRTLLMBatchSchedulerPolicy string

const ModelTRTLLMBatchSchedulerPolicyGuaranteedNoEvict ModelTRTLLMBatchSchedulerPolicy = "guaranteed_no_evict"
const ModelTRTLLMBatchSchedulerPolicyMaxUtilization ModelTRTLLMBatchSchedulerPolicy = "max_utilization"

type ModelTRTLLMBuildConfiguration struct {
	// BaseModel corresponds to the JSON schema field "base_model".
	BaseModel ModelTRTLLMModel `json:"base_model,omitempty,omitzero" yaml:"base_model,omitempty"`

	// CheckpointRepository corresponds to the JSON schema field
	// "checkpoint_repository".
	CheckpointRepository *CheckpointRepository `json:"checkpoint_repository,omitempty,omitzero" yaml:"checkpoint_repository,omitempty"`

	// GatherAllTokenLogits corresponds to the JSON schema field
	// "gather_all_token_logits".
	GatherAllTokenLogits bool `json:"gather_all_token_logits,omitempty,omitzero" yaml:"gather_all_token_logits,omitempty"`

	// LoraAdapters corresponds to the JSON schema field "lora_adapters".
	LoraAdapters LoraAdapters `json:"lora_adapters,omitempty,omitzero" yaml:"lora_adapters,omitempty"`

	// LoraConfiguration corresponds to the JSON schema field "lora_configuration".
	LoraConfiguration *ModelTRTLLMLoraConfiguration `json:"lora_configuration,omitempty,omitzero" yaml:"lora_configuration,omitempty"`

	// MaxBatchSize corresponds to the JSON schema field "max_batch_size".
	MaxBatchSize int `json:"max_batch_size,omitempty,omitzero" yaml:"max_batch_size,omitempty"`

	// MaxBeamWidth corresponds to the JSON schema field "max_beam_width".
	MaxBeamWidth int `json:"max_beam_width,omitempty,omitzero" yaml:"max_beam_width,omitempty"`

	// MaxNumTokens corresponds to the JSON schema field "max_num_tokens".
	MaxNumTokens int `json:"max_num_tokens,omitempty,omitzero" yaml:"max_num_tokens,omitempty"`

	// MaxPromptEmbeddingTableSize corresponds to the JSON schema field
	// "max_prompt_embedding_table_size".
	MaxPromptEmbeddingTableSize int `json:"max_prompt_embedding_table_size,omitempty,omitzero" yaml:"max_prompt_embedding_table_size,omitempty"`

	// MaxSeqLen corresponds to the JSON schema field "max_seq_len".
	MaxSeqLen *int `json:"max_seq_len,omitempty,omitzero" yaml:"max_seq_len,omitempty"`

	// MoeExpertParallelOption corresponds to the JSON schema field
	// "moe_expert_parallel_option".
	MoeExpertParallelOption int `json:"moe_expert_parallel_option,omitempty,omitzero" yaml:"moe_expert_parallel_option,omitempty"`

	// NumBuilderGpus corresponds to the JSON schema field "num_builder_gpus".
	NumBuilderGpus *int `json:"num_builder_gpus,omitempty,omitzero" yaml:"num_builder_gpus,omitempty"`

	// PipelineParallelCount corresponds to the JSON schema field
	// "pipeline_parallel_count".
	PipelineParallelCount int `json:"pipeline_parallel_count,omitempty,omitzero" yaml:"pipeline_parallel_count,omitempty"`

	// PluginConfiguration corresponds to the JSON schema field
	// "plugin_configuration".
	PluginConfiguration ModelTRTLLMPluginConfiguration `json:"plugin_configuration,omitempty,omitzero" yaml:"plugin_configuration,omitempty"`

	// QuantizationConfig corresponds to the JSON schema field "quantization_config".
	QuantizationConfig ModelTRTQuantizationConfiguration `json:"quantization_config,omitempty,omitzero" yaml:"quantization_config,omitempty"`

	// QuantizationType corresponds to the JSON schema field "quantization_type".
	QuantizationType ModelTRTLLMQuantizationType `json:"quantization_type,omitempty,omitzero" yaml:"quantization_type,omitempty"`

	// SequenceParallelCount corresponds to the JSON schema field
	// "sequence_parallel_count".
	SequenceParallelCount int `json:"sequence_parallel_count,omitempty,omitzero" yaml:"sequence_parallel_count,omitempty"`

	// SkipBuildResult corresponds to the JSON schema field "skip_build_result".
	SkipBuildResult bool `json:"skip_build_result,omitempty,omitzero" yaml:"skip_build_result,omitempty"`

	// Speculator corresponds to the JSON schema field "speculator".
	Speculator *ModelSpeculatorConfiguration `json:"speculator,omitempty,omitzero" yaml:"speculator,omitempty"`

	// StronglyTyped corresponds to the JSON schema field "strongly_typed".
	StronglyTyped bool `json:"strongly_typed,omitempty,omitzero" yaml:"strongly_typed,omitempty"`

	// TensorParallelCount corresponds to the JSON schema field
	// "tensor_parallel_count".
	TensorParallelCount int `json:"tensor_parallel_count,omitempty,omitzero" yaml:"tensor_parallel_count,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelTRTLLMLoraConfiguration struct {
	// LoraTargetModules corresponds to the JSON schema field "lora_target_modules".
	LoraTargetModules []string `json:"lora_target_modules,omitempty,omitzero" yaml:"lora_target_modules,omitempty"`

	// MaxLoraRank corresponds to the JSON schema field "max_lora_rank".
	MaxLoraRank int `json:"max_lora_rank,omitempty,omitzero" yaml:"max_lora_rank,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelTRTLLMModel string

const ModelTRTLLMModelDecoder ModelTRTLLMModel = "decoder"
const ModelTRTLLMModelDeepseek ModelTRTLLMModel = "deepseek"
const ModelTRTLLMModelEncoder ModelTRTLLMModel = "encoder"
const ModelTRTLLMModelEncoderBert ModelTRTLLMModel = "encoder_bert"
const ModelTRTLLMModelLlama ModelTRTLLMModel = "llama"
const ModelTRTLLMModelMistral ModelTRTLLMModel = "mistral"
const ModelTRTLLMModelPalmyra ModelTRTLLMModel = "palmyra"
const ModelTRTLLMModelQwen ModelTRTLLMModel = "qwen"
const ModelTRTLLMModelWhisper ModelTRTLLMModel = "whisper"

type ModelTRTLLMPluginConfiguration struct {
	// PagedKvCache corresponds to the JSON schema field "paged_kv_cache".
	PagedKvCache bool `json:"paged_kv_cache,omitempty,omitzero" yaml:"paged_kv_cache,omitempty"`

	// UseFp8ContextFmha corresponds to the JSON schema field "use_fp8_context_fmha".
	UseFp8ContextFmha bool `json:"use_fp8_context_fmha,omitempty,omitzero" yaml:"use_fp8_context_fmha,omitempty"`

	// UsePagedContextFmha corresponds to the JSON schema field
	// "use_paged_context_fmha".
	UsePagedContextFmha bool `json:"use_paged_context_fmha,omitempty,omitzero" yaml:"use_paged_context_fmha,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelTRTLLMQuantizationType string

const ModelTRTLLMQuantizationTypeFp4 ModelTRTLLMQuantizationType = "fp4"
const ModelTRTLLMQuantizationTypeFp4Kv ModelTRTLLMQuantizationType = "fp4_kv"
const ModelTRTLLMQuantizationTypeFp4MlpOnly ModelTRTLLMQuantizationType = "fp4_mlp_only"
const ModelTRTLLMQuantizationTypeFp8 ModelTRTLLMQuantizationType = "fp8"
const ModelTRTLLMQuantizationTypeFp8Kv ModelTRTLLMQuantizationType = "fp8_kv"
const ModelTRTLLMQuantizationTypeNoQuant ModelTRTLLMQuantizationType = "no_quant"
const ModelTRTLLMQuantizationTypeSmoothQuant ModelTRTLLMQuantizationType = "smooth_quant"
const ModelTRTLLMQuantizationTypeWeightsInt4 ModelTRTLLMQuantizationType = "weights_int4"
const ModelTRTLLMQuantizationTypeWeightsInt4KvInt8 ModelTRTLLMQuantizationType = "weights_int4_kv_int8"
const ModelTRTLLMQuantizationTypeWeightsInt8 ModelTRTLLMQuantizationType = "weights_int8"
const ModelTRTLLMQuantizationTypeWeightsKvInt8 ModelTRTLLMQuantizationType = "weights_kv_int8"

type ModelTRTLLMRuntimeConfiguration struct {
	// BatchSchedulerPolicy corresponds to the JSON schema field
	// "batch_scheduler_policy".
	BatchSchedulerPolicy ModelTRTLLMBatchSchedulerPolicy `json:"batch_scheduler_policy,omitempty,omitzero" yaml:"batch_scheduler_policy,omitempty"`

	// EnableChunkedContext corresponds to the JSON schema field
	// "enable_chunked_context".
	EnableChunkedContext bool `json:"enable_chunked_context,omitempty,omitzero" yaml:"enable_chunked_context,omitempty"`

	// KvCacheFreeGpuMemFraction corresponds to the JSON schema field
	// "kv_cache_free_gpu_mem_fraction".
	KvCacheFreeGpuMemFraction float64 `json:"kv_cache_free_gpu_mem_fraction,omitempty,omitzero" yaml:"kv_cache_free_gpu_mem_fraction,omitempty"`

	// KvCacheHostMemoryBytes corresponds to the JSON schema field
	// "kv_cache_host_memory_bytes".
	KvCacheHostMemoryBytes *int `json:"kv_cache_host_memory_bytes,omitempty,omitzero" yaml:"kv_cache_host_memory_bytes,omitempty"`

	// RequestDefaultMaxTokens corresponds to the JSON schema field
	// "request_default_max_tokens".
	RequestDefaultMaxTokens *int `json:"request_default_max_tokens,omitempty,omitzero" yaml:"request_default_max_tokens,omitempty"`

	// ServedModelName corresponds to the JSON schema field "served_model_name".
	ServedModelName *string `json:"served_model_name,omitempty,omitzero" yaml:"served_model_name,omitempty"`

	// TotalTokenLimit corresponds to the JSON schema field "total_token_limit".
	TotalTokenLimit int `json:"total_token_limit,omitempty,omitzero" yaml:"total_token_limit,omitempty"`

	// WebserverDefaultRoute corresponds to the JSON schema field
	// "webserver_default_route".
	WebserverDefaultRoute *ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute `json:"webserver_default_route,omitempty,omitzero" yaml:"webserver_default_route,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute string

const ModelTRTLLMRuntimeConfigurationWebserverDefaultRoutePredict ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute = "/predict"
const ModelTRTLLMRuntimeConfigurationWebserverDefaultRoutePredictTokens ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute = "/predict_tokens"
const ModelTRTLLMRuntimeConfigurationWebserverDefaultRouteRerank ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute = "/rerank"
const ModelTRTLLMRuntimeConfigurationWebserverDefaultRouteV1Embeddings ModelTRTLLMRuntimeConfigurationWebserverDefaultRoute = "/v1/embeddings"

// Configuration for quantization of TRT models
//
// Args:
//
//	calib_size (int, optional): Size of calibration dataset. Defaults to 1024.
//	    recommended to increase for production runs (e.g. 1536), or decrease
//
// e.g. to 256 for quick testing.
//
//	calib_dataset (str, optional): Hugginface dataset to use for calibration.
//
// Defaults to 'cnn_dailymail'.
//
//	    uses split='train' and  quantized based on 'text' column.
//	calib_max_seq_length (int, optional): Maximum sequence length for
//
// calibration. Defaults to 2048.
type ModelTRTQuantizationConfiguration struct {
	// CalibDataset corresponds to the JSON schema field "calib_dataset".
	CalibDataset string `json:"calib_dataset,omitempty,omitzero" yaml:"calib_dataset,omitempty"`

	// CalibMaxSeqLength corresponds to the JSON schema field "calib_max_seq_length".
	CalibMaxSeqLength int `json:"calib_max_seq_length,omitempty,omitzero" yaml:"calib_max_seq_length,omitempty"`

	// CalibSize corresponds to the JSON schema field "calib_size".
	CalibSize int `json:"calib_size,omitempty,omitzero" yaml:"calib_size,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type PatchKwargs map[string]interface{}

// Configuration for SSH access to running model instances.
type RemoteSSH struct {
	// If true, enables SSH access to running model instances.
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Compute resources that your model needs, including CPU, memory, and GPU
// resources.
type Resources struct {
	// The GPU type for your instance. To request multiple GPUs, use the ':' operator
	// (e.g. L4:4).
	Accelerator *AcceleratorSpec `json:"accelerator,omitempty,omitzero" yaml:"accelerator,omitempty"`

	// CPU resources needed, expressed as either a raw number or millicpus. For
	// example, 500m is half of a CPU core.
	Cpu string `json:"cpu,omitempty,omitzero" yaml:"cpu,omitempty"`

	// The full SKU name for the instance type. When specified, cpu, memory, and
	// accelerator fields are ignored.
	InstanceType *string `json:"instance_type,omitempty,omitzero" yaml:"instance_type,omitempty"`

	// CPU RAM needed, expressed as a number with units. Units include Gi (Gibibytes),
	// G (Gigabytes), Mi (Mebibytes), and M (Megabytes).
	Memory string `json:"memory,omitempty,omitzero" yaml:"memory,omitempty"`

	// Number of nodes for multi-node deployments.
	NodeCount *int `json:"node_count,omitempty,omitzero" yaml:"node_count,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Runtime settings for your model instance.
type Runtime struct {
	// If true, sets the Truss server log level to DEBUG instead of INFO.
	EnableDebugLogs bool `json:"enable_debug_logs,omitempty,omitzero" yaml:"enable_debug_logs,omitempty"`

	// If true, enables trace data export with built-in OTEL instrumentation. May add
	// performance overhead.
	EnableTracingData bool `json:"enable_tracing_data,omitempty,omitzero" yaml:"enable_tracing_data,omitempty"`

	// HealthChecks corresponds to the JSON schema field "health_checks".
	HealthChecks *HealthChecks `json:"health_checks,omitempty,omitzero" yaml:"health_checks,omitempty"`

	// DEPRECATED. Do not set manually. Automatically inferred from transport.kind ==
	// websocket.
	IsWebsocketEndpoint *bool `json:"is_websocket_endpoint,omitempty,omitzero" yaml:"is_websocket_endpoint,omitempty"`

	// The number of concurrent requests that can run in your model's predict method.
	// Increase this if your model supports parallelism.
	PredictConcurrency int `json:"predict_concurrency,omitempty,omitzero" yaml:"predict_concurrency,omitempty"`

	// RemoteSsh corresponds to the JSON schema field "remote_ssh".
	RemoteSsh *RemoteSSH `json:"remote_ssh,omitempty,omitzero" yaml:"remote_ssh,omitempty"`

	// The timeout in seconds for streaming read operations.
	StreamingReadTimeout int `json:"streaming_read_timeout,omitempty,omitzero" yaml:"streaming_read_timeout,omitempty"`

	// The transport protocol for your model. Supports http (default), websocket, and
	// grpc.
	Transport interface{} `json:"transport,omitempty,omitzero" yaml:"transport,omitempty"`

	// By default, truss servers are built from the same release as the CLI used to
	// push. This field allows specifying a pinned/specific version instead.
	TrussServerVersionOverride *string `json:"truss_server_version_override,omitempty,omitzero" yaml:"truss_server_version_override,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// Grants access to secrets during the build. Provide a mapping between a secret
// and a path on the image.
type SecretToPathMapping map[string]string

// Declare secrets your model needs at runtime, such as API keys or access tokens.
// Use null as a placeholder; store actual values in your organization settings.
type Secrets map[string]interface{}

type TRTLLMConfiguration interface{}

type TRTLLMConfigurationV1 struct {
	// Build corresponds to the JSON schema field "build".
	Build ModelTRTLLMBuildConfiguration `json:"build" yaml:"build"`

	// InferenceStack corresponds to the JSON schema field "inference_stack".
	InferenceStack string `json:"inference_stack,omitempty,omitzero" yaml:"inference_stack,omitempty"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime ModelTRTLLMRuntimeConfiguration `json:"runtime,omitempty,omitzero" yaml:"runtime,omitempty"`

	// VersionOverrides corresponds to the JSON schema field "version_overrides".
	VersionOverrides VersionsOverrides `json:"version_overrides,omitempty,omitzero" yaml:"version_overrides,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type TRTLLMConfigurationV2 struct {
	// Build corresponds to the JSON schema field "build".
	Build ModelTRTLLMBuildConfiguration `json:"build" yaml:"build"`

	// InferenceStack corresponds to the JSON schema field "inference_stack".
	InferenceStack string `json:"inference_stack,omitempty,omitzero" yaml:"inference_stack,omitempty"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime TRTLLMRuntimeConfigurationV2 `json:"runtime" yaml:"runtime"`

	// VersionOverrides corresponds to the JSON schema field "version_overrides".
	VersionOverrides VersionsOverrides `json:"version_overrides,omitempty,omitzero" yaml:"version_overrides,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type TRTLLMRuntimeConfigurationV2 struct {
	// EnableChunkedPrefill corresponds to the JSON schema field
	// "enable_chunked_prefill".
	EnableChunkedPrefill bool `json:"enable_chunked_prefill,omitempty,omitzero" yaml:"enable_chunked_prefill,omitempty"`

	// MaxBatchSize corresponds to the JSON schema field "max_batch_size".
	MaxBatchSize int `json:"max_batch_size,omitempty,omitzero" yaml:"max_batch_size,omitempty"`

	// MaxNumTokens corresponds to the JSON schema field "max_num_tokens".
	MaxNumTokens int `json:"max_num_tokens,omitempty,omitzero" yaml:"max_num_tokens,omitempty"`

	// MaxSeqLen corresponds to the JSON schema field "max_seq_len".
	MaxSeqLen *int `json:"max_seq_len,omitempty,omitzero" yaml:"max_seq_len,omitempty"`

	// PatchKwargs corresponds to the JSON schema field "patch_kwargs".
	PatchKwargs PatchKwargs `json:"patch_kwargs,omitempty,omitzero" yaml:"patch_kwargs,omitempty"`

	// ServedModelName corresponds to the JSON schema field "served_model_name".
	ServedModelName *string `json:"served_model_name,omitempty,omitzero" yaml:"served_model_name,omitempty"`

	// TensorParallelSize corresponds to the JSON schema field "tensor_parallel_size".
	TensorParallelSize int `json:"tensor_parallel_size,omitempty,omitzero" yaml:"tensor_parallel_size,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type TrainingArtifactReference struct {
	// The paths of the files to download which can contain * or ?.
	Paths []string `json:"paths,omitempty,omitzero" yaml:"paths,omitempty"`

	// The training job id that the artifact reference belongs to.
	TrainingJobId string `json:"training_job_id" yaml:"training_job_id"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type VersionsOverrides struct {
	// BeiBertVersion corresponds to the JSON schema field "bei_bert_version".
	BeiBertVersion *string `json:"bei_bert_version,omitempty,omitzero" yaml:"bei_bert_version,omitempty"`

	// BeiVersion corresponds to the JSON schema field "bei_version".
	BeiVersion *string `json:"bei_version,omitempty,omitzero" yaml:"bei_version,omitempty"`

	// BritonVersion corresponds to the JSON schema field "briton_version".
	BritonVersion *string `json:"briton_version,omitempty,omitzero" yaml:"briton_version,omitempty"`

	// EngineBuilderVersion corresponds to the JSON schema field
	// "engine_builder_version".
	EngineBuilderVersion *string `json:"engine_builder_version,omitempty,omitzero" yaml:"engine_builder_version,omitempty"`

	// V2LlmVersion corresponds to the JSON schema field "v2_llm_version".
	V2LlmVersion *string `json:"v2_llm_version,omitempty,omitzero" yaml:"v2_llm_version,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type WebsocketOptions struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind,omitempty,omitzero" yaml:"kind,omitempty"`

	// PingIntervalSeconds corresponds to the JSON schema field
	// "ping_interval_seconds".
	PingIntervalSeconds *float64 `json:"ping_interval_seconds,omitempty,omitzero" yaml:"ping_interval_seconds,omitempty"`

	// PingTimeoutSeconds corresponds to the JSON schema field "ping_timeout_seconds".
	PingTimeoutSeconds *float64 `json:"ping_timeout_seconds,omitempty,omitzero" yaml:"ping_timeout_seconds,omitempty"`
}

// List of weights sources for the new weights API.
type Weights []WeightsSource

// Authentication configuration for a weights source.
//
// This can be used to specify OIDC-based authentication for cloud storage sources,
// or a Baseten secret name for access key authentication.
type WeightsAuth struct {
	// Authentication method for downloading weights from the source.
	AuthMethod WeightsAuthMethod `json:"auth_method" yaml:"auth_method"`

	// Baseten secret name containing credentials for accessing the source.
	AuthSecretName *string `json:"auth_secret_name,omitempty,omitzero" yaml:"auth_secret_name,omitempty"`

	// AWS region for OIDC authentication.
	AwsOidcRegion *string `json:"aws_oidc_region,omitempty,omitzero" yaml:"aws_oidc_region,omitempty"`

	// AWS IAM role ARN for OIDC authentication.
	AwsOidcRoleArn *string `json:"aws_oidc_role_arn,omitempty,omitzero" yaml:"aws_oidc_role_arn,omitempty"`

	// GCP service account name for OIDC authentication.
	GcpOidcServiceAccount *string `json:"gcp_oidc_service_account,omitempty,omitzero" yaml:"gcp_oidc_service_account,omitempty"`

	// GCP workload identity provider for OIDC authentication.
	GcpOidcWorkloadIdProvider *string `json:"gcp_oidc_workload_id_provider,omitempty,omitzero" yaml:"gcp_oidc_workload_id_provider,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type WeightsAuthMethod string

const WeightsAuthMethodAWSOIDC WeightsAuthMethod = "AWS_OIDC"
const WeightsAuthMethodCUSTOMSECRET WeightsAuthMethod = "CUSTOM_SECRET"
const WeightsAuthMethodGCPOIDC WeightsAuthMethod = "GCP_OIDC"

// Configuration for a weights source in the new weights API.
//
// Uses a URI-based `source` field with a required scheme prefix:
// - hf:// -> HuggingFace (e.g., "hf://meta-llama/Llama-2-7b" or
// "hf://meta-llama/Llama-2-7b@main")
// - s3:// -> AWS S3 (e.g., "s3://bucket/path")
// - gs:// -> Google Cloud Storage (e.g., "gs://bucket/path")
// - azure:// -> Azure Blob Storage (e.g., "azure://account/container/path")
// - r2:// -> CloudFlare R2 Storage (e.g., "r2://account_id.bucket/path")
// - https:// -> Direct URL download (e.g., "https://example.com/model.bin")
//
// For HuggingFace sources, you can specify a revision (branch, tag, or commit SHA)
// using the @{rev} suffix: "hf://owner/repo@revision"
//
// Authentication can be specified either:
//   - Using the `auth` section (required for OIDC):
//     auth:
//     auth_method: AWS_OIDC
//     aws_oidc_role_arn: <role_arn>
//     aws_oidc_region: <region>
//   - Using `auth_secret_name` at the top level (or in the `auth` section)
type WeightsSource struct {
	// File patterns to include (e.g., ['*.safetensors']).
	AllowPatterns []string `json:"allow_patterns,omitempty,omitzero" yaml:"allow_patterns,omitempty"`

	// Authentication configuration for accessing the weights source.
	Auth *WeightsAuth `json:"auth,omitempty,omitzero" yaml:"auth,omitempty"`

	// Baseten secret name containing credentials. Can also be specified in
	// auth.auth_secret_name.
	AuthSecretName *string `json:"auth_secret_name,omitempty,omitzero" yaml:"auth_secret_name,omitempty"`

	// File patterns to exclude (e.g., ['*.md']).
	IgnorePatterns []string `json:"ignore_patterns,omitempty,omitzero" yaml:"ignore_patterns,omitempty"`

	// Absolute path where weights will be mounted at runtime.
	MountLocation string `json:"mount_location" yaml:"mount_location"`

	// URI with scheme prefix. Use hf://, s3://, gs://, azure://, r2://, or https://.
	// For HuggingFace, use @revision suffix (e.g., hf://owner/repo@main).
	Source string `json:"source" yaml:"source"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}
